{%include file="header.phtml"%}
{%include file="common/ad_header.phtml"%}

<div id="access">
	<div class="content" style="background:#fff5f5;">
		<div class="headline" style="background:#ff9999;color:#ffffff;text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/access.gif" width="230" height="60" /><br />
			{%*
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			{% emoji code="F8C4" %}{% $activeResInfo.name %}<br />
			*%}
		</div><!--/.headline-->
		{% if !$accessList %}
			<div class="null" style="text-align:center;">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
				まだ誰も来店していません<br />
				<span style="color:#006699;text-decoration:blink;">≫</span><a href='{% "$baseUrl/mobile/kitchen/home"|mixiurl %}'>{% if $uid == $userInfo.uid %}Myレストランへ{% else %}{% $userInfo.displayName%}のﾚｽﾄﾗﾝへ{% /if %}</a><span style="color:#006699;text-decoration:blink;">≪</span>
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
				<div class="line" style="background:#ff9999;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
			</div><!--/.inner-->
		{% else %}
			<div class="inner">
				<div class="count">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					{% $accessCount %}件中 {% $startNm %}-{% $endNm %}件<br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				</div><!--/.count-->
				<div style="background:#ff9999;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
				{% foreach from=$accessList item=data%}
					<div class="section">
						<table width="100%" cellpadding="0" cellspacing="0" border="0">
							<tr>
								<td style="width:44px;text-align:center;"><img src="{%$data.miniThumbnailUrl%}" style="margin:3px 0;" /></td>
								<td><div style="{% if $ua==1 %}font-size:x-small;{% /if %}">
									{% emoji code="F9D1" %}<a href='{% "$baseUrl/mobile/kitchen/home?CF_uid=`$data.visit_uid`"|mixiurl %}'>{%$data.displayName%}</a><br />
									{% if $data.action == 1 %}
										ハエを撃退しました<br />
									{% elseif $data.action == 2 %}
										ハエを投入しました<br />
									{% elseif $data.action == 3 %}
										味付けしました<br />
									{% elseif $data.action == 4 %}
										味見しました<br />
									{% elseif $data.action == 5 %}
										ナデナデしました<br />
									{% /if %}
									<div style="color:#999999;text-align:right;">{% emoji code="F95E" %}{% $data.update_time|date_format:"%m月%d日 %H:%M" %}&nbsp;</div>
	                            </div></td>
							</tr>
						</table>
						<div style="background:#ff9999;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
	                </div><!--/.section-->
				{% /foreach %}
	            {% if $pager.maxPager > 1 %}
					<div class="pager" style="color:#006699;text-align:center;">
						{%include file="common/pager.phtml"%}
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						<div style="background:#ff9999;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
					</div><!--/.pager-->
				{% /if %}
				<div class="toInviteNav" style="text-align:center;">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					{% emoji code="F9CE" %}<a href='{% "invite:friends?callback=$baseUrl/mobile/callback/invite?forward=$baseUrl/mobile/kitchen/invitefinish" %}' style="color:#ea68a2;"><span style="color:#ea68a2;">まだ参加してないﾏｲﾐｸを招待</span></a><br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				</div><!--/.toInviteNav-->
				<div class="footlink">
					<div style="background:#ff9999;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchen/home"|mixiurl %}'>{% if $uid == $userInfo.uid %}Myレストラン{% else %}{% $userInfo.displayName%}のお店{% /if %}</a><br />
				</div><!--/.footlink-->
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="line" style="background:#ff9999;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
			</div><!--/.inner-->
		{% /if %}
	</div><!--/.content-->
</div><!--/#access-->

{%include file="common/menu.phtml"%}
{%include file="ad_footer.phtml"%}