{%include file="header.phtml"%}

<div id="inviteFinish">
	<div class="content" style="background:#ffffdd;">
		<div class="headline" style="background:#ff9933;color:#ffffff;text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/invitation.gif?100205" width="230" height="60" /><br />
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			招待送信完了<br />
		</div><!--/.headline-->
		<div class="inner">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			招待状を送信しました!招待特典の反映は､招待成立後､2-3日お時間をいただくことがありますので､あらかじめご了承ください｡<br />
			{%include file="common/ad_192x106.phtml"%}
			<div class="toRestaurant" style="text-align:center;">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
				<span style="color:#ff9933;">≫</span><a href='{% "$baseUrl/mobile/kitchen/home"|mixiurl %}'>Myレストランへ</a><span style="color:#ff9933;">≪</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
			</div><!--/.toRestaurant-->
		</div><!--/.inner-->
		{%*
			<div class="headline" style="background:#ff9933;color:#ffffff;text-align:center;">
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
				{% emoji code="F99F" %}こちらもオススメ{% emoji code="F99F" %}<br />
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			</div><!--/.headline-->
			<div class="inner">
				<div class="section">
					<div class="banner" style="text-align:center;">
						<img src="{%$staticUrl%}/apps/kitchen/mobile/img/campaign/100206.gif?" width="192" height="53" style="margin-top:3px;" /><br />
						<span style="color:#cc0000;">抽選で総額30000Mﾌﾟﾚｾﾞﾝﾄ!<br />1等:1000M(10名)/2等:500M(20名)</span><br />
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					</div><!--/.banner-->
					<div class="description">
						{% emoji code="F8E4" %}参加条件{% emoji code="F8E4" %}<br />
						3/7までに<span style="color:#cc0000;">友達を3名以上招待</span>した方<br />
						<span style="color:#f16dc0;">招</span><span style="color:#f16dc0;">待</span><span style="color:#ee5564;">人</span><span style="color:#dc4646;">数</span><span style="color:#ec884e;">に</span><span style="color:#ff952e;">応</span><span style="color:#e7b300;">じ</span><span style="color:#eecf02;">て<span style="color:#72c156;">当</span><span style="color:#4fa445;">選</span><span style="color:#62badc;">確</span><span style="color:#1f83cf;">率</span><span style="color:#1854bc;">U</span><span style="color:#0c0c9c;">P</span>{% emoji code="F99A" %}<br />
					</div><!--/.description-->
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<form method="post" action='{% "invite:friends?callback=$baseUrl/mobile/callback/invite?forward=$baseUrl/mobile/kitchen/invitefinish" %}'>
						<div class="btn" style="text-align:center;">
							<input type="submit" value="  続けてマイミクを招待  " /><br />
						</div><!--/.btn-->
					</form>
					<div class="more" style="text-align:right;">
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						<span style="color:#cc6666;">⇒</span><a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100206_campaign"|mixiurl %}'>招待キャンペーン詳細</a>&nbsp;<br />
					</div><!--/.more-->
				</div><!--/.section-->
			</div><!--/.inner-->
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		*%}
		<div class="line" style="background:#ff9933;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		{% emoji code="F8C4" %}<a href='{% "$baseUrl/mobile/kitchen/home"|mixiurl %}'>Myレストラン</a><br />
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#ff9933;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#inviteFinish-->

{%include file="common/menu.phtml"%}
{%include file="footer.phtml"%}