{%include file="header.phtml"%}
{%include file="common/ad_header.phtml"%}

<div id="ranking">
	<div class="content" style="background:#fff5f5;">
		<div class="headline" style="background:#ff9999;color:#ffcccc;text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/ranking.gif?100205" width="230" height="60" /><br />
		</div><!--/.headline-->
		<div class="switch" style="text-align:center;">
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% if $orderType == "total_level" %}
				{% emoji code="F8CF" %}<a href='{% "$baseUrl/mobile/kitchen/rankinglist?CF_ordertype=nakano_order"|mixiurl %}'>調理数</a><span style="color:#999999;">|</span>{% emoji code="F8D0" %}ﾚﾍﾞﾙ<span style="color:#999999;">|</span>{% emoji code="F8E4" %}<a href='{% "$baseUrl/mobile/kitchen/rankinglist?CF_ordertype=total_recipe_count"|mixiurl %}'>ﾚｼﾋﾟ</a><br />
			{% elseif $orderType == "total_recipe_count" %}
				{% emoji code="F8CF" %}<a href='{% "$baseUrl/mobile/kitchen/rankinglist?CF_ordertype=nakano_order"|mixiurl %}'>調理数</a><span style="color:#999999;">|</span>{% emoji code="F8D0" %}<a href='{% "$baseUrl/mobile/kitchen/rankinglist?CF_ordertype=total_level"|mixiurl %}'>ﾚﾍﾞﾙ</a><span style="color:#999999;">|</span>{% emoji code="F8E4" %}ﾚｼﾋﾟ<br />
			{% elseif $orderType == "nakano_order"%}
				{% emoji code="F8CF" %}調理数<span style="color:#999999;">|</span>{% emoji code="F8D0" %}<a href='{% "$baseUrl/mobile/kitchen/rankinglist?CF_ordertype=total_level"|mixiurl %}'>ﾚﾍﾞﾙ</a><span style="color:#999999;">|</span>{% emoji code="F8E4" %}<a href='{% "$baseUrl/mobile/kitchen/rankinglist?CF_ordertype=total_recipe_count"|mixiurl %}'>ﾚｼﾋﾟ</a><br />
			{% /if %}
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div style="background:#ff9999;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
		</div><!--/.switch-->
		<div class="inner">
			{% foreach from=$rankList item=data%}
				<div class="section">
					<table width="100%" cellpadding="0" cellspacing="0" border="0">
						<tr>
							{% if $data.rank <= 3%}
                            <td style="width:44px;text-align:center;"><img src="{%$data.miniThumbnailUrl%}" style="margin:3px 0;" /></td>
							{% /if %}
							<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}">
								{% if $uid == $data.uid %}
									{% emoji code="F995" %}<span style="color:#cc0000;">{%$data.displayName%}</span><br />
								{% else %}
									{% emoji code="F995" %}<a href='{% "$baseUrl/mobile/kitchen/home?CF_uid=`$data.uid`"|mixiurl %}'>{%$data.displayName%}</a><br />
								{% /if %}
									{% emoji code="F8D0" %}Lv.{%$data.total_level%} {% emoji code="F8E4" %}{%$data.total_recipe_count%}/{% $totalRecipeCount %}<br />
									{% if $data.cooking_dish %}調理:{% $data.cooking_dish %}品{% else %}調理:0品{% /if %}
									{% if $data.cookover_dish %}完成:{% $data.cookover_dish %}品{% else %}完成:0品{% /if %}<br/>
								</div></td>
						</tr>
					</table>
					<div style="background:#ff9999;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
				</div><!--/.section-->
			{% /foreach %}
            {% if $pager.maxPager > 1 %}
				<div class="pager" style="color:#006699;text-align:center;">
					{%include file="common/pager.phtml"%}
	                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<div style="background:#ff9999;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
				</div><!--/.pager-->
			{% /if %}
			<div class="toInviteNav" style="text-align:center;">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9CE" %}<a href='{% "invite:friends?callback=$baseUrl/mobile/callback/invite?forward=$baseUrl/mobile/kitchen/invitefinish" %}' style="color:#ea68a2;"><span style="color:#ea68a2;">まだ参加してないﾏｲﾐｸを招待</span></a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			</div><!--/.toInviteNav-->
			<div class="caution">
				<div style="background:#ff9999;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9A0" %}表示Lvは全ての料理ｼﾞｬﾝﾙの合計を表示しています｡<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			</div><!--/.toInviteNav-->
			<div class="footlink">
				<div style="background:#ff9999;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		        {% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchen/home"|mixiurl %}'>Myレストラン</a><br />
			</div><!--/.footlink-->
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="line" style="background:#ff9999;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
		</div><!--/.inner-->
	</div><!--/.content-->
</div><!--/#ranking-->

{%include file="common/menu.phtml"%}
{%include file="ad_footer.phtml"%}