{%include file="header.phtml"%}

<div id="removeFly">
	<div class="content" style="background:#f0f5e0;">

		<div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			{% if $actNum == 1 %}
			{%emoji code="F8F5"%}味付けをしました{%emoji code="F8F5"%}<br />
			{% elseif $actNum == 3 %}
			{%emoji code="F8F5"%}ハエを撃退しました{%emoji code="F8F5"%}<br />
			{% else %}
			{%emoji code="F8D0"%}味見しました{%emoji code="F8D0"%}<br />
			{% /if %}
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
		</div><!--/.headline-->

		<div class="description">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% if $actNum == 1 %}
			｢{%$rcpInfo.recipe_name|escape%}｣の味付けをして､<span style="color:#cc0000;">5の経験値</span>を獲得しました{%emoji code="F9CF"%}<br />
			{% elseif $actNum == 3 %}
			{% if $uid == $profileUid %}マイキッチン{% else %}{% $displayName %}さんの店{% /if %}のハエを撃退し、<span style="color:#cc0000;">5の経験値</span>を獲得しました{%emoji code="F9CF"%}<br />
			{% else %}
			{% $displayName %}さんの｢{%$rcpInfo.recipe_name|escape%}｣を味見し､<span style="color:#cc0000;">10の経験値</span>を獲得しました!<br />
			{% /if %}
		</div><!--/.description-->

		{%include file="common/ad_middle.phtml"%}
		{% if $recipeGot == 1 || $recipeGot == 2%}
		<div id="learn">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
				レシピの習得に成功しました!<br />
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			</div><!--/.headline-->
			<div class="inner">
				<div class="thumb" style="text-align:center;">
					<img src="{%$staticUrl%}/apps/kitchen/mobile/img/meal/130x130/{%$rcpInfo.f%}/{%$rcpInfo.n%}.gif" width="130" height="130" style="margin:3px 0;" /><br />
					<span style="color:#cc0000;">{%$rcpInfo.recipe_name|escape%}</span><br />
				</div><!--/.thumb-->
			</div><!--/.inner-->
		</div><!--/#learn-->
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="5" /><br />
		{% /if %}
		
		{% if $recipeGot == 0 || $recipeGot == 2%}
			<div class="levelUp" style="text-align:center;">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="5" /><br />
				<object data="{%$staticUrl%}/apps/kitchen/mobile/img/recipe/levelup.swf" type="application/x-shockwave-flash" width="240" height="106">
					<param name="bgcolor" value="ffffff" />
					<param name="loop" value="on" />
					<param name="quality" value="high" />
					<embed src="{%$staticUrl%}/apps/kitchen/mobile/img/recipe/levelup.swf" width="240" height="106" loop="on" quality="high" bgcolor="#ffffff"></embed>
				</object><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#cc0000;">レベルアップしました!</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="5" /><br />
	
				{% if $nowLv == 3 && $specialLv %}
					<span style="color:#cc0000;">食材市場でお買い物が<br />できるようになりました!</span><br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
					<span style="color:#cc0000;">食材を増やすと<br />{%emoji code="F8E4"%}レシピ開発に有利だよ!</span><br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
					食材を充実させよう{%emoji code="F99B"%}<br />
					<span style="color:#ff9999;">≫</span><a href='{% "$baseUrl/mobile/kitchenshop/foodlist"|mixiurl %}'>食材市場へ</a><span style="color:#ff9999;">≪</span><br />
				{% elseif $nowLv == 5 && $specialLv %}
					<span style="color:#cc0000;">不動産屋でお買い物が<br />できるようになりました!</span><br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
					<span style="color:#cc0000;">不動産物件を変えると<br />{%emoji code="F8E4"%}新しいｼﾞｬﾝﾙに挑戦できたり<br />キッチンの台数が増えるよ{%emoji code="F99F"%}</span><br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
					目指せ!セレブな一流店{%emoji code="F99B"%}<br />
					<span style="color:#ff9999;">≫</span><a href='{% "$baseUrl/mobile/kitchenshop/estatelist"|mixiurl %}'>不動産屋へ</a><span style="color:#ff9999;">≪</span><br />
				{% elseif $nowLv == 10 && $specialLv %}
					<span style="color:#cc0000;">美容室が利用<br />できるようになりました!</span><br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
					<span style="color:#cc0000;">シェフの容姿を変更して<br />友達に自慢しよう{%emoji code="F8F5"%}</span><br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
					すてきなシェフに大変身{%emoji code="F99B"%}<br />
					<span style="color:#ff9999;">≫</span><a href='{% "$baseUrl/mobile/kitchenshop/beautylist"|mixiurl %}'>美容室へ</a><span style="color:#ff9999;">≪</span><br />
				{% else %}
					<span style="color:#ff9999;">≫</span><a href='{% "$baseUrl/mobile/kitchenitem/mygiftlist"|mixiurl %}'>ごほうびギフトを確認</a><span style="color:#ff9999;">≪</span><br />
				{% /if %}
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
			</div><!--/.levelUp-->
		{% /if %}
		
		{% if $actNum == 1 %}
		<div>
		</div>
		{% elseif $actNum == 3 %}
		<div class="caution" style="text-align:center;">
			他の店でも撃退協力しよう{%emoji code="F99B"%}<br />
			<span style="color:#ff9999;">≫</span><a href='{% "$baseUrl/mobile/kitchen/rankinglist"|mixiurl %}'>マイミクさんの店舗一覧へ</a><span style="color:#ff9999;">≪</span><br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
		</div><!--/.caution-->
		{% else %}
			{% if $recipeGot == 0 %}
			<div class="caution" style="text-align:center;">
				別の店でも味見してみよう{% emoji code="F99B" %}<br />
				<span style="color:#ff9999;">≫</span><a href='{% "$baseUrl/mobile/kitchen/rankinglist"|mixiurl %}'>マイミクさんの店舗一覧へ</a><span style="color:#ff9999;">≪</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="5" /><br />
				{% emoji code="F9A0" %}運がｲｲとﾚｼﾋﾟを盗めることも!<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
			</div><!--/.caution-->
			{% else %}
			<div class="caution" style="text-align:center;">
				別の店でも味見してみよう{% emoji code="F99B" %}<br />
				<span style="color:#ff9999;">≫</span><a href='{% "$baseUrl/mobile/kitchen/rankinglist"|mixiurl %}'>マイミクさんの店舗一覧へ</a><span style="color:#ff9999;">≪</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
			</div><!--/.caution-->
			{% /if %}
		{% /if %}
		
		
		<div class="toKitchen" style="text-align:center;">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
				<span style="color:#ff9999;">≫</span><a href='{% "$baseUrl/mobile/kitchenflash/kitchen?CF_uid=`$profileUid`&opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$uid`&rand=`$rand`"|mobile_flashurl %}' accesskey="5">{% if $uid == $profileUid %}マイキッチンへ{% else %}{% $displayName %}さんのｷｯﾁﾝへ{% /if %}</a><span style="color:#ff9999;">≪</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
		</div><!--/.toKitchen-->
		
		<div class="footlink">
			<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% emoji code="F8C4" %}<a href='{% "$baseUrl/mobile/kitchen/home"|mixiurl %}'>Myレストラン</a><br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		</div><!--/.footlink-->

		<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#removeFly-->

{%include file="common/menu.phtml"%}
{%include file="footer.phtml"%}