{%include file="header.phtml"%}
{%include file="common/ad_header.phtml"%}

<div id="recipeDetail">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/recipe.gif" width="230" height="60" /><br />
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			{% $recipeInfo.recipe_name %}<br />
		</div><!--/.headline-->
		
		
		{% if !$canDisplayFood %}
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="info" style="text-align:center;">
			<span style="color:#cc0000;">まだこのレシピを覚えていません</span><br />
		</div><!--/.info-->
		{% /if %}
		
		
		<div class="thumb" style="text-align:center;">
        {% if $canDisplayFood %}
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/meal/130x130/{% $recipeInfo.f %}/{% $recipeInfo.n %}.gif" width="130" height="130" style="margin:3px 0;" /><br />
        {% else %}
            <img src="{%$staticUrl%}/apps/kitchen/mobile/img/meal/130x130/incomp/{% $recipeInfo.f %}/{% $recipeInfo.n %}.gif" width="130" height="130" style="margin:3px 0;" /><br />
        {% /if %}
		</div><!--/.thumb-->
		<div class="info">
        {% if $canDisplayFood %}
			{% emoji code="F8D0" %}ジャンル:{% $recipeInfo.genre_name|replace:"　":"" %}<br />
			{% emoji code="F8F5" %}調理回数:{% $userRecipeInfo.cooking_times %}回<br />
			{% emoji code="F8E5" %}販売価格:{% $recipeInfo.point %}T<br />
	   {% else %}
            {% emoji code="F8D0" %}ジャンル:{% $recipeInfo.genre_name|replace:"　":"" %}<br />
            {% emoji code="F8F5" %}調理回数:?回<br />
            {% emoji code="F8E5" %}販売価格:?T<br />
	   {% /if %}
		</div><!--/.info-->
		
		{% if !$luckyFlag %}
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
		<div class="info" style="text-align:center;">
			<span style="color:#cc0000;">≫</span><a href='{% "$baseUrl/mobile/kitchenrecipe/recipeask/CF_recipe_id/`$recipeInfo.recipe_id`/CF_uid/`$userInfo.uid`"|mixiurl %}'>マイミクにレシピを質問</a><span style="color:#cc0000;">≪</span><br />
			<span style="color:#999999;">1ｸﾘｯｸで簡単質問通知♪</span><br />
		</div><!--/.info-->
		{% /if %}
		
		
		<div class="stuff">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
				{% emoji code="F99F" %}必要な材料<br />
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			</div><!--/.headline-->
			<div class="inner">
                {% if $recipeInfo.food1 %}
                    <div class="section">
                        <table width="100%" cellpadding="0" cellspacing="0" border="0">
                            <tr>
                                {% if $canDisplayFood %}
                                    <td style="width:44px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/food/40x40/{% $food1.food_picture %}.gif" width="40" height="40" style="margin:3px 0;" /></td>
                                    <td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}">
                                        {% $food1.food_name %}<br />
                                        <div style="color:#999999;text-align:right;">{% $food1.food_category_name %}&nbsp;</div>
                                    </div></td>
                                {% else %}
                                    <td style="width:44px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/food/40x40/null.gif" width="40" height="40" style="margin:3px 0;" /></td>
                                    <td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}">
                                        ????<br />
                                        <div style="color:#999999;text-align:right;">{% $food1.food_category_name %}&nbsp;</div>
                                    </div></td>
                                {% /if %}
                            </tr>
                        </table>
                        <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
                    </div><!--/.section-->
                {% /if %}
                {% if $recipeInfo.food2 %}
                    <div class="section">
                        <table width="100%" cellpadding="0" cellspacing="0" border="0">
                            <tr>
                                {% if $canDisplayFood %}
                                    <td style="width:44px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/food/40x40/{% $food2.food_picture %}.gif" width="40" height="40" style="margin:3px 0;" /></td>
                                    <td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}">
                                        {% $food2.food_name %}<br />
                                        <div style="color:#999999;text-align:right;">{% $food2.food_category_name %}&nbsp;</div>
                                    </div></td>
                                {% else %}
                                    <td style="width:44px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/food/40x40/null.gif" width="40" height="40" style="margin:3px 0;" /></td>
                                    <td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}">
                                        ????<br />
                                        <div style="color:#999999;text-align:right;">{% $food2.food_category_name %}&nbsp;</div>
                                    </div></td>
                                {% /if %}
                            </tr>
                        </table>
                        <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
                    </div><!--/.section-->
                {% /if %}
                {% if $recipeInfo.food3 %}
                    <div class="section">
                        <table width="100%" cellpadding="0" cellspacing="0" border="0">
                            <tr>
                                {% if $canDisplayFood %}
                                    <td style="width:44px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/food/40x40/{% $food3.food_picture %}.gif" width="40" height="40" style="margin:3px 0;" /></td>
                                    <td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}">
                                        {% $food3.food_name %}<br />
                                        <div style="color:#999999;text-align:right;">{% $food3.food_category_name %}&nbsp;</div>
                                    </div></td>
                                {% else %}
                                    <td style="width:44px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/food/40x40/null.gif" width="40" height="40" style="margin:3px 0;" /></td>
                                    <td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}">
                                        ????<br />
                                        <div style="color:#999999;text-align:right;">{% $food3.food_category_name %}&nbsp;</div>
                                    </div></td>
                                {% /if %}
                            </tr>
                        </table>
                        <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
                    </div><!--/.section-->
                {% /if %}
            </div><!--/.inner-->
        </div><!--/.stuff-->

        <div class="lucky">
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
            <div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
                <img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
                {% emoji code="F8F5" %}ラッキー食材<br />
                <img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
            </div><!--/.headline-->
            <div class="inner">
                <div class="section">
                    <table width="100%" cellpadding="0" cellspacing="0" border="0">
                        <tr>
                            {% if $canDisplayFood && $luckyFlag %}
                                <td style="width:44px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/food/40x40/{% $luckyFood.food_picture %}.gif" width="40" height="40" style="margin:3px 0;" /></td>
                                <td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}">
                                    {% $luckyFood.food_name %}<br />
                                    <div style="color:#999999;text-align:right;">{% $luckyFood.food_category_name %}&nbsp;</div>
                                </div></td>
                            {% else %}
                                <td style="width:44px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/food/40x40/null.gif" width="40" height="40" style="margin:3px 0;" /></td>
                                <td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}">
                                    ????<br />
                                    <div style="color:#999999;text-align:right;">{% $luckyFood.food_category_name %}&nbsp;</div>
                                </div></td>
                            {% /if %}
                        </tr>
                    </table>
                    <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
                    {% emoji code="F9A0" %}ﾗｯｷｰ食材を加えてﾚｼﾋﾟ開発すると､通常よりも多くﾁｯﾌﾟがもらえます{% emoji code="F99F" %}<br />
                    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                </div><!--/.section-->
            </div><!--/.inner-->
        </div><!--/.lucky-->

		{% if !$luckyFlag %}
			<div class="diary">
				{% assign var="diary_title" value="【質問】"|cat:$recipeInfo.recipe_name|cat:"の作り方" %}
				{% assign var="diary_body" value=$recipeInfo.recipe_name|cat:"の作り方、誰か知ってる？\n\n◎ようこそマイキッチン\nhttp://mixi.jp/view_appli.pl?id=16235" %}
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
					<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
					{% emoji code="F8F6" %}ﾏｲﾐｸさんに聞いてみよう<br />
					<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
				</div><!--/.headline-->
				<div class="inner">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					{% emoji code="F9BE" %}<span style="color:#cc0000;">[レシピ質問日記]</span>を書いて､ﾏｲﾐｸさんに{% $recipeInfo.recipe_name %}のレシピを教えてもらおう!みんなで攻略すれば､一流店への道のりも遠くはないはず<br />
					<form method="get" action="http://m.mixi.jp/add_diary.pl">
						<input type="hidden" name="diary_title" value="{% $diary_title %}" />
						<input type="hidden" name="diary_body" value="{% $diary_body %}" />
						<input type="hidden" name="guid" value="ON" />
						<div class="btn" style="text-align:center;">
							<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
							<input type="submit" value=" レシピ質問日記を書く " /><br />
						</div><!--/.btn-->
					</form>
				</div><!--/.inner-->
			</div><!--/.diary-->
		{% /if %}

		<div class="toInviteNav" style="text-align:center;">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% emoji code="F9A0" %}<a href='{% "$baseUrl/mobile/kitchenshop/gachalist"|mixiurl %}'>ﾚｱ食材をｶﾞﾁｬでGET!!</a><br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		</div><!--/.toInviteNav-->
		<div class="footlink">
			<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchenrecipe/recipelist?CF_uid=`$userInfo.uid`&CF_genre=`$recipeInfo.genre`"|mixiurl %}'>{% $recipeInfo.genre_name|replace:"　":"" %}レシピ一覧</a><br />
			{% emoji code="F9B8" %}<a href='{% "$baseUrl/mobile/kitchenitem/food"|mixiurl %}'>アイテムBOX:食材冷蔵庫</a><br />
	        {% emoji code="F8C4" %}<a href='{% "$baseUrl/mobile/kitchen/home?CF_uid=`$userInfo.uid`"|mixiurl %}'>{% $userInfo.displayName%}のお店</a><br />
		</div><!--/.footlink-->

		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->

</div><!--/#recipeDetail-->

{%include file="common/menu.phtml"%}
{%include file="ad_footer.phtml"%}