{%include file="header.phtml"%}
{%include file="common/ad_header.phtml"%}

<div id="editCharaFinish">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			シェフ設定完了<br />
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
		</div><!--/.headline-->
		<div class="inner">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			今日からこのシェフといっしょに、理想のレストランを作っていきましょう!<br />
			<div class="thumb" style="text-align:center;">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<object data='{% "$baseUrl/mobile/kitchenwrapper/profileswf?$paramStr&opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$uid`&rand=`$rand`"|mobile_flashurl %}' type="application/x-shockwave-flash" width="130" height="130">
					<param name="bgcolor" value="FFFFFF" />
					<param name="loop" value="on" />
					<param name="quality" value="high" />
					<embed src='{% "$baseUrl/mobile/kitchenwrapper/profileswf?$paramStr&opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$uid`&rand=`$rand`"|mobile_flashurl %}' width="130" height="130" loop="on" quality="high" bgcolor="#FFFFFF"></embed>
				</object><br />
			</div><!--/.thumb-->
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			続けて､お店の名前が設定できます｡<br />
			<div class="select" style="text-align:center;">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
				<form method="post" action='{% "$baseUrl/mobile/kitchenfirst/editname"|mixiurl %}'>
					<input type="submit" value=" お店の名前を設定する " /><br />
				</form>
				<form method="post" action='{% "$baseUrl/mobile/kitchen/home"|mixiurl %}'>
					<input type="submit" value=" ｽｷｯﾌﾟ|あとで変更する " /><br />
				</form>
				{%*
					<span style="color:#ff9999;">≫</span><a href='{% "$baseUrl/mobile/kitchenfirst/editname"|mixiurl %}'>お店の名前を設定する</a><span style="color:#ff9999;">≪</span><br />
					<span style="color:#ff9999;">≫</span><a href='{% "$baseUrl/mobile/kitchen/home"|mixiurl %}'>ｽｷｯﾌﾟ|あとで設定する</a><span style="color:#ff9999;">≪</span><br />
				*%}
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
			</div><!--/.select-->
		</div><!--/.inner-->
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#editCharaFinish-->

{%include file="common/copyright.phtml"%}
{%include file="footer.phtml"%}