{%include file="header.phtml"%}
{%include file="common/ad_header.phtml"%}

<div id="firstLesson">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="background:#8bbd82;text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/firsttime.gif" width="230" height="60" /><br />
		</div><!--/.headline-->
		<div class="inner">
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				ようこそマイキッチンの基本的な遊び方を紹介します｡<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="line" style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.description-->
			<div class="section">
				<table width="100%" cellpadding="0" cellspacing="0" border="0">
					<tr>
						<td style="width:64px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/firsttime/04.jpg?" width="60" height="60" style="margin:3px 0;" /></td>
						<td><img src="{%$staticUrl%}/apps/kitchen/mobile/img/firsttime/04.gif?" width="165" height="60" /></td>
					</tr>
				</table>
				<span style="color:#cc0000;">調理したい料理のレシピを選ぶ</span>と､シェフが調理を開始します｡料理によって､{% emoji code="F95E" %}調理時間や{% emoji code="F8E5" %}獲得ﾁｯﾌﾟが異なるので要注意!<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="line" style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<table width="100%" cellpadding="0" cellspacing="0" border="0">
					<tr>
						<td style="width:64px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/firsttime/05.jpg?" width="60" height="60" style="margin:3px 0;" /></td>
						<td><img src="{%$staticUrl%}/apps/kitchen/mobile/img/firsttime/05.gif?" width="165" height="60" /></td>
					</tr>
				</table>
				料理が完成するまでの時間、<span style="color:#cc0000;">気長に待ちましょう</span>{% emoji code="F99C" %}<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="line" style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<table width="100%" cellpadding="0" cellspacing="0" border="0">
					<tr>
						<td style="width:64px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/firsttime/06.jpg?" width="60" height="60" style="margin:3px 0;" /></td>
						<td><img src="{%$staticUrl%}/apps/kitchen/mobile/img/firsttime/06.gif?" width="165" height="60" /></td>
					</tr>
				</table>
				完成した料理を運ぶと､{% emoji code="F8E5" %}ﾁｯﾌﾟと{% emoji code="F99F" %}経験値がもらえます｡<span style="color:#cc0000;">ﾁｯﾌﾟが貯まったら、ﾃﾞﾊﾟｰﾄで食材やざっかを購入してみましょう!</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="line" style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="toGame" style="color:#497d40;text-align:center;">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
				遊び方の基本は<br />
				[選ぶ]→[待つ]→[運ぶ]です｡<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
				基本ルールがわかったら<br />
				さっそく調理を始めましょう<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="5" /><br />
	            <table width="230" cellpadding="3" cellspacing="1" border="0" align="center" style="background:#8bbd82;">
					<tr>
						<td style="background:#ffffcc;text-align:center;"><div style="{% if $ua==1 %}font-size:x-small;{%/if%}"><span style="color:#006699;">≫</span><a href='{% "$baseUrl/mobile/kitchenflash/kitchen?CF_uid=`$uid`&opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$uid`&rand=`$rand`"|mobile_flashurl %}' accesskey="5">マイキッチンへ</a><span style="color:#006699;">≪</span></div></td>
					</tr>
	            </table>
			</div><!--/.toGame-->
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
			<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	    </div><!--/.inner-->
    </div><!--/.content-->
</div><!--/#firstLesson-->

{%include file="common/browseback.phtml"%}
{%include file="footer.phtml"%}