{%include file="header.phtml"%}
{%include file="common/ad_header.phtml"%}

<div id="selectChara">
    <div class="content" style="background:#f0f5e0;">
        <div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
            <img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
            さぁレストランを始めよう!<br />
            <img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
        </div><!--/.headline-->
        <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
        <div class="inner">
			これからレストランを共同運営していくシェフを選びます｡<br />
			<div class="thumb" style="text-align:center;">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<object data="{%$staticUrl%}/apps/kitchen/mobile/img/wrapper/{%$swfName%}" type="application/x-shockwave-flash" width="130" height="130">
					<param name="bgcolor" value="ffffff" />
					<param name="loop" value="on" />
					<param name="quality" value="high" />
					<embed src="{%$staticUrl%}/apps/kitchen/mobile/img/wrapper/{%$swfName%}" width="240" height="106" loop="on" quality="high" bgcolor="#ffffff"></embed>
				</object><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			</div><!--/.thumb-->
			こちらのシェフでよろしければ、[このシェフでＯＫ]を押してください。<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="5" /><br />
			<div class="btn" style="text-align:center;">
				<form method="post" action='{% "$baseUrl/mobile/kitchenfirst/selectchara"|mixiurl %}'>
					<input type="submit" value=" 別のシェフを探す " /><br />
				</form>
			</div><!--/.btn-->
			<div class="btn" style="text-align:center;">
				<form method="post" action='{% "$baseUrl/mobile/kitchenfirst/editchara?$paramStr"|mixiurl %}'>
					<input type="submit" value=" このシェフでＯＫ " /><br />
				</form>
			</div><!--/.btn-->
        </div><!--/.inner-->
        <div class="edit">
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
            <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			シェフの色や形をこまかく作成することもできます(お時間2分程度)。なかなか好みのシェフが見つからない場合はこちらをご利用ください。<br />
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="5" /><br />
			<div class="changeChara" style="text-algin:center;">
                <table width="230" cellpadding="3" cellspacing="1" border="0" align="center" style="background:#8bbd82;">
					<tr>
						<td style="background:#ffffcc;text-align:center;"><div style="{% if $ua==1 %}font-size:x-small;{%/if%}">
							<span style="color:#ff9999;">≫</span><a href='{% "$baseUrl/mobile/kitchenwrapper/changecharaswf?opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$uid`&rand=`$rand`"|mobile_flashurl %}'>じっくり作成する</a><span style="color:#ff9999;">≪</span><br />
						</div></td>
					</tr>
				</table>
			</div><!--/.changeChara-->
        </div><!--/.edit-->
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
        <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
        <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		{% emoji code="F9A0" %}<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=pointer"|mixiurl %}'>シェフの作成ができない場合</a><br />
        <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
        <div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
    </div><!--/.content-->
</div><!--/#selectChara-->

{%include file="common/copyright.phtml"%}
{%include file="footer.phtml"%}
