{% if $step=="confirm" %}
	{%include file="header.phtml"%}
	<div id="zakkaAddConfirm">
		<div class="content" style="background:#f0f5e0;">
			<div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/warehouse.gif" width="230" height="60" /><br />
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
				{%$good.goods_name%}<br />
			</div><!--/.headline-->
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				こちらのざっかをおきますか?<br />
			</div><!--/.description-->
			<div class="thumb" style="text-align:center;">
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/zakka/130x130/{%$good.goods_picture%}.gif" width="130" height="130" style="margin:3px 0;" /><br />
				{%$good.goods_introduce%}<br />
			</div><!--/.thumb-->
			<div class="action">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
				<form method="post" action='{% "$baseUrl/mobile/kitchenitem/addgood/CF_step/complete/CF_position/`$position`/CF_goodId/`$goodId`"|mixiurl %}'>
					<div class="btn" style="text-align:center;">
						<input type="submit" value=" お　く " />
					</div><!--/.btn-->
				</form>
				<form method="post" action='{% "$baseUrl/mobile/kitchenitem/good"|mixiurl %}'>
					<div class="btn" style="text-align:center;">
						<input type="submit" value=" やめる " />
					</div><!--/.btn-->
				</form>
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
			</div><!--/.action-->
			<div class="caution">
				{% emoji code="F9A0" %}ざっかの配置はいつでも自由に変更可能です｡<br />
			</div><!--/.caution-->
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
		</div><!--/.content-->
	</div><!--/#zakkaAddConfirm-->
	{%include file="common/browseback.phtml"%}
	{%include file="footer.phtml"%}
{% else %}
	{%include file="header.phtml"%}
	<div id="zakkaAddFinish">
		<div class="content" style="background:#f0f5e0;"> 
			<div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/warehouse.gif" width="230" height="60" /><br />
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
				{%$good.goods_name%}<br />
			</div><!--/.headline-->
			<div class="inner">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				ざっかを置きました!<br />
				{%include file="common/ad_192x106.phtml"%}
				<div class="toShop" style="text-align:center;">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
					<span style="color:#ff9999;">≫</span><a href='{% "$baseUrl/mobile/kitchenitem/good"|mixiurl %}'>ざっか置き場へ</a><span style="color:#ff9999;">≪</span><br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
				</div><!--/.toShop-->
				<div class="toShopNav" style="text-align:center;">
					<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					{% emoji code="F9A0" %}<a href='{% "$baseUrl/mobile/kitchenshop/goodslist"|mixiurl %}'>デパートでざっかを買おう</a><br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				</div><!--/.toShopNav-->
				<div class="footlink">
					<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<span style="color:#ff9999;">⇒</span><a href='{% "$baseUrl/mobile/kitchen/home"|mixiurl %}'>Myレストランへ</a><br />
				</div><!--/.footlink-->
			</div><!--/.inner-->
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
		</div><!--/.content-->
	</div><!--/#zakkaAddFinish-->
	{%include file="common/menu.phtml"%}
	{%include file="footer.phtml"%}
{% /if %}
