{%include file="header.phtml"%}
<div id="giftFinish">
	<div class="content" style="background:#eeffff;">
		<div class="headline" style="background:#82bdba;color:#ffffff;text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/giftshop.gif" width="230" height="60" /><br />
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			配送完了<br />
		</div><!--/.headline-->
		<div class="inner">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{%$giftInfo.name%}をﾏｲﾐｸに贈りました!<br />
			{%include file="common/ad_middle.phtml"%}
			<div class="toSend" style="text-align:center;">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
                <span style="color:#ff9999;">≫</span><a href='{% "$baseUrl/mobile/kitchenitem/freegiftlist?resend=1"|mixiurl %}'>無料ギフトへ</a><span style="color:#ff9999;">≪</span><br />
				<span style="color:#ff9999;">≫</span><a href='{% "$baseUrl/mobile/kitchenitem/gift"|mixiurl %}'>ギフト配送所へ</a><span style="color:#ff9999;">≪</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
			</div><!--/.toSend-->
            <div class="toShopNav" style="text-align:center;">
                <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                {% emoji code="F9A0" %}<a href='{% "$baseUrl/mobile/kitchenshop/giftlist"|mixiurl %}'>デパートでギフトを買おう</a><br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
            </div><!--/.toShopNav-->
			<div class="footlink">
				<div style="background:#82bdba;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{%emoji code="F9B8"%}<a href='{% "$baseUrl/mobile/kitchenitem/index"|mixiurl %}'>ｱｲﾃﾑBOX</a><br />
				{% emoji code="F8C4" %}<a href='{% "$baseUrl/mobile/kitchen/home"|mixiurl %}'>Myレストラン</a><br />
			</div><!--/.footlink-->
		</div><!--/.inner-->
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#82bdba;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#giftFinish-->

{%include file="common/menu.phtml"%}
{%include file="footer.phtml"%}
