{%include file="header.phtml"%}
{%include file="common/ad_header.phtml"%}

<div id="giftList">
    <div class="content" style="background:#f0f5e0;">
        <div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
            <img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/giftcenter.gif" width="230" height="60" /><br />
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			無料ギフト<br />
        </div><!--/#headline-->
		<div class="description">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			無料ｷﾞﾌﾄは毎日ﾏｲﾐｸに贈れるｷﾞﾌﾄだよ｡みんなでｷﾞﾌﾄを送りあおう!
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
		</div><!--/.description-->
        <div class="inner">
            {% foreach from=$giftList item=data%}
                <div class="section">
                    <table width="100%" cellpadding="0" cellspacing="0" border="0">
                        <tr>
                            {% if $data.goods_gift %}
                            <td style="width:44px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/zakka/40x40/{% $data.picture %}.gif" width="40" height="40" style="margin:3px 0;" /></td>
                            {% elseif $data.item_gift %}
                                <td style="width:44px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/yorozu/40x40/{% $data.picture %}.gif" width="40" height="40" style="margin:3px 0;" /></td>
                            {% /if %}
                            <td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}">{%$data.name%}<br />
                                {%$data.introduce%}<br />
                                <div style="text-align:right;">{% emoji code="F8E6" %}<a href='{% "$baseUrl/mobile/kitchenitem/freegiftselect?giftId=`$data.gift_id`"|mixiurl %}'>ﾏｲﾐｸに贈る</a>&nbsp;</div></div></td>
                        </tr>
                    </table>
                    <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
                </div><!--/.section-->
            {% /foreach %}
			<div class="description">
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9DC" %}友達ｷﾞﾌﾄはﾏｲﾐｸ1人ごとに1日1回まで贈れます｡<br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.description-->
            <div class="toShopNav" style="text-align:center;">
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                {% emoji code="F9A0" %}<a href='{% "$baseUrl/mobile/kitchenshop/giftlist"|mixiurl %}'>デパートでギフトを買おう</a><br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
            </div><!--/.toShopNav-->
            <div class="footlink">
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                {% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchenitem/index"|mixiurl %}'>アイテムBOX</a><br />
                {% emoji code="F8C4" %}<a href='{% "$baseUrl/mobile/kitchen/home"|mixiurl %}'>Myレストラン</a><br />
            </div><!--/.footlink-->
        </div><!--/.inner-->
        <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
        <div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
    </div><!--/.content-->
</div><!--/#giftList-->

{%include file="common/menu.phtml"%}
{%include file="ad_footer.phtml"%}
