{%include file="header.phtml"%}
{%include file="common/ad_header.phtml"%}

<div id="giftSelectList">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/giftcenter.gif" width="230" height="60" /><br />
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			{% $giftInfo.name %}<br />
		</div><!--/.headline-->
		<div class="description">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			このギフトの送付先を選んでください<br />
		</div><!--/.description-->
		<div class="thumb" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/gift/130x130/{% $giftInfo.picture %}" width="130" height="130" style="margin:3px 0;" /><br />
			{% $giftInfo.introduce %}<br />
		</div><!--/.thumb-->
		<div class="selectUser">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
				マイミク一覧から送付先を選択<br />
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			</div><!--/.headline-->
			{% if $count > 0 %}
				<div class="kind" style="text-align:center;">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					{% if $rankBy == "asc" %}新人さん{% else %}<a href='{% "$baseUrl/mobile/kitchenitem/giftselect?giftId=`$giftId`&rankBy=asc"|mixiurl %}'>新人さん</a>{% /if %}<span style="color:#999999;">|</span>{% if $rankBy == "desc" %}ベテラン{% else %}<a href='{% "$baseUrl/mobile/kitchenitem/giftselect?giftId=`$giftId`&rankBy=desc"|mixiurl %}'>ベテラン</a>{% /if %}</a><br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
				</div><!--/.kind-->
				<div class="count">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					{% $count %}件中 {% $start %}-{% if $count <= $start+4 %}{% $count %}{% else %}{% $start+4 %}{% /if %}件<br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
				</div><!--/.count-->
				<div class="inner">
				   {% foreach from=$friendList item=data key=key %}
						<div class="section">
							<table width="100%" cellpadding="0" cellspacing="0" border="0">
								<tr>
									<td style="width:44px;text-align:center;"><img src="{%$data.miniThumbnailUrl%}" style="margin:3px 0;" /></td>
									<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}">
										{% emoji code="F995" %}<a href='{% "$baseUrl/mobile/kitchen/profile?CF_uid=`$data.uid`"|mixiurl %}'>{% $data.displayName %}</a><br />
										<div style="text-align:right;"><a href='{% "$baseUrl/mobile/kitchenitem/giftconfirm?taruid=`$data.uid`&giftId=`$giftId`"|mixiurl %}'>このﾏｲﾐｸを選択</a>&nbsp;</div>
									</div></td>
								</tr>
							</table>
							<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
						</div><!--/.section-->
					{% /foreach %}
				</div><!--/.inner-->
	            {% if $count > 5 %}
					<div class="pager" style="color:#006699;text-align:center;">
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						{%include file="kitchenitem/common/pager.phtml"%}<br />
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
					</div><!--/.pager-->
				{% /if %}
			{% else %}
				<div class="null" style="text-align:center;">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
					アプリを利用している<br />
					マイミクがいません{% emoji code="F997" %}<br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="5" /><br />
					<span style="color:#ff9999;">≫</span><a href='{% "$baseUrl/mobile/kitchen/inviteguide"|mixiurl %}'>マイミクを招待する</a><span style="color:#ff9999;">≪</span><br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
					<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
				</div><!--/.null-->
			{% /if %}
		</div><!--/.selectUser-->
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#giftSelectList-->

{%include file="common/browseback.phtml"%}
{%include file="ad_footer.phtml"%}