{%include file="header.phtml"%}
{%include file="common/ad_header.phtml"%}

<div id="giftList">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="background:#8bbd82;text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/giftcenter.gif" width="230" height="60" /><br />
		</div><!--/#headline-->
		{% if $count > 0 %}
            {% if 1 == $userInfo.daily_gift %}
			<div class="toFreeGift" style="text-align:center;">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F8E6" %}<a href='{% "$baseUrl/mobile/kitchenitem/freegiftlist"|mixiurl %}'><span style="color:#cc0000;">マイミクに無料ギフトを贈ろう</span></a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.toFreeGift-->
            {% /if %}
			<div class="count">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% $count %}件中 {% $start %}-{% if $count <= $start+4 %}{% $count %}{% else %}{% $start+4 %}{% /if %}件<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.count-->
			<div class="inner">
				{% foreach from=$giftList item=data key=key %}
					<div class="section">
						<table width="100%" cellpadding="0" cellspacing="0" border="0">
							<tr>
								<td style="width:44px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/gift/40x40/{% $data.picture %}" width="40" height="40" style="margin:3px 0;" /></td>
								<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}">{%$data.name%}<br />
									{%$data.introduce%}<br />
                                    <div style="text-align:right;">数量:{% $data.sum %} {% emoji code="F8E6" %}{% if $taruid == 0 %}<a href='{% "$baseUrl/mobile/kitchenitem/giftselect?giftId=`$data.gift_id`"|mixiurl %}'>ﾏｲﾐｸに贈る</a>{% else %}<a href='{% "$baseUrl/mobile/kitchenitem/giftconfirm?giftId=`$data.gift_id`&taruid=`$taruid`"|mixiurl %}'>ﾏｲﾐｸに贈る</a>{% /if %}&nbsp;</div></div></td>
							</tr>
						</table>
						<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
					</div><!--/.section-->
				{% /foreach %}
				{% if $count > 5 %}
					<div class="pager" style="color:#006699;text-align:center;">
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						{%include file="kitchenitem/common/pager.phtml"%}<br />
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
					</div><!--/.pager-->
				{% /if %}
				<div class="toShopNav" style="text-align:center;">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					{% emoji code="F9A0" %}<a href='{% "$baseUrl/mobile/kitchenshop/giftlist"|mixiurl %}'>デパートでギフトを買おう</a><br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
				</div><!--/.toShopNav-->
				<div class="footlink">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchenitem/index"|mixiurl %}'>アイテムBOX</a><br />
					{% emoji code="F8C4" %}<a href='{% "$baseUrl/mobile/kitchen/home"|mixiurl %}'>Myレストラン</a><br />
				</div><!--/.footlink-->
			</div><!--/.inner-->
		{% else %}
			<div class="null" style="text-align:center;">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
				まだギフトがありません<br />
				マイミクにギフトを贈ろう!<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="5" /><br />
				{% if 1 == $userInfo.daily_gift %}
				<span style="color:#ff9999;">≫</span><a href='{% "$baseUrl/mobile/kitchenitem/freegiftlist"|mixiurl %}'>無料ギフトを贈る</a><span style="color:#ff9999;">≪</span><br />
				{% /if %}
				<span style="color:#ff9999;">≫</span><a href='{% "$baseUrl/mobile/kitchenshop/giftlist"|mixiurl %}'>ギフト屋で購入！</a><span style="color:#ff9999;">≪</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.null-->
			<div class="footlink">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchenitem/index"|mixiurl %}'>アイテムBOX</a><br />
				{% emoji code="F8C4" %}<a href='{% "$baseUrl/mobile/kitchen/home"|mixiurl %}'>Myレストラン</a><br />
			</div><!--/.footlink-->
		{% /if %}
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#giftList-->

{%include file="common/menu.phtml"%}
{%include file="ad_footer.phtml"%}
