{%include file="header.phtml"%}
{%include file="common/ad_header.phtml"%}

<div id="itemIndex">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="background:#8bbd82;text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/itembox.gif" width="230" height="60" /><br />
		</div><!--/#headline-->
		<div class="inner">
			<div class="section">
				<table width="100%" cellpadding="0" cellspacing="0" border="0">
					<tr>
						<td style="width:44px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/itembox/food.gif?100205" width="40" height="40" style="margin:3px 0;" /></td>
						<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}"><a href='{% "$baseUrl/mobile/kitchenitem/food"|mixiurl %}'>食材冷蔵庫</a><br />
							手持ちの食材が確認できるよ</div></td>
					</tr>
				</table>
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<table width="100%" cellpadding="0" cellspacing="0" border="0">
					<tr>
						<td style="width:44px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/itembox/zakka.gif?100205" width="40" height="40" style="margin:3px 0;" /></td>
						<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}"><a href='{% "$baseUrl/mobile/kitchenitem/good"|mixiurl %}'>ざっか置き場</a><br />
							模様替えをして自慢しよう!</div></td>
					</tr>
				</table>
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<table width="100%" cellpadding="0" cellspacing="0" border="0">
					<tr>
						<td style="width:44px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/itembox/yorozu.gif?100205" width="40" height="40" style="margin:3px 0;" /></td>
						<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}"><a href='{% "$baseUrl/mobile/kitchenitem/item"|mixiurl %}'>どうぐばこ</a><br />
							生産量/調理速度ｱｯﾌﾟで効率化!</div></td>
					</tr>
				</table>
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<table width="100%" cellpadding="0" cellspacing="0" border="0">
					<tr>
						<td style="width:44px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/itembox/gift.gif?100205" width="40" height="40" style="margin:3px 0;" /></td>
						<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}"><a href='{% "$baseUrl/mobile/kitchenitem/gift"|mixiurl %}'>ギフト配送所</a><br />
							配送前のｷﾞﾌﾄが確認できるよ</div></td>
					</tr>
				</table>
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
		</div><!--/.inner-->
		<div class="toShopNav" style="text-align:center;">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% emoji code="F9A0" %}<a href='{% "$baseUrl/mobile/kitchenshop/shopping"|mixiurl %}'>デパートで買い物をしよう</a><br />
		</div><!--/.toShopNav-->
		<div class="footlink">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% emoji code="F8C4" %}<a href='{% "$baseUrl/mobile/kitchen/home"|mixiurl %}'>Myレストラン</a><br />
		</div><!--/.footlink-->
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#itemIndex-->

{%include file="common/menu.phtml"%}
{%include file="ad_footer.phtml"%}