{%include file="header.phtml"%}

<div id="giftOpenConfirm">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/giftlist.gif" width="230" height="60" /><br />
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			{% $name %}<br />
		</div><!--/.headline-->
		<div class="description">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% if $sendUid %}
				{% $sendUserInfo.displayName %}さんから頂いたギフトを開封しますか?<br />
			{% else %}
				このギフトを開封しますか?<br />
			{% /if %}
		</div><!--/.description-->
		<div class="thumb" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/gift/130x130/{% $picture %}" width="130" height="130" style="margin:3px 0;" /><br />
			{% $introduce %}<br />
		</div><!--/.thumb-->
		<div class="action">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
			<form method="post" action='{% "$baseUrl/mobile/kitchenitem/opengiftfinish"|mixiurl %}'>
				<input type="hidden" name="CF_id" value="{% $id %}" />
				<input type="hidden" name="CF_name" value="{% $name %}" />
				<div class="btn" style="text-align:center;">
					<input type="submit" value=" 開ける " /><br />
				</div><!--/.btn-->
			</form>
			<form method="post" action='{% "$baseUrl/mobile/kitchenitem/mygiftlist"|mixiurl %}'>
				<input type="hidden" name="CF_id" value="{% $id %}" />
				<div class="btn" style="text-align:center;">
					<input type="submit" value=" やめる " /><br />
				</div><!--/.btn-->
			</form>
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
		</div><!--/.action-->

		{% if $sendUid %}
			<div class="sendUser">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
					<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
					このギフトの贈り主<br />
					<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
				</div><!--/.headline-->
				<div class="inner">
					<table width="100%" cellpadding="0" cellspacing="0" border="0">
						<tr>
							<td style="width:44px;text-align:center;"><img src="{% $sendUserInfo.miniThumbnailUrl %}" style="margin:3px 0;" /></td>
							<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}">
							{% emoji code="F995" %}<a href='{% "$baseUrl/mobile/kitchen/home?CF_uid=`$sendUserInfo.uid`"|mixiurl %}'>{% $sendUserInfo.displayName %}</a><br />
							{% emoji code="F99F" %}ﾚﾍﾞﾙ:{% $sendUserInfo.total_level %}<br />
							{% emoji code="F8E4" %}ﾚｼﾋﾟ:{% $sendUserInfo.total_recipe_count %}/{% $totalRecipeCount %}</div></td>
						</tr>
					</table>
				</div><!--/.inner-->
			</div><!--/.sendUser-->
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		{% /if %}

		<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#giftOpenConfirm-->

{%include file="common/browseback.phtml"%}
{%include file="footer.phtml"%}