{%include file="header.phtml"%}

<div id="giftOpenFinish">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/giftlist.gif" width="230" height="60" /><br />
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			{% $name %}<br />
		</div><!--/.headline-->
		<div class="description">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% if $sendUid %}
				{% $sendUserInfo.displayName %}さんから頂いたｷﾞﾌﾄを開封しました!<br />
			{% else %}
				ギフトを開封しました!<br />
			{% /if %}
		</div><!--/.description-->
		{%include file="common/ad_middle.phtml"%}
		<div class="giftContent">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
				なかに入っていたもの<br />
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			</div><!--/.headline-->
			<div class="inner">
				{% foreach from=$result item=giftitem %}
					<div class="section">
						<table width="100%" cellpadding="0" cellspacing="0" border="0">
							<tr>
								{% if 'food' == $giftitem.type %}
									<td style="width:44px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/food/40x40/{% $giftitem.picture %}.gif" width="40" height="40" style="margin:3px 0;" /></td>
									<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}">
										{% $giftitem.name %}<br />
										{% $giftitem.introduce %}<br />
										<div style="text-align:right;">食材:{% $giftitem.food_category %} 数量:{% $giftitem.food_count %}&nbsp;</div>
									</div></td>
								{% elseif 'goods' == $giftitem.type %}
									<td style="width:44px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/zakka/40x40/{% $giftitem.picture %}.gif" width="40" height="40" style="margin:3px 0;" /></td>
									<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}">
										{% $giftitem.name %}<br />
										{% $giftitem.introduce %}<br />
										<div style="text-align:right;">ざっか:{% $giftitem.genre %} {% if $ownerGenreId == $giftitem.genre_id %}<a href='{% "$baseUrl/mobile/kitchenflash/setgoods?goodsId=`$giftitem.goods_id`2&opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$osUID`&rand=`$rand`"|mobile_flashurl %}'>設置する</a>{% else %}設置する{% /if %}&nbsp;</div>
									</div></td>
                                {% elseif 'item' == $giftitem.type %}
									<td style="width:44px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/yorozu/40x40/{% $giftitem.picture %}.gif" width="40" height="40" style="margin:3px 0;" /></td>
									<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}">
										{% $giftitem.name %}<br />
										{% $giftitem.introduce %}<br />
										<div style="text-align:right;">どうぐ 数量:{% $giftitem.item_count %}&nbsp;</div>
									</div></td>
								{% elseif 'point' == $giftitem.type %}
									<td style="width:44px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/gift/40x40/{% $giftitem.picture %}.gif" width="40" height="40" style="margin:3px 0;" /></td>
									<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}">
										{% $giftitem.name %}<br />
										{% $giftitem.introduce %}<br />
										<div style="text-align:right;">{% $giftitem.point %}T&nbsp;</div>
									</div></td>
								{% /if %}
							</tr>
						</table>
						<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
					</div><!--/.section-->
				{% /foreach %}
			</div><!--/.inner-->
		</div><!--/.giftContent-->
		{% if $sendUid %}
			<div class="sendUser">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
					<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
					このギフトの贈り主<br />
					<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
				</div><!--/.headline-->
				<div class="inner">
					<div class="section">
						<table width="100%" cellpadding="0" cellspacing="0" border="0">
							<tr>
								<td style="width:44px;text-align:center;"><img src="{% $sendUserInfo.miniThumbnailUrl %}" style="margin:3px 0;" /></td>
								<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}">
									{% emoji code="F995" %}<a href='{% "$baseUrl/mobile/kitchen/home?CF_uid=`$sendUserInfo.uid`"|mixiurl %}'>{% $sendUserInfo.displayName %}</a><br />
									{% emoji code="F99F" %}ﾚﾍﾞﾙ:{% $sendUserInfo.total_level %}<br />
									{% emoji code="F8E4" %}ﾚｼﾋﾟ:{% $sendUserInfo.total_recipe_count %}/{% $totalRecipeCount %}<br />
								</div></td>
							</tr>
						</table>
						<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
					</div><!--/.section-->
				</div><!--/.inner-->
				<div class="toGiftShop" style="text-align:center;">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
					{% $sendUserInfo.displayName %}さんにお返しギフトを贈ろう!<br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="5" /><br />
					<span style="color:#ff9999;">≫</span><a href='{% "$baseUrl/mobile/kitchenshop/giftlist"|mixiurl %}'>お返しギフトを探す</a><span style="color:#ff9999;">≪</span><br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
					<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
				</div><!--/.toGiftShop-->
			</div><!--/.sendUser-->
		{% /if %}
		<div class="footlink">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% if $hasGift %}
				{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchenitem/mygiftlist"|mixiurl %}'>ギフト一覧</a><br />
			{% else %}
				{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchen/home"|mixiurl %}' accesskey="3">Myレストラン</a><br />
			{% /if %}
		</div><!--/.footlink-->
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#giftOpenFinish-->

{%include file="common/menu.phtml"%}
{%include file="footer.phtml"%}