{% if $step=="confirm" %}
	{%include file="header.phtml"%}
	<div id="yorozuUseConfirm">
		<div class="content" style="background:#f0f5e0;">
			<div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/toolbox.gif" width="230" height="60" /><br />
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
				{%$item.item_name%}<br />
			</div><!--/.headline-->
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				このどうぐを使いますか?<br />
			</div><!--/.description-->
			<div class="thumb" style="text-align:center;">
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/yorozu/130x130/{%$item.item_picture%}.gif" width="130" height="130" style="margin:3px 0;" /><br />
				{%$item.item_introduce%}<br />
			</div><!--/.thumb-->
			{% if $itemId == 19 && $usedChara == 1 %}
				<div class="action" style="text-align:center;">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
					申し訳ありませんが<br />
					現在､使用できません<br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
				</div><!--/.action-->
			{% elseif $item.item_category == 4 %}
				<div class="action">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
					<form method="post" action='{% "$baseUrl/mobile/kitchenitem/useitem/CF_step/complete/CF_kitchen_id/`$kitchenId`/CF_itemId/`$itemId`/CF_uid/`$profileUid`"|mixiurl %}'>
						<div class="btn" style="text-align:center;">
							<input type="submit" value=" スプーンで味見 " /><br />
						</div><!--/.btn-->
					</form>
					<form method="post" action='{% "$baseUrl/mobile/kitchen/tryfood/CF_spoonOver/1/CF_uid/`$profileUid`/CF_kitchen_id/`$kitchenId`"|mixiurl %}'>
						<div class="btn" style="text-align:center;">
							<input type="submit" value=" 普通に味見する " /><br />
						</div><!--/.btn-->
					</form>
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
				</div><!--/.action-->
			{% else %}	
				<div class="action">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
					<form method="post" action='{% "$baseUrl/mobile/kitchenitem/useitem/CF_step/complete/CF_kitchen_id/`$kitchenId`/CF_itemId/`$itemId`"|mixiurl %}'>
						<div class="btn" style="text-align:center;">
							<input type="submit" value=" 決 定 " /><br />
						</div><!--/.btn-->
					</form>
					<form method="post" action='{% "$baseUrl/mobile/kitchenitem/item"|mixiurl %}'>
						<div class="btn" style="text-align:center;">
							<input type="submit" value=" ｷｬﾝｾﾙ " /><br />
						</div><!--/.btn-->
					</form>
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
				</div><!--/.action-->
			{% /if %}
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
		</div><!--/.content-->
	</div><!--/#yorozuUseConfirm-->
	{%include file="common/browseback.phtml"%}
	{%include file="footer.phtml"%}
{% elseif $step=="complete" %}
	{%include file="header.phtml"%}
	<div id="yorozuUseFinish">
		<div class="content" style="background:#f0f5e0;">
			<div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/toolbox.gif" width="230" height="60" /><br />
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
				{%$item.item_name%}<br />
			</div><!--/.headline-->
			<div class="inner">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{%$item.item_name%}を使いました!<br />
				{%include file="common/ad_192x106.phtml"%}
				<div class="toRestaurant" style="text-align:center;">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="5" /><br />
					{% if $kitchenId == 0 %}
						{% if $itemId==19 %}
							<span style="color:#ff9999;">≫</span><a href='{% "$baseUrl/mobile/kitchenwrapper/changecharaswf?opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$uid`&rand=`$rand`"|mobile_flashurl %}'>シェフ設定画面へ</a><span style="color:#ff9999;">≪</span><br />
						{% else %}
							<span style="color:#ff9999;">≫</span><a href='{% "$baseUrl/mobile/kitchen/home"|mixiurl %}'>Myレストランへ</a><span style="color:#ff9999;">≪</span><br />
						{% /if %}
					{% else %}
						<span style="color:#ff9999;">≫</span><a href='{% "$baseUrl/mobile/kitchenflash/kitchen?CF_uid=`$uid`&opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$uid`&rand=`$rand`"|mobile_flashurl %}' accesskey="5">マイキッチンへ</a><span style="color:#ff9999;">≪</span><br />
					{% /if %}
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
				</div><!--/.toRestaurant-->
				<div class="toShopNav" style="text-align:center;">
					<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					{% emoji code="F9A0" %}<a href='{% "$baseUrl/mobile/kitchenshop/itemlist"|mixiurl %}'>デパートでどうぐを買おう</a><br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
				</div><!--/.toShopNav-->
				<div class="footlink">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchenitem/item"|mixiurl %}'>どうぐばこ</a><br />
					{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchenitem/index"|mixiurl %}'>アイテムBOX</a><br />
				</div><!--/.footlink-->
			</div><!--/.inner-->
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
		</div><!--/.content-->
	</div><!--/#yorozuUseFinish-->
	{%include file="common/menu.phtml"%}
	{%include file="footer.phtml"%}
{% elseif $step=="caution"%}
	{%include file="header.phtml"%}
	<div id="yorozuUseCaution">
		<div class="content" style="background:#f0f5e0;">
			<div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/toolbox.gif" width="230" height="60" /><br />
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
				{%$item.item_name%}<br />
			</div><!--/.headline-->
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% if $item.item_id==20 || $item.item_id==21 %}
				こちらのどうぐはマイミクのキッチンから使用してください<br />
				{% else %}
				こちらのどうぐはマイキッチンから使用してください<br />
				{% /if %}
			</div><!--/.description-->
			<div class="thumb" style="text-align:center;">
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/yorozu/130x130/{%$item.item_picture%}.gif" width="130" height="130" style="margin:10px 0 3px 0;" /><br />
				<span style="color:#cc0000;">{%$item.item_name%}</span><br />
				{%$item.item_introduce%}<br />
			</div><!--/.thumb-->
			<div class="toMyKitchen" style="text-align:center;">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
				{% if $item.item_id==20 || $item.item_id==21 %}
				<span style="color:#ff9999;">≫</span><a href='{% "$baseUrl/mobile/kitchen/rankinglist"|mixiurl %}'>マイミクのキッチンへ</a><span style="color:#ff9999;">≪</span><br />
				{% else %}
				<span style="color:#ff9999;">≫</span><a href='{% "$baseUrl/mobile/kitchenflash/kitchen?CF_uid=`$uid`&opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$uid`&rand=`$rand`"|mobile_flashurl %}' accesskey="5">マイキッチンへ</a><span style="color:#ff9999;">≪</span><br />
				{% /if %}
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
			</div><!--/.toMyKitchen-->
			<div class="toShopNav" style="text-align:center;">
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9A0" %}<a href='{% "$baseUrl/mobile/kitchenshop/itemlist"|mixiurl %}'>デパートでどうぐを買おう</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.toShopNav-->
			<div class="footlink">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchenitem/item"|mixiurl %}'>どうぐばこ</a><br />
				{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchenitem/index"|mixiurl %}'>アイテムBOX</a><br />
			</div><!--/.footlink-->
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
		</div><!--/.content-->
	</div><!--/#yorozuUseCaution-->
	{%include file="common/menu.phtml"%}
	{%include file="footer.phtml"%}
{% elseif $step=="cautionTwo"%}
	{%include file="header.phtml"%}
	<div id="yorozuUseConfirm">
		<div class="content" style="background:#f0f5e0;">
			<div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/toolbox.gif" width="230" height="60" /><br />
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
				{%$item.item_name%}<br />
			</div><!--/.headline-->
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				このどうぐは使えません。<br />
			</div><!--/.description-->
			<div class="thumb" style="text-align:center;">
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/yorozu/130x130/{%$item.item_picture%}.gif" width="130" height="130" style="margin:3px 0;" /><br />
				{%$item.item_introduce%}<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
			</div><!--/.thumb-->
			
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#cc0000;">{% emoji code="F9DC" %}既に辞典に載っているﾚｼﾋﾟは全部覚えています｡</span><br />
				<span style="color:#cc0000;">{% emoji code="F9DC" %}ｶﾞﾁｬ食材を利用したﾚｼﾋﾟは覚えられません｡</span><br />
				<span style="color:#cc0000;">{% emoji code="F9DC" %}このﾚｼﾋﾟの料理ｼﾞｬﾝﾙに進むまで利用できません｡</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			</div><!--/.description-->
			
			<div class="toShopNav" style="text-align:center;">
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9A0" %}<a href='{% "$baseUrl/mobile/kitchenshop/itemlist"|mixiurl %}'>デパートでどうぐを買おう</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.toShopNav-->
			<div class="footlink">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchenitem/item"|mixiurl %}'>どうぐばこ</a><br />
				{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchenitem/index"|mixiurl %}'>アイテムBOX</a><br />
			</div><!--/.footlink-->
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
		</div><!--/.content-->
	</div><!--/#yorozuUseConfirm-->
	{%include file="common/browseback.phtml"%}
	{%include file="footer.phtml"%}
{% elseif $step=="recipeGot"%}
	{%include file="header.phtml"%}
	<div id="yorozuUseFinish">
		<div class="content" style="background:#f0f5e0;">
			<div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/toolbox.gif" width="230" height="60" /><br />
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
				{%$item.item_name%}<br />
			</div><!--/.headline-->
			<div class="inner">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{%$item.item_name%}を使いました!<br />
				{%include file="common/ad_192x106.phtml"%}
				
				<div class="description">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					シェフが新しいレシピを覚えたようです！<br />
				</div><!--/.description-->
				
				<div class="toRestaurant" style="text-align:center;">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="5" /><br />
					<span style="color:#ff9999;">≫</span><a href='{% "$baseUrl/mobile/kitchenitem/useitem/CF_step/recipeGotFinish/CF_recipeId/`$recipeInfo.recipe_id`/CF_itemId/`$itemId`"|mixiurl %}'>レシピを確認</a><span style="color:#ff9999;">≪</span><br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
				</div><!--/.toRestaurant-->
				<div class="toShopNav" style="text-align:center;">
					<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					{% emoji code="F9A0" %}<a href='{% "$baseUrl/mobile/kitchenshop/itemlist"|mixiurl %}'>デパートでどうぐを買おう</a><br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
				</div><!--/.toShopNav-->
				<div class="footlink">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchenitem/item"|mixiurl %}'>どうぐばこ</a><br />
					{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchenitem/index"|mixiurl %}'>アイテムBOX</a><br />
				</div><!--/.footlink-->
			</div><!--/.inner-->
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
		</div><!--/.content-->
	</div><!--/#yorozuUseFinish-->
	{%include file="common/menu.phtml"%}
	{%include file="footer.phtml"%}
{% elseif $step=="recipeGotFinish"%}
	{%include file="header.phtml"%}
	{%include file="common/ad_header.phtml"%}

	<div id="recipeSuccess">
		<div class="content" style="background:#ffffdd;">
			<div class="headline" style="background:#81623e;color:#ffffff;text-align:center;">
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/make.gif" width="230" height="60" /><br />
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
				{% emoji code="F99F" %}新レシピ誕生{% emoji code="F99F" %}<br />
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/recipe/success.gif" width="240" height="105" /><br />
			</div><!--/.headline-->
			<div class="congratulate" style="color:#cc0000;text-align:center;">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
				おめでとうございます{% emoji code="F99B" %}<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
			</div><!--/.congratulate-->
			<div class="description">
				レシピの開発に成功し、新メニュー「<span style="color:#cc0000;">{%$recipeInfo.recipe_name%}</span>」が誕生しました!<br />
			</div><!--/.description-->
			
			<div class="thumb" style="color:#cc0000;text-align:center;">
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/meal/130x130/{%$recipeInfo.f%}/{%$recipeInfo.n%}.gif" width="130" height="130" style="margin:3px 0;" /><br />
			</div><!--/.thumb-->
			
			<div class="toRestaurant" style="text-align:center;">
				さっそく調理してみよう！<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="5" /><br />
				<span style="color:#ff9999;">≫</span><a href='{% "$baseUrl/mobile/kitchenflash/kitchen?CF_uid=`$uid`&opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$uid`&rand=`$rand`"|mobile_flashurl %}' accesskey="5">マイキッチンへ</a><span style="color:#ff9999;">≪</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
			</div><!--/.toRestaurant-->
			
			<div class="toShopNav" style="text-align:center;">
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9A0" %}<a href='{% "$baseUrl/mobile/kitchenshop/itemlist"|mixiurl %}'>デパートでどうぐを買おう</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.toShopNav-->
			<div class="footlink">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchenitem/item"|mixiurl %}'>どうぐばこ</a><br />
				{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchenitem/index"|mixiurl %}'>アイテムBOX</a><br />
			</div><!--/.footlink-->
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="line" style="background:#81623e;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
		</div><!--/.content-->
	</div><!--/#recipeSuccess-->
	{%include file="common/menu.phtml"%}
	{%include file="ad_footer.phtml"%}
{% elseif $step=="spoonList"%}
	{%include file="header.phtml"%}
	<div id="yorozuUseConfirm">
		<div class="content" style="background:#f0f5e0;">
			<div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/toolbox.gif" width="230" height="60" /><br />				
			</div><!--/.headline-->
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				以下のアイテムが利用できます｡<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.description-->
			{% foreach from=$userSpoon item=data%}
				<div class="section">
					<table width="100%" cellpadding="0" cellspacing="0" border="0">
						<tr>
							<td style="width:44px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/yorozu/40x40/{%$data.item_picture%}.gif" width="40" height="40" style="margin:3px 0;" /></td>
							<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}">
								{%$data.item_name%}<br />
								{%$data.item_introduce%}<br />
								<div style="text-align:right;">数量:{%$data.item_count%} {% emoji code="F8F6" %}<a href='{% "$baseUrl/mobile/kitchenitem/useitem/CF_kitchen_id/`$kitchenId`/CF_itemId/`$data.item_id`/CF_uid/`$profileUid`"|mixiurl %}'>使用する</a>&nbsp;</div>
							</div></td>
						</tr>
					</table>
					<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
				</div><!--/.section-->
			{% /foreach %}
			
			<div class="toShopNav" style="text-align:center;">
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9A0" %}<a href='{% "$baseUrl/mobile/kitchenshop/itemlist"|mixiurl %}'>デパートでどうぐを買おう</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.toShopNav-->
			<div class="footlink">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchenitem/item"|mixiurl %}'>どうぐばこ</a><br />
				{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchenitem/index"|mixiurl %}'>アイテムBOX</a><br />
			</div><!--/.footlink-->
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
		</div><!--/.content-->
	</div><!--/#yorozuUseConfirm-->
	{%include file="common/browseback.phtml"%}
	{%include file="footer.phtml"%}	
	
{% /if %}
