<div id="faq">
    <div class="content" style="background:#f0f5e0;">
        <div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
            <img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/faq.gif" width="230" height="60" /><br />
        </div><!--/.headline-->
        <div class="inner">
            <div class="section">
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                <span style="color:#497d40;">{% emoji code="F998" %}不具合/バグを発見しました</span><br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				もし､不具合/ﾊﾞｸﾞを発見された場合は、弊社までお問い合わせください。また､公式ｺﾐｭﾆﾃｨにも<a href="http://m.mixi.jp/view_bbs.pl?id=50246181&comment_count=0&comm_id=4809835&guid=ON">ﾊﾞｸﾞ･不具合報告用ﾄﾋﾟｯｸ</a>を用意しておりますので､そちらも併せてご利用ください｡<br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
            </div><!--/.section-->
            <div class="section">
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                <span style="color:#497d40;">{% emoji code="F998" %}マイミクを招待したのに特典がもらえません</span><br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				特典が反映されるまで､2-3日お時間がかかります。<br />
				また以下の条件では特典対象になりません｡<br />
				・ｱﾌﾟﾘ登録後､ﾚｽﾄﾗﾝ開設までｹﾞｰﾑを進めていない人<br />
				・ｱﾌﾟﾘ招待ﾒｯｾｰｼﾞ以外からｱﾌﾟﾘ登録した人<br />
				・過去に当ｱﾌﾟﾘに登録経験がある人<br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
            </div><!--/.section-->
            <div class="section">
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                <span style="color:#497d40;">{% emoji code="F998" %}シェフの容姿を再度作成したい</span><br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				ｼｪﾌの容姿を再度作成することはできません。もし、どうしても変更したい場合には、美容室をご利用ください。ただし、美容室のご利用はﾚﾍﾞﾙ10からとなります。<br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
            </div><!--/.section-->
            <div class="section">
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                <span style="color:#497d40;">{% emoji code="F998" %}割引券でメダルの価格は割引になりますか?</span><br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                ﾒﾀﾞﾙの価格は割引になりません。割引券（ﾃﾞﾊﾟｰﾄｷﾞﾌﾄ券、ﾒﾀﾞﾙｶｰﾄﾞ、ﾌﾞﾗｯｸｶｰﾄﾞ）での割引は、各使用後1回まで、<span style="color:#cc0000;">ﾁｯﾌﾟでの購入時のみ適用となります</span>ので、注意してご利用いただければと思います。<br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
            </div><!--/.section-->
            <div class="section">
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                <span style="color:#497d40;">{% emoji code="F998" %}メダルはチップに交換できますか?</span><br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                ﾒﾀﾞﾙとﾁｯﾌﾟの交換はできません。ただし,ﾒﾀﾞﾙは、不動産屋を除く、ほぼすべてのｼｮｯﾌﾟでの購入にご利用いただけるようになっております。さらに、ﾒﾀﾞﾙでのみご利用可能なﾌﾟﾚﾐｱｶﾞﾁｬもございますので、ｹﾞｰﾑを進めていく上で効率的にご利用いただければと思います。<br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
            </div><!--/.section-->
            <div class="section">
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                <span style="color:#497d40;">{% emoji code="F998" %}食材・ざっか・どうぐをﾏｲﾐｸに贈りたい</span><br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                現状、ﾏｲﾐｸに贈ることができるｱｲﾃﾑはｷﾞﾌﾄのみとなります。ただし､ざっかについてはﾏｲﾐｸのお店に配置できるような機能を準備しています｡今しばらくお待ちください｡なお､ﾁｯﾌﾟやﾒﾀﾞﾙについても、他社に譲渡することができませんので、あらかじめご了承ください。<br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
            </div><!--/.section-->
            <div class="section">
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                <span style="color:#497d40;">{% emoji code="F998" %}プレミアガチャで希望の賞品がもらえなかった</span><br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				ﾌﾟﾚﾐｱｶﾞﾁｬは抽選となりますので、必ずしもご希望の景品が当たるとは限りません。再度ﾁｬﾚﾝｼﾞしていただければと思います。<br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
            </div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497D40;">{% emoji code="F998" %}ﾏｲﾐｸが｢ﾏｲﾐｸさんの運営ﾚｽﾄﾗﾝ｣に表示されない</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				｢ﾏｲﾐｸさんの運営ﾚｽﾄﾗﾝ｣のﾏｲﾐｸは､ﾚｽﾄﾗﾝを開設した人だけになります｡ｱﾌﾟﾘ登録後ｹﾞｰﾑを進めていないなどの場合は表示されませんのでご注意下さい｡<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497D40;">{% emoji code="F998" %}今の自分のﾚﾍﾞﾙと｢ﾏｲﾐｸさんの運営ﾚｽﾄﾗﾝ｣で表示されるﾚﾍﾞﾙが違う</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				｢ﾏｲﾐｸさんの運営ﾚｽﾄﾗﾝ｣に表示されるﾚﾍﾞﾙは洋食､ﾘｽﾄﾗﾝﾃなどのﾚﾍﾞﾙを全て合計した数字になります｡ざっかなどのﾚﾍﾞﾙ解放はそれぞれの料理ｼﾞｬﾝﾙごとのﾚﾍﾞﾙが対象になります｡<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497D40;">{% emoji code="F998" %}ﾏｲﾐｸ以外の人にｷﾞﾌﾄを贈りたい</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				ｷﾞﾌﾄを贈りたいﾕｰｻﾞｰのﾏｲﾚｽﾄﾗﾝへ移動した後に､｢ｷﾞﾌﾄｾｯﾄを配送する｣をｸﾘｯｸします｡<br />
				その後､贈りたいｷﾞﾌﾄを選択されることでｷﾞﾌﾄを贈ることができます｡<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			
            <div class="section">
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                <span style="color:#497d40;">{% emoji code="F998" %}お問い合わせをしたが返信が来ません</span><br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					ﾕｰｻﾞｰの皆様から頂戴したお問い合わせに関し､担当者が1件1件目を通し“必ず”返信をさせていただいております｡<br />
					<br />
					ただし､お客様が以下ﾄﾞﾒｲﾝでのﾒｰﾙ受信を許可していない場合､せっかくお問い合わせいただいたにも関わらず､弊社担当者が返信できないことがございます｡<br />
					<br />
					<form method="get" action="#"><input type="text" value="communityfactory.com" style="color:#000;background:#fff;" /></form><br />
					<br />
					もしも､｢問い合わせをしたのに返信がない!｣と､お心当たりがある場合は､<span style="color:#cc0000;">上記のﾄﾞﾒｲﾝのﾒｰﾙを受信できるように設定</span>し､再度お問い合わせください｡<br />
					<br />
					なお､公式ｺﾐｭﾆﾃｨに関しては､原則､返信を行っておりませんので､回答をお求めの場合は､ﾒｰﾙにてお問い合わせいただけたら幸いです｡<br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
            </div><!--/.section-->
        </div><!--/.inner-->
        <div class="footlink">
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
            {% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchenstatic/help"|mixiurl %}'>ヘルプ:もくじ</a><br />
        </div><!--/.footlink-->
        <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
        <div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
    </div><!--/.content-->
</div><!--/#faq-->
