{%include file="error/common/header.phtml"%}

<div id="error">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			アクセスエラー<br />
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
		</div><!--/.headline-->
		<div class="description">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			大変申し訳ございませんが、お客様の携帯電話には対応しておりません。<br />
			<br />
            <div style="text-align:center;">
                {% if $ua == 1 %}
                <a href="http://m.mixi.jp/view_appli.pl?id=6230&guid=ON">
                {% else %}
                <a href="http://m.mixi.jp/view_appli.pl?id=6230">
                {% /if %}
                                ﾏｲﾐｸ同士でﾊﾞﾄﾙﾛﾜｲﾔﾙ!<br />
                                どきどきﾀﾞｲﾅﾏｲﾄﾊﾟﾆｯｸ<br />
                </a>
            </div>
		</div><!--/.description-->

        <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
        <div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
    </div><!--/.content-->
</div><!--/#error-->

{%include file="common/menu.phtml"%}
{%include file="error/common/footer.phtml"%}
