{%include file="header.phtml"%}
<div id="goldlist">
	<div class="content" style="background:#eeffff;">
		<div class="headline" style="background:#82bdba;text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/bank.gif" width="230" height="60" /><br />
		</div><!--/#headline-->
		<div class="money">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<table width="220" cellpadding="3" cellspacing="1" border="0" align="center" style="background:#82bdba;">
				<tr>
					<td style="background:#ffffee;text-align:center;"><div style="{% if $ua==1 %}font-size:x-small;{%/if%}">
						{% if $gold >= 1000000 || $point >= 1000000 %}
							{% emoji code="F8C8" %}所持M {% $gold|string_format:"%'#7s"|replace:"#":"&nbsp;" %}<br />
							{% emoji code="F8E5" %}所持T {% $point|string_format:"%'#7s"|replace:"#":"&nbsp;" %}<br />
						{% elseif $gold >= 100000 || $point >= 100000 %}
							{% emoji code="F8C8" %}所持M {% $gold|string_format:"%'#6s"|replace:"#":"&nbsp;" %}<br />
							{% emoji code="F8E5" %}所持T {% $point|string_format:"%'#6s"|replace:"#":"&nbsp;" %}<br />
						{% else %}
							{% emoji code="F8C8" %}所持M {% $gold|string_format:"%'#5s"|replace:"#":"&nbsp;" %}<br />
							{% emoji code="F8E5" %}所持T {% $point|string_format:"%'#5s"|replace:"#":"&nbsp;" %}<br />
						{% /if %}
					</div></td>
				</tr>
			</table>
		</div><!--/.money-->
		<div class="description">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			ﾌﾟﾚﾐｱｶﾞﾁｬなどに使えるﾒﾀﾞﾙの購入はｺﾁﾗ!<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div style="background:#82bdba;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
		</div><!--/.description-->
		<div class="inner">
			{% foreach from=$goldList item=data key=key %}
			<div class="section">
				<table width="100%" cellpadding="0" cellspacing="0" border="0">
					<tr>
						<td style="width:44px;text-align:center;vertical-align:top;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/bank/40x40/{% $data.gold_picture %}?100310" width="40" height="40" style="margin:3px 0;" /></td>
						<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}"><a href='{% "$baseUrl/mobile/kitchengold/goldconfirm?CF_gold_id=`$data.id`"|mixiurl %}'>{% $data.gold_name %}</a><br />
							{% $data.gold_introduce %}<br />
						</div></td>
					</tr>
				</table>
				<div style="background:#82bdba;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			{% /foreach %}
		</div><!--/.inner-->
		
		<div class="toInvite" style="text-align:center;">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% emoji code="F8E6" %}<a href='{% "$baseUrl/mobile/kitchen/inviteguide"|mixiurl %}'>ﾏｲﾐｸ招待で100M+ﾌﾟﾚﾐｱｶﾞﾁｬ</a><br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div style="background:#82bdba;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
		</div><!--/.toInvite-->
		
		<div class="footlink">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{%/if%}<a href='{% "$baseUrl/mobile/kitchenshop/shopping"|mixiurl %}'>マイキチデパート</a><br />
			{% emoji code="F8C4" %}<a href='{% "$baseUrl/mobile/kitchen/home"|mixiurl %}'>Myレストラン</a><br />
		</div><!--/.footlink-->
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#82bdba;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/.goldlist-->
{%include file="common/menu.phtml"%}
{%include file="footer.phtml"%}
