{%include file="header.phtml"%}
<div id="goldconfirm">
	<div class="content" style="background:#eeffff;">
		<div class="headline" style="background:#82bdba;color:#ffffff;text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/bank.gif" width="230" height="60" /><br />
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			{% $goldInfo.gold_name %}<br />
		</div><!--/.headline-->
		<div class="description">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			こちらのﾒﾀﾞﾙを購入しますか?
		</div><!--/.description-->
		<div class="thumb" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/bank/130x130/{% $goldInfo.gold_picture %}?100310" width="130" height="130" style="margin:3px 0;" /><br />
			{% $goldInfo.gold_introduce %}<br />
		</div><!--/.thumb-->
		<div class="account">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<table width="150" cellpadding="0" cellspacing="0" border="0" align="center" style="text-align:center;">
				<tr>
					<td colspan="2"><div class="line" style="background:#82bdba;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div></td>
				</tr>
				<tr>
					<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}text-align:left;">{% emoji code="F8C8" %}所持M</div></td>
					<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}text-align:left;">{% $gold %}M</div></td>
				</tr>
				<tr>
					<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}text-align:left;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/bank/mixipt_for_mobile.gif" width="16" height="16" style="vertical-align:middle;" /></div></td>
					<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}text-align:left;">{% $goldInfo.gold_price %}Pt</div></td>
				</tr>
				<tr>
					<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}text-align:left;">{% emoji code="F8C8" %}購入後M</div></td>
					<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}text-align:left;">{% $gold+$goldInfo.gold_value %}M</div></td>
				</tr>
				<tr>
					<td colspan="2"><div class="line" style="background:#82bdba;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div></td>
				</tr>
			</table>
		</div><!--/.account-->

		<div class="buy" style="color:#cc0000;text-align:center;">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
				<a href='{% "$baseUrl/mobile/kitchengold/buygoldsend?CF_gold_id=`$goldInfo.id`"|mixiurl %}'><span style="color:#cc0000;">購入する</span></a><br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
		</div><!--/.buy-->

		<div class="toCompanyInfo">
			<div style="background:#82bdba;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% emoji code="F8E4" %}<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=1002"|mixiurl %}'>特定商取引法に基づく表記</a><br />
			{% emoji code="F8E4" %}<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=1003"|mixiurl %}'>プライバシーポリシー</a><br />
		</div><!--/.toCompanyInfo-->

		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#82bdba;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/.goldconfirm-->


{%include file="common/menu.phtml"%}
{%include file="footer.phtml"%}