{%include file="header.phtml"%}
<div id="goldfinish">
	<div class="content" style="background:#eeffff;">
		<div class="headline" style="background:#82bdba;color:#ffffff;text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/bank.gif" width="230" height="60" /><br />
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			購入完了<br />
		</div><!--/.headline-->
		<div class="inner">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			ﾒﾀﾞﾙの購入が完了しました!所有ﾒﾀﾞﾙが{% $gold-$goldInfo.gold_value %}M増え､{% $gold %}Mになりました。<br />
			{%include file="common/ad_middle.phtml"%}
		</div><!--/.inner-->
		<div class="toShop" style="text-align:center;">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
			<span style="color:#ff9999;">≫</span><a href='{% "$baseUrl/mobile/kitchengold/goldlist"|mixiurl %}'>買い物を続ける</a><span style="color:#ff9999;">≪</span><br/>
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
		</div><!--/.toShop-->
		<div class="toInvite" style="text-align:center;">
			<div style="background:#82bdba;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% emoji code="F8E6" %}<a href='{% "$baseUrl/mobile/kitchen/inviteguide"|mixiurl %}'>ﾏｲﾐｸ招待で100M+ﾌﾟﾚﾐｱｶﾞﾁｬ</a><br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div style="background:#82bdba;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
		</div><!--/.toInvite-->
		<div class="footlink">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{%/if%}<a href='{% "$baseUrl/mobile/kitchenshop/shopping"|mixiurl %}'>マイキチデパート</a><br />
			{% emoji code="F8C4" %}<a href='{% "$baseUrl/mobile/kitchen/home"|mixiurl %}'>Myレストラン</a><br />
		</div><!--/.footlink-->
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#82bdba;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>	
	</div><!--/.content-->
</div><!--/.goldfinish-->

{%include file="common/menu.phtml"%}
{%include file="footer.phtml"%}