{%include file="header.phtml"%}
{%include file="common/ad_header.phtml"%}

<div id="help">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
			<img src="img/title/help.gif" width="230" height="60" /><br />
			<img src="img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			見出し◆あああああああああああ<br />
		</div><!--/.headline-->
		<div class="inner">
			<img src="img/spacer.gif" width="1" height="3" /><br />
			ああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ<br />
		</div><!--/.inner-->
		<div class="footlink">
			<img src="img/spacer.gif" width="1" height="3" /><br />
			<div style="background:#8bbd82;text-align:center;"><img src="img/line.gif" width="230" height="1" /></div>
			<img src="img/spacer.gif" width="1" height="3" /><br />
			<span style="color:#ff9999;">⇒</span><a href="#">ﾍﾙﾌﾟ:目次</a><br />
		</div><!--/.footlink-->
		<img src="img/spacer.gif" width="1" height="3" /><br />
		<div class="line" style="background:#8bbd82;"><img src="img/spacer.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#help-->

{%include file="common/menu.phtml"%}
{%include file="footer.phtml"%}
