<div id="news">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/news.gif?100205" width="240" height="60" /><br />
		</div><!--/#headline-->
		<div class="inner">
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年2月11日(木)]<br />
				日記ｷｬﾝﾍﾟｰﾝのﾁｯﾌﾟ付与</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				日頃より当ｱﾌﾟﾘをご利用いただきありがとうございます｡<br />
				<br />
				本日2月9日まで行なわれた日記投稿ｷｬﾝﾍﾟｰﾝのﾁｯﾌﾟを付与いたしました｡<br />
				<br />
				なお､今回のﾁｯﾌﾟ付与に関しまして弊社の日記投稿集計ｼｽﾃﾑに問題が生じ､日記投稿内容の確認が不可能となりました｡<br />
				<br />
				そのため今回はｱﾌﾟﾘをご利用いただいているすべての方に1000Tを付与しております｡<br />
				<br />
				この度は弊社の不手際でｷｬﾝﾍﾟｰﾝを成立させることができず､大変申し訳ございませんでした｡<br />
				<br />
				日記を投稿頂いた方には深くお詫び申し上げます｡<br />
				<br />
				本日より日記投稿ｷｬﾝﾍﾟｰﾝの第2弾を開始しましたので､ぜひ今回のｷｬﾝﾍﾟｰﾝにもご応募いただきますようお願いいたします｡<br />
				<br />
				<div style="text-align:center;">
					↓↓紹介日記で500T↓↓<br />
					<span style="color:#006699;text-decoration:blink;">≫</span><a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100210_campaign"|mixiurl %}'>紹介日記500T[第2弾]ｽﾀｰﾄ!</a><span style="color:#006699;text-decoration:blink;">≪</span><br />
				</div>
				<br />
				今後ともようこそﾏｲｷｯﾁﾝをよろしくお願いいたします｡<br />
				<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="caution">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9DC" %}ｻｰﾋﾞｽに関する不明点・疑問を感じた場合は､「<a href='{% "$baseUrl/mobile/kitchenstatic/qa"|mixiurl %}'>よくある質問</a>」をご覧ください｡<br />
			</div><!--/.caution-->
        </div><!--/.inner-->
	    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#news-->
{%include file="common/menu.phtml"%}
