<div id="news">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/news.gif?100205" width="240" height="60" /><br />
		</div><!--/#headline-->
		<div class="inner">
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年2月9日(火)]<br />
				公開設定機能を追加しました</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				日頃より当ｱﾌﾟﾘをご利用いただきありがとうございます｡<br />
				<br />
				さまざまなお客様よりお問い合わせいただいている<br />
				<br />
				｢ﾏｲﾐｸｼｨ以外のﾕｰｻﾞｰから味見･味付け･ﾊｴ飛ばす･ﾊｴ撃退をできないようにして欲しい｣<br />
				<br />
				という要望に対応して､<span style="color:#cc0000;">【ｷｯﾁﾝの公開設定機能】</span>を追加しました｡<br />
				<br />
				ｷｯﾁﾝの公開設定では､<br />
				・｢全体公開[誰でも訪問]｣<br />
				・｢限定公開[ﾏｲﾐｸのみ訪問]」<br />
				の2種をお選びいただけます｡<br />
				※｢非公開｣はｹﾞｰﾑの特性上､追加予定はありません｡何卒ご理解のほどお願いいたします｡<br />
				<br />
				なお､ｷｯﾁﾝの公開設定機能については、Myﾚｽﾄﾗﾝ画面の来店履歴の下部分よりいつでも設定変更が可能となります。<br />
				<br />
				<div style="text-align:center;">
					↓↓お急ぎの場合はｺﾁﾗ↓↓<br />
					<span style="color:#006699;text-decoration:blink;">≫</span><a href='{% "$baseUrl/mobile/kitchenfirst/editaccess"|mixiurl %}'>キッチン公開設定</a><span style="color:#006699;text-decoration:blink;">≪</span><br />
				</div>
				<br />
				ｷｯﾁﾝ公開設定にてﾏｲﾐｸのみに変更した場合､ﾏｲﾐｸ以外のﾕｰｻﾞｰからﾊｴ撃退や味付けもご協力いただけなくなりますのでご注意ください｡<br />
				<br />
				今後ともようこそﾏｲｷｯﾁﾝをよろしくお願いいたします｡<br />
				<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="caution">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9DC" %}ｻｰﾋﾞｽに関する不明点・疑問を感じた場合は､「<a href='{% "$baseUrl/mobile/kitchenstatic/qa"|mixiurl %}'>よくある質問</a>」をご覧ください｡<br />
			</div><!--/.caution-->
        </div><!--/.inner-->
	    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#news-->
{%include file="common/menu.phtml"%}
