<div id="news">
	<div class="content" style="background:#fff5f5;">
		<div class="headline" style="background:#ff9999;color:#ffffff;text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			日記投稿キャンペーン<br />
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
		</div><!--/#headline-->
		<div class="banner" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/campaign/100211.gif?" width="192" height="53" style="margin-top:3px;" /><br />
			日記投稿で必ず貰える<br />2月末日までの期間限定ｷｬﾝﾍﾟｰﾝ!<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<span style="color:#cc0000;">※こちらのｷｬﾝﾍﾟｰﾝは終了しました<br />
			ご投稿ありがとうございました</span><br />
		</div><!--/.banner-->
		<div class="section">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#ff9999;color:#ffffff;">
				{% emoji code="F8E6" %}景品<br />
			</div><!--/.headline-->
			<div class="inner">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F8E5" %}500T<br />
				<span style="color:#cc0000;">※必ずもらえます!</span><br />
				※当ｱﾌﾟﾘ内で利用できる仮想通貨<br />
			</div><!--/.inner-->
		</div><!--/.section-->
		<div class="section">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#ff9999;color:#ffffff;">
				{% emoji code="F991" %}プレゼント対象<br />
			</div><!--/.headline-->
			<div class="inner">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				ｱﾌﾟﾘ紹介日記を<span style="color:#cc0000;">[全体に公開]</span>で投稿した方<br />
				{% emoji code="F991" %}<span style="color:#ff6666;">当ｱﾌﾟﾘの名前とURL､今回の投稿ｷｰﾜｰﾄﾞが含まれていればﾌﾟﾚｾﾞﾝﾄ対象</span>となります<br />
				{% emoji code="F9DC" %}前回応募した方も再応募できます<br />
				{% emoji code="F9DC" %}今回の投稿ｷｰﾜｰﾄﾞでmixi日記 検索結果に含まれない場合はﾌﾟﾚｾﾞﾝﾄ対象外となりますのでご注意ください<br />
			</div><!--/.inner-->
		</div><!--/.section-->
		<div class="section">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#ff9999;color:#ffffff;">
				{% emoji code="F8EA" %}キャンペーン期間<br />
			</div><!--/.headline-->
			<div class="inner">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#cc0000;">2月末日 24:00までの期間限定!</span><br />
				※お1人様500Tまで付与!<br />
			</div><!--/.inner-->
		</div><!--/.section-->
		<div class="section">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#ff9999;color:#ffffff;">
				{% emoji code="F8F5" %}プレゼント付与予定<br />
			</div><!--/.headline-->
			<div class="inner">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#cc0000;">3月第1週中を予定</span><br />
				{% emoji code="F9DC" %}当選は付与をもって代えさせていただきます<br />
				{% emoji code="F9DC" %}日記投稿直後に付与されるものではありません<br />
				{% emoji code="F9DC" %}付与された旨は通知されません<br />
				{% emoji code="F9DC" %}付与の有無に関するお問い合わせには応じられません<br />
			</div><!--/.inner-->
		</div><!--/.section-->
		{%*
			<div class="toDiary" style="text-align:center;">
				<br />
				<span style="color:#cc0000;">そのまま投稿でもOK!<br />
				このﾁｬﾝｽをお見逃しなく!<br />
				↓↓↓↓↓↓↓↓</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% assign var="diary_title" value="ようこそマイキッチン" %}
				{% assign var="diary_body" value="◎ようこそマイキッチン\nhttp://mixi.jp/view_appli.pl?id=16235\n\nケータイで遊べる、ほのぼの系お料理ゲーム！\n\n「レシピ開発ハマってます！」" %}
				<table width="220" cellpadding="3" cellspacing="1" border="0" align="center" style="background:#ff9999;">
					<tr>
						<td style="background:#ffffdd;text-align:center;"><div style="{% if $ua==1 %}font-size:x-small;{%/if%}">
							<span style="color:#cc0000;">2月末までの特別企画!</span><br />
							キャンペーン日記の投稿で<br />
							もれなく{% emoji code="F8E5" %}500Tﾌﾟﾚｾﾞﾝﾄ!<br />
							<form method="get" action="http://m.mixi.jp/add_diary.pl">
								<input type="hidden" name="diary_title" value="{% $diary_title %}" />
								<input type="hidden" name="diary_body" value="{% $diary_body %}" />
								<input type="submit" value=" キャンペーン日記を書く " /><br />
							</form>
							</div></td>
					</tr>
				</table>
			</div><!--/.toDiary-->
		*%}
		<br />
		<br />
	    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#ff9999;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#news-->

{%include file="common/browseback.phtml"%}
