<div id="news">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/news.gif?100205" width="240" height="60" /><br />
		</div><!--/#headline-->
		<div class="inner">
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年2月19日(金)]<br />
				新ｼﾞｬﾝﾙ追加予定のご案内</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				日頃より当ｱﾌﾟﾘをご利用いただきありがとうございます｡<br />
				<br />
				当ｱﾌﾟﾘでは皆様よりたくさんのご要望をいただいている､ｽｲｰﾂ(仮)の料理ｼﾞｬﾝﾙ追加を予定しています｡<br />
				ﾚｼﾋﾟや食材はもちろん､ざっかまで全てｽｲｰﾂに関連したものになりますのでご期待下さい｡<br />
				ｽｲｰﾂの料理ｼﾞｬﾝﾙ追加は3月中のｵｰﾌﾟﾝを目指しております｡<br />
				<br />
				料理ｼﾞｬﾝﾙの追加以外にも､ｷｯﾁﾝ画面の使いやすさの向上や不具合の修正も鋭意取り組んでおりますので今しばらくお待ち下さい｡<br />
				<br />
				今後ともﾕｰｻﾞｰの皆様にご満足いただけるｻｰﾋﾞｽになるよう努力してまいりますので､引き続き｢ようこそﾏｲｷｯﾁﾝ｣をよろしくお願いいたします｡<br />
				<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="caution">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9DC" %}ｻｰﾋﾞｽに関する不明点・疑問を感じた場合は､「<a href='{% "$baseUrl/mobile/kitchenstatic/qa"|mixiurl %}'>よくある質問</a>」をご覧ください｡<br />
			</div><!--/.caution-->
        </div><!--/.inner-->
	    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#news-->
{%include file="common/menu.phtml"%}
