<div id="news">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/news.gif?100205" width="240" height="60" /><br />
		</div><!--/#headline-->
		<div class="inner">
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年2月23日(火)]<br />
				200M進呈のご報告</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				日頃より当ｱﾌﾟﾘをご利用いただきありがとうございます｡<br />
				<br />
				先日のｱｸｾｽ障害によりﾕｰｻﾞｰの皆さまに多大なるご迷惑をおかけしてしまい申し訳ございませんでした｡<br />
				そこで､わずかばかりではございますが､先程全てのご利用者の方々に200Mを進呈いたしました｡<br />
				<br />
				Myﾚｽﾄﾗﾝﾍﾟｰｼﾞをご覧いただけますと所持ﾒﾀﾞﾙが増えているのが確認できるかと思います｡<br />
				尚､ﾒﾀﾞﾙ進呈に関するお知らせはこちらのﾍﾟｰｼﾞ以外にはありませんのでご注意ください｡<br />
				<br />
				この度はご利用の皆さまにはご不便をおかけしまして大変申し訳ございません｡<br />
				改めてお詫び申し上げます｡<br />
				<br />
				今回の件については厳しく反省を行い､より一層皆さまに愛されるｻｰﾋﾞｽとなれるよう努力してまいります｡<br />
				<br />
				今後とも｢ようこそマイキッチン｣を宜しくお願いいたします｡<br />
				<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="caution">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9DC" %}ｻｰﾋﾞｽに関する不明点・疑問を感じた場合は､「<a href='{% "$baseUrl/mobile/kitchenstatic/qa"|mixiurl %}'>よくある質問</a>」をご覧ください｡<br />
			</div><!--/.caution-->
        </div><!--/.inner-->
	    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#news-->
{%include file="common/menu.phtml"%}
