<div id="news">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/news.gif?100205" width="240" height="60" /><br />
		</div><!--/#headline-->
		<div class="inner">
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年2月11日(木)]<br />
				新ﾚｼﾋﾟ追加のご案内</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				日頃より当ｱﾌﾟﾘをご利用いただきありがとうございます｡<br />
				<br />
				本日、新しいﾚｼﾋﾟを12種類追加しました。新しいﾚｼﾋﾟについてはﾚｼﾋﾟ図鑑よりご確認いただけます｡<br />
				<br />
				今後もﾚｼﾋﾟ・ざっか・料理ｼﾞｬﾝﾙの追加などを準備ができ次第､順次行ってまいりますのでご期待ください｡<br />
				<br />
				また今後の追加内容に関するﾘｸｴｽﾄは公式ｺﾐｭﾆﾃｨまでお願いします｡<br />
				<br />
				皆さまのご意見にできるだけ応え､皆さまに愛されるｻｰﾋﾞｽを目指してまいります｡<br />
				<br />
				今後とも｢ようこそﾏｲｷｯﾁﾝ｣をよろしくお願いいたします｡<br />
				<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="caution">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9DC" %}ｻｰﾋﾞｽに関する不明点・疑問を感じた場合は､「<a href='{% "$baseUrl/mobile/kitchenstatic/qa"|mixiurl %}'>よくある質問</a>」をご覧ください｡<br />
			</div><!--/.caution-->
        </div><!--/.inner-->
	    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#news-->
{%include file="common/menu.phtml"%}
