<div id="news">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/news.gif?100205" width="240" height="60" /><br />
		</div><!--/#headline-->
		<div class="inner">
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年2月15日(月)]<br />
				アクセス負荷対応について</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				日頃より当ｱﾌﾟﾘをご利用いただき､誠にありがとうございます｡<br />
				<br />
				既におしらせしております､2月12日のｻｰﾊﾞｰ増強の結果ですが､今までのところ目立った効果もなく､引き続きアクセス障害が発生している状況となり､ご利用者の皆様にはご迷惑をおかけしまして大変申し訳ございません｡<br />
				<br />
				引き続き対応を行なっておりますが､先日ｻｰﾊﾞｰ増強を行なった直後という事もあり次の対応までには1週間ほどお時間をいただいてしまいます｡<br />
				<br />
				もちろん､それまでの期間中にもｱｸｾｽ負荷を軽減する調整は出来るだけ行なっていく予定でございますが､ｱｸｾｽ負荷が大きすぎる状況の中､快適にｱｸｾｽできるまでの状態に戻すまでの対応は非常に難しい状態となります｡<br />
				<br />
				ご利用中の皆様に対して快適なｻｰﾋﾞｽをお送りできない今の状況は､非常に心苦しいのですが､今しばらくお待ちいただけますよう何卒よろしくお願いいたします｡<br />
				<br />
				これからもｽﾀｯﾌ一同､未熟ながらも一生懸命努力してまいりますので､今後とも｢ようこそﾏｲｷｯﾁﾝ｣をよろしくお願いいたします｡<br />
				<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="caution">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9DC" %}ｻｰﾋﾞｽに関する不明点・疑問を感じた場合は､「<a href='{% "$baseUrl/mobile/kitchenstatic/qa"|mixiurl %}'>よくある質問</a>」をご覧ください｡<br />
			</div><!--/.caution-->
        </div><!--/.inner-->
	    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#news-->
{%include file="common/menu.phtml"%}
