<div id="news">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/news.gif?100205" width="240" height="60" /><br />
		</div><!--/#headline-->
		<div class="inner">
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年2月11日(木)]<br />
				公開設定機能の変更</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				日頃より当ｱﾌﾟﾘをご利用いただきありがとうございます｡<br />
				<br />
				先日ﾘﾘｰｽいたしました「公開設定機能」について<br />
				<br />
				｢ﾏｲﾐｸ限定公開を設定している場合は全体公開のﾕｰｻﾞｰに訪問できないようにしてほしい｣<br />
				<br />
				｢ﾏｲﾐｸ限定公開にしても画面ﾒﾓやﾌﾞｯｸﾏｰｸなどから味見されてしまう｣<br />
				<br />
				というご要望に応え､ｷｯﾁﾝの公開設定機能の内容を一部変更いたしました｡<br />
				<br />
				変更内容は次の通りです｡<br />
				<br />
				1)ﾏｲﾐｸ限定公開にしている場合､ﾏｲﾐｸｼｨ以外の方のｷｯﾁﾝに訪問できなくなります<br />
				<br />
				2)ﾌﾞｯｸﾏｰｸした画面から味見などを行った場合､不正なｱｸｼｮﾝとみなします<br />
				<br />
				なお､現状は､公開設定の変更に関する制限を設けておりませんが､<span style="color:#cc0000;">一部のﾕｰｻﾞｰによる明らかなﾏﾅｰ違反と考えられる悪質行為が目立つ場合､公開設定の変更に関するに制限を設けることも検討</span>しております｡<br />
				<br />
				もしﾏｲﾐｸではないﾕｰｻﾞｰからのﾏﾅｰ違反と考えられる行為を発見いたしましたら､運営事務局までお問い合わせください｡また､そのような<span style="color:#cc0000;">ご不快な思いをしたくない場合は､あらかじめ[ﾏｲﾐｸ限定公開]</span>でご利用なさることを推奨いたします｡<br />
				<br />
				今後も皆さまのご意見を真摯に受け止め、より一層のｻｰﾋﾞｽ改善に取り組んでまいります｡ｻｰﾋﾞｽに関して何かお気づきの点がございましたら､正直なご意見をお問い合わせください｡<br />
				<br />
				今後とも｢ようこそﾏｲｷｯﾁﾝ｣をよろしくお願いいたします｡<br />
				<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="caution">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9DC" %}ｻｰﾋﾞｽに関する不明点・疑問を感じた場合は､「<a href='{% "$baseUrl/mobile/kitchenstatic/qa"|mixiurl %}'>よくある質問</a>」をご覧ください｡<br />
			</div><!--/.caution-->
        </div><!--/.inner-->
	    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#news-->
{%include file="common/menu.phtml"%}
