<div id="news">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/news.gif?100205" width="240" height="60" /><br />
		</div><!--/#headline-->
		<div class="inner">
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年2月24日(水)]<br />
				ﾏｲﾐｸ招待ｷｬﾝﾍﾟｰﾝ延長のご案内</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				日頃より当ｱﾌﾟﾘをご利用いただきありがとうございます｡<br />
				<br />
				先日のｱｸｾｽ障害の時よりmixiｱﾌﾟﾘの規定にて新規ｱﾌﾟﾘ登録ができない状態になっておりましたが､先程制限が解除され､現在は新規ｱﾌﾟﾘ登録が可能な状態になっております｡<br />
				<br />
				皆さまにはご報告が遅れてしまい大変申し訳ございません｡<br />
				<br />
				新規ｱﾌﾟﾘ登録制限があったためにﾏｲﾐｸを招待が成立しない状況がありましたので､現在行なっておりますﾏｲﾐｸ招待ｷｬﾝﾍﾟｰﾝを延長することにいたしました｡<br />
				<br />
				延長期間は以下の通りとなります｡<br />
				<br />
				[現在]<br />
				2月28日(日)24:00まで<br />
				&nbsp;↓<br />
				[延長後]<br />
				3月7日(日)24:00まで<br />
				<br />
				<div style="text-align:center;">
					≫<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100206_campaign"|mixiurl %}'>ﾏｲﾐｸ招待ｷｬﾝﾍﾟｰﾝ詳細</a>≪<br />
				</div>			
				<br />
				今後とも｢ようこそマイキッチン｣をよろしくお願いいたします｡<br />
				<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="caution">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9DC" %}ｻｰﾋﾞｽに関する不明点・疑問を感じた場合は､「<a href='{% "$baseUrl/mobile/kitchenstatic/qa"|mixiurl %}'>よくある質問</a>」をご覧ください｡<br />
			</div><!--/.caution-->
        </div><!--/.inner-->
	    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#news-->
{%include file="common/menu.phtml"%}
