<div id="news">
	<div class="content" style="background:#fff5f5;">
		<div class="headline" style="background:#ff9999;color:#ffffff;text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			日記投稿キャンペーン<br />
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
		</div><!--/#headline-->
		<div class="banner" style="color:#cc0000;text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/campaign/100205.gif?" width="192" height="53" style="margin-top:3px;" /><br />
			日記投稿で必ず貰える<br />2/9までの期間限定ｷｬﾝﾍﾟｰﾝ!<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			※こちらのｷｬﾝﾍﾟｰﾝは終了しました<br />
			ご投稿ありがとうございました<br />
		</div><!--/.banner-->
		<div class="section">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#ff9999;color:#ffffff;">
				{% emoji code="F8E6" %}景品<br />
			</div><!--/.headline-->
			<div class="inner">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F8E5" %}1000T<br />
				<span style="color:#cc0000;">※かならずもらえます!</span><br />
				※当ｱﾌﾟﾘ内でご利用いただける仮想通貨<br />
			</div><!--/.inner-->
		</div><!--/.section-->
		<div class="section">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#ff9999;color:#ffffff;">
				{% emoji code="F991" %}プレゼント対象<br />
			</div><!--/.headline-->
			<div class="inner">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				ｱﾌﾟﾘ紹介日記を<span style="color:#cc0000;">[全体に公開]</span>で投稿した方<br />
				{% emoji code="F991" %}<span style="color:#ff6666;">当ｱﾌﾟﾘの名前とURLさえ含まれていればﾌﾟﾚｾﾞﾝﾄ対象</span>となります<br />
				{% emoji code="F9DC" %}mixi日記 検索結果に含まれない場合はﾌﾟﾚｾﾞﾝﾄ対象外となりますのでご注意ください<br />
			</div><!--/.inner-->
		</div><!--/.section-->
		<div class="section">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#ff9999;color:#ffffff;">
				{% emoji code="F8EA" %}キャンペーン期間<br />
			</div><!--/.headline-->
			<div class="inner">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#cc0000;">2/9（火）24:00までの期間限定!</span><br />
				※お1人様1000Tまで付与!<br />
			</div><!--/.inner-->
		</div><!--/.section-->
		<div class="section">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#ff9999;color:#ffffff;">
				{% emoji code="F8F5" %}プレゼント付与予定<br />
			</div><!--/.headline-->
			<div class="inner">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#cc0000;">付与いたしました</span><br />
			</div><!--/.inner-->
		</div><!--/.section-->
		<br />
		<br />
	    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#ff9999;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#news-->

{%include file="common/menu.phtml"%}
