<div id="news">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/news.gif?100205" width="240" height="60" /><br />
		</div><!--/#headline-->
		<div class="inner">
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年2月9日(火)]<br />
				ﾌﾟﾚｾﾞﾝﾄ付与について</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				日頃より当ｱﾌﾟﾘをご利用いただきありがとうございます｡<br />
				<br />現在行なっております日記ｷｬﾝﾍﾟｰﾝ並びにﾏｲﾐｸ招待､ﾏｲﾐｸ招待ｷｬﾝﾍﾟｰﾝのﾌﾟﾚｾﾞﾝﾄ付与予定日に関しまして複数のお問い合わせが届いておりますので､再度お知らせいたします｡<br />
				<br />
				◆ﾌﾟﾚｾﾞﾝﾄ付与予定日<br />
				◯日記ｷｬﾝﾍﾟｰﾝ<br />
				→2月12日(金)<br />
				<br />
				◯ﾏｲﾐｸ招待<br />
				→招待ﾏｲﾐｸのﾚｽﾄﾗﾝ開店後2-3日後<br />
				&nbsp;※ｱﾌﾟﾘ登録後､ﾚｽﾄﾗﾝ開店までｹﾞｰﾑを進める必要があります｡<br />
				<br />
				◯ﾏｲﾐｸ招待ｷｬﾝﾍﾟｰﾝ<br />
				→3月上旬頃<br />
				<br />
				ﾌﾟﾚｾﾞﾝﾄ付与予定日について不明な点をお持ちの場合は､上記をご確認いただきますようお願いいたします｡<br />
				<br/>
				今後とも｢ようこそﾏｲｷｯﾁﾝ｣をよろしくお願いいたします｡<br />
				<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="caution">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9DC" %}ｻｰﾋﾞｽに関する不明点・疑問を感じた場合は､「<a href='{% "$baseUrl/mobile/kitchenstatic/qa"|mixiurl %}'>よくある質問</a>」をご覧ください｡<br />
			</div><!--/.caution-->
        </div><!--/.inner-->
	    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#news-->
{%include file="common/menu.phtml"%}
