<div id="news">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/news.gif?100205" width="240" height="60" /><br />
		</div><!--/#headline-->
		<div class="inner">
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年2月12日(金)]<br />
				サーバー増強のお知らせ</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				日頃より当ｱﾌﾟﾘをご利用いただきありがとうございます｡<br />
				<br />
				昨日の夜間より本日17:00までｻｰﾊﾞｰ不具合によるｱｸｾｽ障害が発生し､ご利用の皆様には多大なご迷惑をおかけしてことをお詫び申し上げます｡<br />
				<br />
				先程この件に対応してｻｰﾊﾞｰの増強を行ないました｡<br />
				<br />
				現在ではｱｸｾｽ障害が発生する頻度はかなり低くなっているかと思います｡<br />
				<br />
				未熟なｻｰﾋﾞｽではございますが､今後ともﾕｰｻﾞｰの皆様にご満足頂けるｻｰﾋﾞｽになるよう努力してまいりますので､引き続き｢ようこそﾏｲｷｯﾁﾝ｣をよろしくお願いいたします｡<br />
				<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="caution">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9DC" %}ｻｰﾋﾞｽに関する不明点・疑問を感じた場合は､「<a href='{% "$baseUrl/mobile/kitchenstatic/qa"|mixiurl %}'>よくある質問</a>」をご覧ください｡<br />
			</div><!--/.caution-->
        </div><!--/.inner-->
	    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#news-->
{%include file="common/menu.phtml"%}
