<div id="news">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/news.gif?100205" width="240" height="60" /><br />
		</div><!--/#headline-->
		<div class="inner">
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年2月11日(木)]<br />
				ｱｸｾｽ障害のお詫び</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				日頃より当ｱﾌﾟﾘをご利用いただきありがとうございます｡<br />
				<br />
				昨日の11:00から20:00までｻｰﾊﾞｰ不具合によるｱｸｾｽ障害が発生し、ご利用の皆さまには多大なるご迷惑をおかけしたことをお詫び申し上げます。<br />
				<br />
				また現状に関しても、対応を急いでいる状況ではありますが、まだ始まったばかりの未熟なｻｰﾋﾞｽゆえ、皆さまにはご不便おかけすることがあるかもしれません。<br />
				<br />
				ｻｰﾋﾞｽに関するご意見はお問い合わせにて随時承っておりますので、今後のｻｰﾋﾞｽ改善のためにも何かお気づきになった場合は、ぜひとも正直なご意見をいただけたらと思います。<br />
				<br />
				皆さまのｻｰﾋﾞｽに対するご意見を真摯に受け止め、皆さまに愛されるｻｰﾋﾞｽが提供できるよう、今後のｻｰﾋﾞｽ改善に取り組んでまいります。<br />
				<br />
				今後とも｢ようこそﾏｲｷｯﾁﾝ｣をよろしくお願いいたします｡<br />
				<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="caution">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9DC" %}ｻｰﾋﾞｽに関する不明点・疑問を感じた場合は､「<a href='{% "$baseUrl/mobile/kitchenstatic/qa"|mixiurl %}'>よくある質問</a>」をご覧ください｡<br />
			</div><!--/.caution-->
        </div><!--/.inner-->
	    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#news-->
{%include file="common/menu.phtml"%}
