<div id="news">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/news.gif?100205" width="240" height="60" /><br />
		</div><!--/#headline-->
		<div class="inner">
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年2月22日(月)]<br />
				アクセス障害のお詫び</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				日頃より当ｱﾌﾟﾘをご利用いただきありがとうございます｡<br />
				<br />
				2月21日19:00から2月22日17:00までｻｰﾊﾞｰ不具合によるｱｸｾｽ障害が発生し､ご利用の皆さまには多大なるご迷惑をおかけしましたことをお詫び申し上げます｡<br />
				<br />
				現在は主な障害の原因については対応が完了しておりますので､ｴﾗｰが頻発する状況からは脱しておりますが､まだ不具合は完全には取りきっておりません｡<br />
				<br />
				そのため､まれにではありますが依然としてｴﾗｰが表示される状態となっております｡こちらの不具合についても引き続き原因究明と修正対応を行なっております｡<br />
				<br />
				先日より度重なるｱｸｾｽ障害を出してしまっていることについては弊社のｻｰﾋﾞｽ運営の未熟さに因るものであり､お客様に対しては言い訳のしようもございません｡心底､お詫び申し上げる次第です｡<br />
				<br />
				弊社が現在出来ることは改めて再発防止の対策を検討し､今後このようなことの無いように準備をしていくことだと思っております。<br />
				<br />
				またｱｸｾｽ不具合が解消され次第､わずかばかりではございますが､ご利用者の皆さまに今回の補償対応を近日中に行うことを予定しております｡これでお許しいただけるとは考えておりませんが､心ばかりのお詫びとしてﾁｯﾌﾟ/ﾒﾀﾞﾙを付与させていただきます｡<br />
				<br />
				補償対応につきましては､後日改めて皆さまにはご報告いたします｡<br />
				<br />
				今後もより一層皆さまからのご意見を真摯に受け止め､愛されるｻｰﾋﾞｽが安定的に提供できるようｻｰﾋﾞｽ改善に取り組んでまいります｡<br />
				<br />
				未熟なｻｰﾋﾞｽではございますが､何卒今後とも｢ようこそマイキッチン｣をよろしくおねがいいたします｡<br />
				<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="caution">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9DC" %}ｻｰﾋﾞｽに関する不明点・疑問を感じた場合は､「<a href='{% "$baseUrl/mobile/kitchenstatic/qa"|mixiurl %}'>よくある質問</a>」をご覧ください｡<br />
			</div><!--/.caution-->
        </div><!--/.inner-->
	    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#news-->
{%include file="common/menu.phtml"%}
