<div id="news">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/news.gif?100205" width="240" height="60" /><br />
		</div><!--/#headline-->
		<div class="inner">
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年3月24日(水)]<br />
				ｷｯﾁﾝ画面のｴﾗｰについて</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				日頃より当ｱﾌﾟﾘをご利用いただきありがとうございます｡<br />
				<br />
				3/23にﾘﾆｭｰｱﾙしましたｷｯﾁﾝ画面ですが､docomoの一部端末でﾃﾞｰﾀの読み込みができない状況になっております｡<br />
				<br />
				現在､こちらの件については対応を急いでおりますのでｴﾗｰとなっているお客様には大変申し訳ございませんがしばらくお待ちいただけますようお願いいたします｡<br />
				<br />
				また､読み込みがｴﾗｰとなる場合は通信の失敗の可能性もございますので､その時は通信中画面の時に決定ｷｰを数回押していただくことで改善する場合もございます｡<br />
				<br />
				お客さまにはご迷惑をおかけしまして大変申し訳ございません｡<br />
				<br />
				今後とも｢ようこそマイキッチン｣をよろしくお願いいたします｡<br />
				<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="caution">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9DC" %}ｻｰﾋﾞｽに関する不明点・疑問を感じた場合は､「<a href='{% "$baseUrl/mobile/kitchenstatic/qa"|mixiurl %}'>よくある質問</a>」をご覧ください｡<br />
			</div><!--/.caution-->
        </div><!--/.inner-->
	    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#news-->
{%include file="common/menu.phtml"%}