<div id="news">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/news.gif?100205" width="240" height="60" /><br />
		</div><!--/#headline-->
		<div class="inner">
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年3月8日(月)]<br />
				通貨名称変更のご報告</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				日頃より当ｱﾌﾟﾘをご利用いただきありがとうございます｡<br />
				<br />
				先日mixiｱﾌﾟﾘのｶﾞｲﾄﾞﾗｲﾝの変更により｢ﾎﾟｲﾝﾄ｣という表記が使用できなくなったため､本日より通貨名称を変更いたします｡<br />
				<br />
				突然の変更となり皆さまにはご迷惑をおかけいたしますが何卒ご了承ください｡<br />
				<br />
				■変更内容<br />
				{% emoji code="F8CD" %}ﾎﾟｲﾝﾄ(P)<br />
				→{% emoji code="F8E5" %}ﾁｯﾌﾟ(T)<br />
				<br />
				{% emoji code="F9BA" %}ｺﾞｰﾙﾄﾞ(G)<br />
				→{% emoji code="F8C8" %}ﾒﾀﾞﾙ(M)<br />
				<br />
				ご不便をおかけしまして申し訳ございません｡<br />
				<br />
				今後とも｢ようこそマイキッチン｣をよろしくお願いいたします｡<br />
				<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="caution">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9DC" %}ｻｰﾋﾞｽに関する不明点・疑問を感じた場合は､「<a href='{% "$baseUrl/mobile/kitchenstatic/qa"|mixiurl %}'>よくある質問</a>」をご覧ください｡<br />
			</div><!--/.caution-->
        </div><!--/.inner-->
	    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#news-->
{%include file="common/menu.phtml"%}
