<div id="news">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/news.gif?100205" width="240" height="60" /><br />
		</div><!--/#headline-->
		<div class="inner">
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年3月25日(金)]<br />
				ｷｯﾁﾝ画面の巻戻しについて</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				日頃より当ｱﾌﾟﾘをご利用いただきありがとうございます｡<br />
				<br />
				3/23にﾘﾆｭｰｱﾙしましたｷｯﾁﾝ画面ですが､docomoの一部端末でﾃﾞｰﾀの読み込みができない状況になっております｡<br />
				<br />
				こちらの件については､原因の調査と対応を急いでおりましたが､すぐに対応することが困難な状況であるため､ｷｯﾁﾝ画面を以前のﾊﾞｰｼﾞｮﾝに戻しました｡<br />
				<br />
				弊社の不手際によりｻｰﾋﾞｽをご利用いただけなかった方､また新しいｷｯﾁﾝ画面をご利用いただいていた方には多大なるご迷惑をおかけしまして申し訳ございません｡<br />
				<br />
				今後ｷｯﾁﾝ画面につきましては､今回の原因調査と対応を進め､皆さまにきちんとご利用いただけることを確認した上で再度変更を行なう予定でございます｡<br />
				<br />
				お客様にはご迷惑をおかけしまして大変申し訳ございません｡<br />
				重ねてお詫び申し上げます｡<br />
				<br />
				今後とも｢ようこそマイキッチン｣をよろしくお願いいたします｡<br />
				<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="caution">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9DC" %}ｻｰﾋﾞｽに関する不明点・疑問を感じた場合は､「<a href='{% "$baseUrl/mobile/kitchenstatic/qa"|mixiurl %}'>よくある質問</a>」をご覧ください｡<br />
			</div><!--/.caution-->
        </div><!--/.inner-->
	    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#news-->
{%include file="common/menu.phtml"%}