<div id="news">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/news.gif?100205" width="240" height="60" /><br />
		</div><!--/#headline-->
		<div class="inner">
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年3月23日(火)]<br />
				ｷｯﾁﾝ画面ﾘﾆｭｰｱﾙのお知らせ</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				日頃より当ｱﾌﾟﾘをご利用いただきありがとうございます｡<br />
				<br />
				本日よりｷｯﾁﾝ画面をﾘﾆｭｰｱﾙしました｡<br />
				<br />
				皆さまからいただいた要望を元に以下の修正点を加えております｡<br />
				<br />
				・1画面で全ての調理台を表示<br />
				・調理台の移動時間を短縮<br />
				・ﾊｴや味付けなどでの画面切り替えが不要<br />
				・ﾏｲﾐｸ調理していない場合でも｢ﾅﾃﾞﾅﾃﾞ｣が可能に<br />
				<br />
				追加機能の｢ﾅﾃﾞﾅﾃﾞ｣以外の流れは今までと変わりません｡<br />
				<br />
				新しくなったｷｯﾁﾝ画面を是非ともご利用ください｡<br />
				<br />
				今後とも｢ようこそマイキッチン｣をよろしくお願いいたします｡<br />
				<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="caution">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9DC" %}ｻｰﾋﾞｽに関する不明点・疑問を感じた場合は､「<a href='{% "$baseUrl/mobile/kitchenstatic/qa"|mixiurl %}'>よくある質問</a>」をご覧ください｡<br />
			</div><!--/.caution-->
        </div><!--/.inner-->
	    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#news-->
{%include file="common/menu.phtml"%}