<div id="news">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/news.gif?100205" width="240" height="60" /><br />
		</div><!--/#headline-->
		<div class="inner">
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年3月4日(木)]<br />
				ざっか配置不具合修正のご報告</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				日頃より当ｱﾌﾟﾘをご利用いただきありがとうございます｡<br />
				<br />
				本日､ﾘｽﾄﾗﾝﾃに料理ｼﾞｬﾝﾙを変更後､一部の雑貨をﾏｲﾚｽﾄﾗﾝに設置する時に｢不正なｱｸｼｮﾝ｣を表示される不具合につきまして先程修正を行いました｡<br />
				<br />
				その他細かい修正や調整を行なっておりますので､以前よりも使いやすくなっているかと思います｡<br />
				<br />
				皆さまには今回の不具合で今までご迷惑をおかけしまして大変申し訳ございませんでした｡<br />
				<br />
				今後の追加内容に関するﾘｸｴｽﾄは公式ｺﾐｭﾆﾃｨまでお願いします｡<br />
				<br />
				今後とも｢ようこそマイキッチン｣をよろしくおねがいいたします｡<br />
				<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="caution">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9DC" %}ｻｰﾋﾞｽに関する不明点・疑問を感じた場合は､「<a href='{% "$baseUrl/mobile/kitchenstatic/qa"|mixiurl %}'>よくある質問</a>」をご覧ください｡<br />
			</div><!--/.caution-->
        </div><!--/.inner-->
	    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#news-->
{%include file="common/menu.phtml"%}
