<div id="news">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/news.gif?100205" width="240" height="60" /><br />
		</div><!--/#headline-->
		<div class="inner">
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年3月30日(火)]<br />
				ｽﾊﾟｲｽの効果について</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				日頃より当ｱﾌﾟﾘをご利用いただきありがとうございます｡<br />
				<br />
				3/23にﾘﾆｭｰｱﾙしたｷｯﾁﾝ画面において数多くお問い合わせを頂いた｢ｽﾊﾟｲｽを使用しても生産量が増えない｣件に関しまして､<br />
				ｽﾊﾟｲｽの効果については､現状では生産量には影響せず､調理完了後の獲得ﾁｯﾌﾟが増加する仕様になっております｡<br />
				<br />
				そのため､生産量が100%に達した料理についてもｽﾊﾟｲｽを使用することで獲得ﾁｯﾌﾟを増やすことができます｡<br />
				<br />
				また現在のflashではｽﾊﾟｲｽを使用すると生産量のｸﾞﾗﾌが増えますが､こちらは不具合となっており今後修正を行う予定です｡<br />
				<br />
				お客様には誤解を与える表現となり大変申し訳ございませんでした｡<br />
				現在の表示不具合についても早急に対応をしてまいります｡<br />
				<br />
				今後とも｢ようこそマイキッチン｣をよろしくお願いいたします｡<br />
				<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="caution">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9DC" %}ｻｰﾋﾞｽに関する不明点・疑問を感じた場合は､「<a href='{% "$baseUrl/mobile/kitchenstatic/qa"|mixiurl %}'>よくある質問</a>」をご覧ください｡<br />
			</div><!--/.caution-->
        </div><!--/.inner-->
	    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#news-->
{%include file="common/menu.phtml"%}