<div id="news">
	<div class="content" style="background:#fff5f5;">
		<div class="headline" style="background:#ff9999;color:#ffffff;text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			マイミク招待キャンペーン第2弾!<br />
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
		</div><!--/#headline-->
		<div class="banner" style="color:#cc0000;text-align:center;">
			このｷｬﾝﾍﾟｰﾝは終了しました｡<br />
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/campaign/100206.gif?100206" width="192" height="53" style="margin-top:3px;" /><br />
			抽選で総額30000Mﾌﾟﾚｾﾞﾝﾄ!<br />1等:1000M(10名)/2等:500M(20名)<br />
		</div><!--/.banner-->
		<div class="section">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#ff9999;color:#ffffff;">
				{% emoji code="F8E6" %}景品<br />
			</div><!--/.headline-->
			<div class="inner">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9BF" %}1等:1000M(10名様)<br />
				{% emoji code="F9BF" %}2等: 500M(20名様)<br />
				{% emoji code="F9BF" %}3等: 100M(100名様)<br />
				抽選で130名様にﾌﾟﾚｾﾞﾝﾄ!<br />
			</div><!--/.inner-->
		</div><!--/.section-->
		<div class="section">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#ff9999;color:#ffffff;">
				{% emoji code="F991" %}プレゼント対象<br />
			</div><!--/.headline-->
			<div class="inner">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#cc0000;">ﾏｲﾐｸを3名以上招待</span>した方から抽選で130名<br />
				{% emoji code="F9DC" %}招待したﾏｲﾐｸが当ｱﾌﾟﾘを始める必要があります<br />
			</div><!--/.inner-->
		</div><!--/.section-->
		<div class="section">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#ff9999;color:#ffffff;">
				{% emoji code="F8EA" %}キャンペーン期間<br />
			</div><!--/.headline-->
			<div class="inner">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#cc0000;">3/31(水)24:00までの期間限定!</span><br />
			</div><!--/.inner-->
		</div><!--/.section-->
		<div class="section">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#ff9999;color:#ffffff;">
				{% emoji code="F9E6" %}抽選方法<br />
			</div><!--/.headline-->
			<div class="inner">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9BB" %}ｺﾝﾋﾟｭｰﾀによるﾗﾝﾀﾞﾑとなります<br />
				<span style="color:#f16dc0;">招</span><span style="color:#f16dc0;">待</span><span style="color:#ee5564;">人</span><span style="color:#dc4646;">数</span><span style="color:#ec884e;">に</span><span style="color:#ff952e;">応</span><span style="color:#e7b300;">じ</span><span style="color:#eecf02;">て<span style="color:#72c156;">当</span><span style="color:#4fa445;">選</span><span style="color:#62badc;">確</span><span style="color:#1f83cf;">率</span><span style="color:#1854bc;">U</span><span style="color:#0c0c9c;">P</span>{% emoji code="F99A" %}<br />
			</div><!--/.inner-->
		</div><!--/.section-->
		<div class="section">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#ff9999;color:#ffffff;">
				{% emoji code="F8F5" %}プレゼント付与予定<br />
			</div><!--/.headline-->
			<div class="inner">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#cc0000;">4月上旬頃を予定</span><br />
				※当選は付与をもって代えさせていただきます<br />
				※付与された旨は通知されませんので予めご了承ください<br />
			</div><!--/.inner-->
		</div><!--/.section-->
		<div class="toDiary" style="text-align:center;">
			<br />
			<span style="color:#cc0000;">3名以上招待するだけ!<br />
			ﾏｲﾐｸを誘ってみんなで遊ぼう!<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<form method="post" action='{% "invite:friends?callback=$baseUrl/mobile/callback/invite?forward=$baseUrl/mobile/kitchen/invitefinish" %}'>
				<div class="btn" style="text-align:center;">
					<input type="submit" value="  マイミクを招待する  " /><br />
				</div><!--/.btn-->
			</form>
		</div><!--/.toDiary-->
		<br />
		<br />
	    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#ff9999;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#news-->

{%include file="common/browseback.phtml"%}
