<div id="news">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/news.gif?100205" width="240" height="60" /><br />
		</div><!--/#headline-->
		<div class="inner">
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年4月27日(火)]<br />
				マイキッチン公開設定について</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				日頃より当ｱﾌﾟﾘをご利用いただきありがとうございます｡<br />
				<br />
				何度かお客様からお問い合わせ頂いております｢ﾏｲｷｯﾁﾝの公開設定｣についてご案内いたします｡<br />
				<br />
				4/15よりMyﾚｽﾄﾗﾝ画面のﾘﾆｭｰｱﾙの際に｢ﾏｲｷｯﾁﾝの公開設定｣ﾘﾝｸを削除いたしました｡<br />
				<br />
				こちらはmixiｱﾌﾟﾘのｶﾞｲﾄﾞﾗｲﾝ変更のため､ﾏｲﾐｸ同士で楽しむ方向を強化するための施策として実施しております｡<br />
				<br />
				そのため､ﾏｲｷｯﾁﾝの公開設定については設定ができませんのでご注意ください｡<br />
				<br />
				本来であればﾘﾆｭｰｱﾙの際にお伝えすべきでしたが､ご報告が遅れてしまい大変申し訳ございませんでした｡<br />
				<br />
				今後とも｢ようこそマイキッチン｣をよろしくお願いいたします｡<br />
				<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="caution">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9DC" %}ｻｰﾋﾞｽに関する不明点・疑問を感じた場合は､「<a href='{% "$baseUrl/mobile/kitchenstatic/qa"|mixiurl %}'>よくある質問</a>」をご覧ください｡<br />
			</div><!--/.caution-->
        </div><!--/.inner-->
	    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#news-->
{%include file="common/menu.phtml"%}