<div id="news">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/news.gif?100205" width="240" height="60" /><br />
		</div><!--/#headline-->
		<div class="inner">
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年4月14日(水)]<br />
				招待ｷｬﾝﾍﾟｰﾝのﾒﾀﾞﾙ付与</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				日頃より当ｱﾌﾟﾘをご利用いただきありがとうございます｡<br />
				<br />
				本日､3/31まで実施した招待ｷｬﾝﾍﾟｰﾝの抽選を行い､ご当選された130名の方に景品であるﾒﾀﾞﾙを付与いたしました｡<br />
				付与が予定よりも遅れてしまい申し訳ございませんでした｡<br />
				<br />
				規定通り付与された旨は通知されておりませんのでご注意ください｡<br />
				<br />
				今後とも｢ようこそマイキッチン｣をよろしくお願いいたします｡<br />
				<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="caution">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9DC" %}ｻｰﾋﾞｽに関する不明点・疑問を感じた場合は､「<a href='{% "$baseUrl/mobile/kitchenstatic/qa"|mixiurl %}'>よくある質問</a>」をご覧ください｡<br />
			</div><!--/.caution-->
        </div><!--/.inner-->
	    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#news-->
{%include file="common/menu.phtml"%}
