<div id="news">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/news.gif?100205" width="240" height="60" /><br />
		</div><!--/#headline-->
		<div class="inner">
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年4月15日(水)]<br />
				ﾚｽﾄﾗﾝ画面ﾘﾆｭｰｱﾙのお知らせ</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				日頃より当ｱﾌﾟﾘをご利用いただきありがとうございます｡<br />
				<br />
				本日ﾚｽﾄﾗﾝ画面のﾘﾆｭｰｱﾙを行ないました｡<br />
				<br />
				皆さまから頂いた要望を元に以下の主な修正点を加えております｡<br />
				<br />
				◯Myﾚｽﾄﾗﾝ<br />
				・調理中のﾚｽﾄﾗﾝ(ﾏｲﾐｸ)を表示<br />
				・カキコミ機能を追加<br />
				<br />
				◯ﾏｲﾐｸﾚｽﾄﾗﾝ<br />
				・ナデナデ機能を追加<br />
				・ｷｯﾁﾝ画面を無くし､ﾚｽﾄﾗﾝ画面にｷｯﾁﾝ情報を表示<br />
				・カキコミ機能を追加<br />
				<br />
				<br />
				追加機能以外の今までの機能は､デザインは変更しておりますが今までと変わりません｡<br />
				<br />
				新しくなったﾚｽﾄﾗﾝ画面をご利用ください｡<br />
				<br />
				今後とも｢ようこそマイキッチン｣をよろしくお願いいたします｡<br />
				<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="caution">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9DC" %}ｻｰﾋﾞｽに関する不明点・疑問を感じた場合は､「<a href='{% "$baseUrl/mobile/kitchenstatic/qa"|mixiurl %}'>よくある質問</a>」をご覧ください｡<br />
			</div><!--/.caution-->
        </div><!--/.inner-->
	    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#news-->
{%include file="common/menu.phtml"%}