<div id="news">
	<div class="content" style="background:#fff5f5;text-align:center;">
		<div class="headline" style="background:#f34cc3;color:#ffffff;text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			強力ｱｲﾃﾑ6種類追加!<br />
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
		</div><!--/#headline-->
		<div class="banner" style="text-align:center;">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/campaign/100401_item.gif?" width="230" height="80" style="margin-top:3px;" /><br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div style="text-align:left;">ｹﾞｰﾑを有利に進められる強力ｱｲﾃﾑが6種類追加されました!<br />
			ｱｲﾃﾑを使って効率的に一流ｼｪﾌの道を目指そう!</div>
		</div><!--/.banner-->
		<div class="section">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#f34cc3;color:#ffffff;">
				{% emoji code="F8E6" %}今回追加のアイテム<br />
			</div><!--/.headline-->
			<div class="inner">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="section">
					<table width="100%" cellpadding="0" cellspacing="0" border="0">
						<tr>
							<td style="width:64px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/yorozu/40x40/20.gif?" style="margin:3px 0;" /></td>
							<td><div style="font-size:x-small;"><a href='{% "$baseUrl/mobile/kitchenshop/itemconfirm?item_id=20&pay=gold"|mixiurl %}'>銀のスプーン</a><br />
							銀の力で特殊なﾚｼﾋﾟ以外は確実に味見に成功!</div></td>
						</tr>
					</table>
				</div><!--/.section-->
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#f34cc3;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />

				<div class="section">
					<table width="100%" cellpadding="0" cellspacing="0" border="0">
						<tr>
							<td style="width:64px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/yorozu/40x40/16.gif?" alt="" style="margin:3px 0;" /></td>
							<td><div style="font-size:x-small;"><a href='{% "$baseUrl/mobile/kitchenshop/itemconfirm?item_id=16&pay=gold"|mixiurl %}'>モダン洋食辞典</a><br />
							伝説の料理人が、洋食のﾚｼﾋﾟを記した辞典。使うとﾗﾝﾀﾞﾑで洋食ﾚｼﾋﾟを習得!</div></td>
						</tr>
					</table>
				</div><!--/.section-->
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#f34cc3;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
				
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />

				<div class="section">
					<table width="100%" cellpadding="0" cellspacing="0" border="0">
						<tr>
							<td style="width:64px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/yorozu/40x40/17.gif?" style="margin:3px 0;" /></td>
							<td><div style="font-size:x-small;"><a href='{% "$baseUrl/mobile/kitchenshop/itemconfirm?item_id=17&pay=gold"|mixiurl %}'>西洋美食辞典</a><br />
							伝説の料理人が、ﾘｽﾄﾗﾝﾃのﾚｼﾋﾟを記した辞典。使うとﾗﾝﾀﾞﾑでﾘｽﾄﾗﾝﾃﾚｼﾋﾟを習得!</div></td>
						</tr>
					</table>
				</div><!--/.section-->
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#f34cc3;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
				
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />

				<div class="section">
					<table width="100%" cellpadding="0" cellspacing="0" border="0">
						<tr>
							<td style="width:64px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/yorozu/40x40/12.gif?" style="margin:3px 0;" /></td>
							<td><div style="font-size:x-small;"><a href='{% "$baseUrl/mobile/kitchenshop/itemconfirm?item_id=12&pay=gold"|mixiurl %}'>伝説の職人</a><br />
							伝説の料理人が料理のお手伝い.一瞬で調理が完了!</div></td>
						</tr>
					</table>
				</div><!--/.section-->
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#f34cc3;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>				

				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="section">
					<table width="100%" cellpadding="0" cellspacing="0" border="0">
						<tr>
							<td style="width:64px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/yorozu/40x40/06.gif?" style="margin:3px 0;" /></td>
							<td><div style="font-size:x-small;"><a href='{% "$baseUrl/mobile/kitchenshop/itemconfirm?item_id=06&pay=gold"|mixiurl %}'>最後のスパイス</a><br />
							伝説の料理人が残した最後のｽﾊﾟｲｽ。料理のﾁｯﾌﾟ(T)が最大にｱｯﾌﾟ!</div></td>
						</tr>
					</table>
				</div><!--/.section-->
				<div class="toyorozu" style="text-align:center;">
					<br />
					<span style="color:#cc0000;">↓↓↓↓↓↓↓↓</span><br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<table width="220" cellpadding="3" cellspacing="1" border="0" align="center" style="background:#ff9999;">
						<tr>
							<td style="background:#ffffdd;text-align:center;"><div style="{% if $ua==1 %}font-size:x-small;{%/if%}">
								<span style="color:#cc0000;">強力ｱｲﾃﾑの購入は<br />こちらから！</span><br />
								<span style="color:#cc0000;">≫</span><a href='{% "$baseUrl/mobile/kitchenshop/itemlist"|mixiurl %}'>よろず屋へ</a><span style="color:#cc0000;">≪</span><br />
								</div></td>
						</tr>
					</table>
					<br />
				</div><!--/.toyorozu-->
			</div><!--/.inner-->
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#ff9999;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>							
	</div><!--/.content-->
</div><!--/#news-->

{%include file="common/browseback.phtml"%}
