<div id="news">
	<div class="content" style="background:#f0f5e0;">
		<div class="headline" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/news.gif?100205" width="240" height="60" /><br />
		</div><!--/#headline-->
		<div class="inner">
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年6月1日(火)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenshop/gachainfo?gacha_id=7"|mixiurl %}'>新しいガチャの追加</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年5月27日(木)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100527_update"|mixiurl %}'>ｱｯﾌﾟﾃﾞｰﾄのお知らせ</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年5月10日(水)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100510"|mixiurl %}'>データ不具合についてのご報告</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年4月29日(水)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenshop/gachainfo?gacha_id=6"|mixiurl %}'>新しいガチャの追加</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100429_invite_campaign"|mixiurl %}'>友達招待ｷｬﾝﾍﾟｰﾝの開始</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100429_diary_campaign"|mixiurl %}'>日記ｷｬﾝﾍﾟｰﾝの開始</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年4月28日(水)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100428"|mixiurl %}'>｢注文する機能｣の追加</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年4月27日(木)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100427"|mixiurl %}'>マイキッチン公開設定について</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年4月22日(木)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100422"|mixiurl %}'>｢ご近所さんのうごき｣を追加</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年4月20日(火)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenshop/gachainfo?gacha_id=5"|mixiurl %}'>新しいガチャの追加</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年4月19日(月)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100419_campaign_elect"|mixiurl %}'>招待ｷｬﾝﾍﾟｰﾝの景品付与</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年4月15日(木)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100415"|mixiurl %}'>ﾚｽﾄﾗﾝ画面ﾘﾆｭｰｱﾙのお知らせ</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年4月14日(水)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100414_update"|mixiurl %}'>ｱｯﾌﾟﾃﾞｰﾄのお知らせ</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100414_campaign_elect"|mixiurl %}'>招待ｷｬﾝﾍﾟｰﾝのﾒﾀﾞﾙ付与</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年4月6日(木)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100406"|mixiurl %}'>ｽﾊﾟｲｽ効果のお詫び</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年4月1日(木)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100401_invitecampaign"|mixiurl %}'>友達招待ｷｬﾝﾍﾟｰﾝ開始</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenshop/gachainfo?gacha_id=4"|mixiurl %}'>新しいガチャの追加</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100401_item"|mixiurl %}'>ｱｲﾃﾑ追加のお知らせ</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年3月30日(火)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100330_update"|mixiurl %}'>ｱｯﾌﾟﾃﾞｰﾄのお知らせ</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100330_schedule"|mixiurl %}'>新規料理ｼﾞｬﾝﾙの延期</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100330"|mixiurl %}'>ｽﾊﾟｲｽの効果について</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年3月26日(金)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100324_campaign"|mixiurl %}'>日記ｷｬﾝﾍﾟｰﾝ開始</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100325_kitchenflash"|mixiurl %}'>ｷｯﾁﾝ画面の巻戻しについて</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年3月25日(木)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100325"|mixiurl %}'>ｱｸｾｽ障害について</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年3月24日(水)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100324"|mixiurl %}'>ｷｯﾁﾝ画面のｴﾗｰについて</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年3月23日(火)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100323_kitchenflash"|mixiurl %}'>ｷｯﾁﾝ画面ﾘﾆｭｰｱﾙのお知らせ</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100323"|mixiurl %}'>ｱｯﾌﾟﾃﾞｰﾄのお知らせ</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年3月18日(月)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100318_campaign"|mixiurl %}'>友達招待ｷｬﾝﾍﾟｰﾝ開始</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100318_campaign_elect"|mixiurl %}'>招待ｷｬﾝﾍﾟｰﾝのﾒﾀﾞﾙ付与</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100318"|mixiurl %}'>ﾏｲｷﾁ銀行の開始</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年3月8日(月)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100308"|mixiurl %}'>通貨名称変更のご報告</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100206_campaign"|mixiurl %}'>招待ｷｬﾝﾍﾟｰﾝ終了</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年3月4日(水)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100304_point"|mixiurl %}'>日記ｷｬﾝﾍﾟｰﾝのﾁｯﾌﾟ付与</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100304_bugfix"|mixiurl %}'>ざっか配置不具合修正のご報告</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年3月2日(火)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100302"|mixiurl %}'>ｱｯﾌﾟﾃﾞｰﾄのお知らせ</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年3月1日(月)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100210_campaign"|mixiurl %}'>日記投稿ｷｬﾝﾍﾟｰﾝ終了</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100301_bugfix"|mixiurl %}'>ﾚｼﾋﾟ開発不具合修正のご報告</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年2月26日(金)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100226"|mixiurl %}'>新ﾚｼﾋﾟ追加のご案内</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年2月25日(木)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100225"|mixiurl %}'>ｱｯﾌﾟﾃﾞｰﾄのお知らせ</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年2月24日(水)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100224"|mixiurl %}'>ﾏｲﾐｸ招待ｷｬﾝﾍﾟｰﾝ延長のご案内</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年2月23日(火)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100223"|mixiurl %}'>200M進呈のご報告</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年2月22日(月)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100222"|mixiurl %}'>ｱｸｾｽ障害のお詫び</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年2月19日(金)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100219"|mixiurl %}'>新ｼﾞｬﾝﾙ追加予定のご案内</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->	
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年2月15日(月)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100215"|mixiurl %}'>ｱｸｾｽ負荷対応について</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年2月12日(金)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100212"|mixiurl %}'>ｻｰﾊﾞｰ増強のお知らせ</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年2月11日(木)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100211_error"|mixiurl %}'>ｱｸｾｽ障害のお詫び</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100211_editAccess"|mixiurl %}'>公開設定機能の変更</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100211_recipe"|mixiurl %}'>新ﾚｼﾋﾟ追加のご案内</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100210_campaign"|mixiurl %}'>紹介日記500T[第2弾]ｽﾀｰﾄ!</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100211_point"|mixiurl %}'>日記ｷｬﾝﾍﾟｰﾝのﾁｯﾌﾟ付与</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年2月9日(火)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100209_editAccess"|mixiurl %}'>公開設定機能を追加</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100209"|mixiurl %}'>ﾌﾟﾚｾﾞﾝﾄ付与について</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100209_bugfix"|mixiurl %}'>ﾚｼﾋﾟ開発時の不具合について</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100205_campaign"|mixiurl %}'>日記投稿ｷｬﾝﾍﾟｰﾝ終了</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年2月8日(月)]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100207"|mixiurl %}'>新規入会再開のお知らせ</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#497d40;">[2010年2月5日(金)]</span><br />
				&nbsp;β版ｻｰﾋﾞｽ提供開始しました<br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100205_campaign"|mixiurl %}'>日記投稿ｷｬﾝﾍﾟｰﾝ開始</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/info?CF_info=100206_campaign"|mixiurl %}'>友達招待ｷｬﾝﾍﾟｰﾝ開始</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="caution">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9DC" %}ｻｰﾋﾞｽに関する不明点・疑問を感じた場合は､「<a href='{% "$baseUrl/mobile/kitchenstatic/qa"|mixiurl %}'>よくある質問</a>」をご覧ください｡<br />
			</div><!--/.caution-->
        </div><!--/.inner-->
	    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#news-->
{%include file="common/menu.phtml"%}
