<div id="help">
    <div class="content" style="background:#f0f5e0;">
        <div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
            <img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/help.gif" width="230" height="60" /><br />
            <img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
            {% emoji code="F99F" %}ｼｪﾌの設定ができない場合<br />
        </div><!--/.headline-->
        <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
        <div class="inner">
			当ｱﾌﾟﾘではﾒｲﾝ操作画面となる[ｼｪﾌ設定][ｷｯﾁﾝ][ﾚｼﾋﾟ開発]がFLASHによる表示形式となっております｡<br />
			<br />
			一部の最新端末でﾎﾟｲﾝﾀを利用した操作がありますが､当ｱﾌﾟﾘではﾎﾟｲﾝﾀを利用した操作には対応しておりません｡<br />
			<br />
			<div style="text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/help/pointer.gif" width="180" height="180" /></div>
			<br />
			もし当ｱﾌﾟﾘでのFLASH画面で操作ができない場合は､<span style="color:#cc0000;">お使いの携帯電話の設定を変更してください｡</span><br />
			<br />
			たいへんお手数をおかけし申し訳ありませんが､何卒よろしくお願い申し上げます｡<br />
			<br />
        </div><!--/.inner-->
        <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
        <div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
    </div><!--/.content-->
</div><!--/#help-->

{%include file="common/browseback.phtml"%}
