{%include file="header.phtml"%}
{%include file="common/ad_header.phtml"%}

<div id="estateList">
	<div class="content" style="background:#eeffff;">
		<div class="headline" style="background:#82bdba;text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/estate.gif" width="230" height="60" /><br />
		</div><!--/#headline-->
		<div class="money">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<table width="220" cellpadding="3" cellspacing="1" border="0" align="center" style="background:#82bdba;">
				<tr>
					<td style="background:#ffffee;text-align:center;"><div style="{% if $ua==1 %}font-size:x-small;{%/if%}">
						{% if $gold >= 1000000 || $point >= 1000000 %}
							{% emoji code="F8C8" %}所持M {% $gold|string_format:"%'#7s"|replace:"#":"&nbsp;" %}<br />
							{% emoji code="F8E5" %}所持T {% $point|string_format:"%'#7s"|replace:"#":"&nbsp;" %}<br />
						{% elseif $gold >= 100000 || $point >= 100000 %}
							{% emoji code="F8C8" %}所持M {% $gold|string_format:"%'#6s"|replace:"#":"&nbsp;" %}<br />
							{% emoji code="F8E5" %}所持T {% $point|string_format:"%'#6s"|replace:"#":"&nbsp;" %}<br />
						{% else %}
							{% emoji code="F8C8" %}所持M {% $gold|string_format:"%'#5s"|replace:"#":"&nbsp;" %}<br />
							{% emoji code="F8E5" %}所持T {% $point|string_format:"%'#5s"|replace:"#":"&nbsp;" %}<br />
						{% /if %}
					</div></td>
				</tr>
			</table>
		</div><!--/.money-->
		<div class="kind" style="text-align:center;">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% if $genre == 0 %}すべて{% else %}<a href='{% "$baseUrl/mobile/kitchenshop/estatelist?genre=0"|mixiurl %}'>すべて</a>{% /if %}<span style="color:#999999;">|</span>{% if $genre == 1 %}洋食{% else %}<a href='{% "$baseUrl/mobile/kitchenshop/estatelist?genre=1"|mixiurl %}'>洋食</a>{% /if %}<span style="color:#999999;">|</span>{% if $genre == 2 %}ﾘｽﾄﾗﾝﾃ{% else %}<a href='{% "$baseUrl/mobile/kitchenshop/estatelist?genre=2"|mixiurl %}'>ﾘｽﾄﾗﾝﾃ</a>{% /if %}<br />
			<span style="color:#999999;">和食|中華|ｴｽﾆｯｸ|ﾒｷｼｶﾝ</span><br />
			{%*
				{% if $genre == 3 %}和食{% else %}<a href='{% "$baseUrl/mobile/kitchenshop/estatelist?genre=3"|mixiurl %}'>和食</a>{% /if %}<span style="color:#999999;">|</span>{% if $genre == 4 %}中華{% else %}<a href='{% "$baseUrl/mobile/kitchenshop/estatelist?genre=4"|mixiurl %}'>中華</a>{% /if %}<span style="color:#999999;">|</span>{% if $genre == 5 %}ｴｽﾆｯｸ{% else %}<a href='{% "$baseUrl/mobile/kitchenshop/estatelist?genre=5"|mixiurl %}'>ｴｽﾆｯｸ</a>{% /if %}<span style="color:#999999;">|</span>{% if $genre == 6 %}ﾒｷｼｶﾝ{% else %}<a href='{% "$baseUrl/mobile/kitchenshop/estatelist?genre=6"|mixiurl %}'>ﾒｷｼｶﾝ</a>{% /if %}<br />
			*%}
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div style="background:#82bdba;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
		</div><!--/.kind-->
		<div class="count">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% $count %}件中 {% $start %}-{% if $count <= $start+4 %}{% $count %}{% else %}{% $start+4 %} {% /if %}件<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div style="background:#82bdba;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
		</div><!--/.count-->
		<div class="inner">
			{% foreach from=$estateList item=data key=key %}
				<div class="section">
					<table width="100%" cellpadding="0" cellspacing="0" border="0">
						<tr>
							<td style="width:44px;text-align:center;vertical-align:top;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/estate/40x40/{% $data.estate_picture %}.gif" width="40" height="40" style="margin:3px 0;" /></td>
							<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}">
								<span style="color:#82bdba;"> [{%$data.genreName%}]</span>{%$data.estate_name%}<br />
								{%$data.estate_introduce%}<br />
								{% if $data.msgType == 0 %}
									<div style="color:#999999;text-align:right;"><a href='{% "$baseUrl/mobile/kitchenshop/estateconfirmpoint?estate_id=`$data.estate_id`&genre=`$data.genre`"|mixiurl %}'>{%$data.estate_price_point%}T</a>&nbsp;</div>
								{% elseif $data.msgType == 1 %}
									<div style="color:#ff0000;text-align:right;">{%$data.up_genreName|replace:"　":""%}ﾚｼﾋﾟ{%$data.up_recipe_count%}習得～購入可</div>
								{% elseif $data.msgType == 2 %}
									<div style="color:#999999;text-align:right;">まだ購入できません</div>
								{% else %}
									<div style="color:#999999;text-align:right;">購入済</div>
								{% /if %}
							</div></td>
						</tr>
					</table>
					<div style="background:#82bdba;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
				</div><!--/.section-->
			{% /foreach %}
			{% if $count > 5 %}
				<div class="pager" style="color:#006699;text-align:center;">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					{%include file="kitchenshop/common/pagergoods.phtml"%}<br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<div style="background:#82bdba;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
				</div><!--/.pager-->
			{% /if %}
			<div class="toInvite" style="text-align:center;">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F8E6" %}<a href='{% "$baseUrl/mobile/kitchen/inviteguide"|mixiurl %}'>ﾏｲﾐｸ招待で100M+ﾌﾟﾚﾐｱｶﾞﾁｬ</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#82bdba;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.toInvite-->
			<div class="footlink">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchenshop/shopping"|mixiurl %}'>マイキチデパート</a><br />
				{% emoji code="F8C4" %}<a href='{% "$baseUrl/mobile/kitchen/home"|mixiurl %}'>Myレストラン</a><br />
			</div><!--/.footlink-->
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="line" style="background:#82bdba;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
		</div><!--/.inner-->
	</div><!--/.content-->
</div><!--/#estateList-->

{%include file="common/menu.phtml"%}
{%include file="ad_footer.phtml"%}
