{%include file="header.phtml"%}
{%include file="common/ad_header.phtml"%}

<div id="gachaList">
	<div class="content" style="background:#eeffff;"> 
		<div class="headline" style="background:#82bdba;color:#ffffff;text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/gacha.gif" width="230" height="60" /><br />
		</div><!--/#headline-->
		<div class="description">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			ﾌﾟﾚﾐｱｶﾞﾁｬで入手できるのは、すべて非売品ｱｲﾃﾑ!ﾚｱなざっかや食材をGETして友達に自慢しよう!<br />
		</div><!--/.description-->
		<div class="status">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<table width="220" cellpadding="3" cellspacing="1" border="0" align="center" style="background:#82bdba;">
				<tr>
					<td style="background:#ffffee;text-align:center;"><div style="{% if $ua==1 %}font-size:x-small;{%/if%}">
						{% emoji code="F973" %}ﾏｲﾐｸ招待数 {% $userGachaInfo.invite_count|string_format:"%'#2s"|replace:"#":"&nbsp;"%}人<br />
						{% emoji code="F8F5" %}ｶﾞﾁｬ挑戦権 {% $userGachaInfo.gacha_count|string_format:"%'#2s"|replace:"#":"&nbsp;"%}回<br />
						</div></td>
				</tr>
			</table>
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div style="background:#82bdba;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
		</div><!--/.status-->
		<div class="inner">
			{% foreach from=$gachaList item=data key=key %}
				<div class="section" style="text-align:center;">
					<a href='{% "$baseUrl/mobile/kitchenshop/gachainfo?gacha_id=`$data.gacha_id`"|mixiurl %}'><img src="{%$staticUrl%}/apps/kitchen/mobile/img/gacha/192x53/{%$data.gacha_picture%}.gif" width="192" height="53" style="margin:3px 0;" /><br />{%$data.gacha_name%}</a><br />{% if $data.gacha_picture == "01" %}<span style="color:#cc0000;">↑初心者はまずコチラ↑</span><br />{% /if %}
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<div style="background:#82bdba;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
				</div><!--/.section-->
			{% /foreach %}
		</div><!--/.inner-->
		<div class="toInvite" style="text-align:center;">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% emoji code="F8E6" %}<a href='{% "$baseUrl/mobile/kitchen/inviteguide"|mixiurl %}'>ﾏｲﾐｸ招待で100M+ﾌﾟﾚﾐｱｶﾞﾁｬ</a><br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div style="background:#82bdba;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
		</div><!--/.toInvite-->
		<div class="footlink">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchenshop/shopping"|mixiurl %}'>マイキチデパート</a><br />
			{% emoji code="F8C4" %}<a href='{% "$baseUrl/mobile/kitchen/home"|mixiurl %}'>Myレストラン</a><br />
		</div><!--/.footlink-->
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#82bdba;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/.gachaList-->

{%include file="common/menu.phtml"%}
{%include file="ad_footer.phtml"%}
