{%include file="./header.phtml"%}
{%include file="./common/ad_header.phtml"%}

<div id="gachaConfirm">
	<div class="content" style="background:#eeffff;"> 
		<div class="headline" style="background:#82bdba;color:#ffffff;text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/gacha.gif" width="230" height="60" /><br />
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			{%$gachaInfo.gacha_name%}<br />
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/gacha/240x100/{%$gachaInfo.gacha_picture%}.gif" width="240" height="100" style="margin-top:1px;" /><br />
		</div><!--/#headline-->
		<div class="thumb" style="text-align:center;">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			ガチャでしか手に入らない<br />
			食材･ざっか･どうぐをGETしよう<br />
		</div><!--/.thumb-->
		<div class="gachaContent">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#82bdba;color:#ffffff;text-align:center;">
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
				GETできる賞品(一部)<br />
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			</div><!--/.headline-->
			{% foreach from=$gachaDetail item=data key=key %}
				<div class="section">
					<table width="100%" cellpadding="0" cellspacing="0" border="0">
						<tr>
							<td style="width:44px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/{%$data.picfolder%}/40x40/{%$data.picture%}.gif" width="40" height="40" style="margin:3px 0;" /></td>
							<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}">
								{%$data.name%}<br />
								{%$data.introduce%}<br />
								<div style="color:#cc0000;text-align:right;">{% if $data.type == 0 %}非売品{%/if%}&nbsp;</div>
							</div></td>
						</tr>
					</table>
					<div style="background:#82bdba;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
				</div><!--/.section-->
			{% /foreach %}
		</div><!--/.gachaContent-->

		<div class="entry" style="text-align:center;">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
			{% emoji code="F8F5" %}ｶﾞﾁｬに挑戦する{% emoji code="F8F5" %}<br />
			1回 <a href='{% "$baseUrl/mobile/kitchenshop/gachaconfirm?gacha_id=`$gachaInfo.gacha_id`"|mixiurl %}'>{%$gachaInfo.gacha_price_gold%}M</a><br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
		</div><!--/.entry-->

		<div class="caution" style="color:#cc0000;">
			{% emoji code="F9DC" %}友達を1人招待するごとに1回無料でｶﾞﾁｬに挑戦できます<br />
		</div><!--/.caution-->

		<div class="invite" style="text-align:center;">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
			{% emoji code="F8E6" %}<a href='{% "$baseUrl/mobile/kitchen/inviteguide"|mixiurl %}'>ﾏｲﾐｸ招待で100M+ﾌﾟﾚﾐｱｶﾞﾁｬ</a><br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
		</div><!--/.invite-->

		<div class="account">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<table width="150" cellpadding="0" cellspacing="0" border="0" align="center" style="text-align:center;">
				<tr>
					<td colspan="2"><div class="line" style="background:#82bdba;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div></td>
				</tr>
				<tr>
					<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}text-align:left;">{% emoji code="F973" %}ﾏｲﾐｸ招待数</div></td>
					<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}text-align:right;">{%$userGachaInfo.invite_count|string_format:"%'#2s"|replace:"#":"&nbsp;"%}回</div></td>
				</tr>
				<tr>
					<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}text-align:left;">{% emoji code="F8F5" %}ｶﾞﾁｬ挑戦権</div></td>
					<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}text-align:right;">{%$userGachaInfo.gacha_count|string_format:"%'#2s"|replace:"#":"&nbsp;"%}回</div></td>
				</tr>
				<tr>
					<td colspan="2"><div class="line" style="background:#82bdba;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div></td>
				</tr>
			</table>
		</div><!--/.account-->
		{% if $userGachaInfo.gacha_count > 0 %}
			<div class="buy" style="color:#cc0000;text-align:center;">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
				{% emoji code="F8F5" %}<a href='{% "$baseUrl/mobile/kitchenflash/gacha?gacha_id=`$gachaInfo.gacha_id`&pay=1&opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$osUID`&rand=`$rand`"|mobile_flashurl %}' style="color:#cc0000;"><span style="color:#cc0000;">挑戦権でガチャる!</span></a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
			</div><!--/.buy-->
		{% else %}
			<div class="buy" style="color:#cc0000;text-align:center;">
				<img src="img/spacer.gif" width="1" height="10" /><br />
				<span style="color:#cc0000;">ｶﾞﾁｬ挑戦権がありません{% emoji code="F9A5" %}</span><br />
				{% emoji code="F8E6" %}<a href='{% "$baseUrl/mobile/kitchen/inviteguide"|mixiurl %}'>ﾏｲﾐｸ招待で100M+ﾌﾟﾚﾐｱｶﾞﾁｬ</a><br />
				<img src="img/spacer.gif" width="1" height="10" /><br />
			</div><!--/.buy-->
		{% /if %}
		<div class="caution" style="color:#cc0000;">
			{% emoji code="F9DC" %}必ずしもご希望の景品が獲得できるわけではありませんので､ご注意ください｡<br />
		</div><!--/.caution-->

		<div class="footlink">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div style="background:#82bdba;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchenshop/gachalist"|mixiurl %}'>プレミアガチャ</a><br />
			{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchenshop/shopping"|mixiurl %}'>マイキチデパート</a><br />
			{% emoji code="F8C4" %}<a href='{% "$baseUrl/mobile/kitchen/home"|mixiurl %}'>Myレストラン</a><br />
		</div><!--/.footlink-->

		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#82bdba;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#gachaConfirm-->

{%include file="./common/menu.phtml"%}
{%include file="./ad_footer.phtml"%}
