{%include file="header.phtml"%}
{%include file="common/ad_header.phtml"%}

<div id="gachaConfirm">
	<div class="content" style="background:#eeffff;"> 
		<div class="headline" style="background:#82bdba;color:#ffffff;text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/gacha.gif" width="230" height="60" /><br />
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			{%$gachaInfo.gacha_name%}<br />
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/gacha/240x100/{%$gachaInfo.gacha_picture%}.gif" width="240" height="100" /><br />
		</div><!--/#headline-->
		<div class="thumb" style="text-align:center;">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			ガチャでしか手に入らない<br />
			食材･ざっか･どうぐをGETしよう<br />
		</div><!--/.thumb-->
		<div class="gachaContent">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#82bdba;color:#ffffff;text-align:center;">
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
				GETできる賞品(一部)<br />
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			</div><!--/.headline-->
			{% foreach from=$gachaDetail item=data key=key %}
				<div class="section">
					<table width="100%" cellpadding="0" cellspacing="0" border="0">
						<tr>
							<td style="width:44px;text-align:center;vertical-align:top;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/{%$data.picfolder%}/40x40/{%$data.picture%}.gif" width="40" height="40" style="margin:3px 0;" /></td>
							<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}">
								{%$data.name%}<br />
								{%$data.introduce%}<br />
								<div style="color:#cc0000;text-align:right;">{% if $data.type == 0 %}非売品{%/if%}&nbsp;</div>
							</div></td>
						</tr>
					</table>
					<div style="background:#82bdba;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
				</div><!--/.section-->
			{% /foreach %}
		</div><!--/.gachaContent-->
		<div class="account">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
			<table width="150" cellpadding="0" cellspacing="0" border="0" align="center" style="text-align:center;">
				<tr>
					<td colspan="2"><div class="line" style="background:#82bdba;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div></td>
				</tr>
				<tr>
					<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}text-align:left;">{% emoji code="F8C8" %}所持M</div></td>
					<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}text-align:right;">{% $gold %}M</div></td>
				</tr>
				<tr>
					<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}text-align:left;">{% emoji code="F8C8" %}価格</div></td>
					<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}text-align:right;">{% $gachaInfo.gacha_price_gold %}M</div></td>
				</tr>
				{% if $gachaInfo.gacha_price_gold <= $gold %}
					<tr>
						<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}text-align:left;">{% emoji code="F8C8" %}利用後G</div></td>
						<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}color:#cc0000;text-align:right;">{% $gold-$gachaInfo.gacha_price_gold %}M</div></td>
					</tr>
				{% /if %}
				<tr>
					<td colspan="2"><div class="line" style="background:#82bdba;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div></td>
				</tr>
			</table>
		</div><!--/.account-->
		{% if $gachaInfo.gacha_price_gold <= $gold %}
			<div class="buy" style="color:#cc0000;text-align:center;">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
				{% emoji code="F8C8" %}<a href='{% "$baseUrl/mobile/kitchenflash/gacha?gacha_id=`$gachaInfo.gacha_id`&pay=2&opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$osUID`&rand=`$rand`"|mobile_flashurl %}' style="color:#cc0000;"><span style="color:#cc0000;">利用する(購入)</span></a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
			</div><!--/.buy-->
		{% else %}
			<div class="buy" style="color:#cc0000;text-align:center;">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
				{% emoji code="F997" %}ﾒﾀﾞﾙが足りません<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
			</div><!--/.buy-->
		{% /if %}
		<div class="caution" style="color:#cc0000;">
			{% emoji code="F9DC" %}必ずしもご希望の景品が獲得できるわけではありませんので､ご注意ください｡<br />
		</div><!--/.caution-->
		{% if $gachaInfo.gacha_price_gold > $gold %}
			<div class="toInvite" style="text-align:center;">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#82bdba;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F8E6" %}<a href='{% "$baseUrl/mobile/kitchen/inviteguide"|mixiurl %}'>ﾏｲﾐｸ招待で100M+ﾌﾟﾚﾐｱｶﾞﾁｬ</a><br />
			</div><!--/.toInvite-->
		{% /if %}
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#82bdba;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#gachaConfirm-->

{%include file="common/browseback.phtml"%}
{%include file="footer.phtml"%}
