{%include file="header.phtml"%}

<div id="yorozuConfirm">
	<div class="content" style="background:#eeffff;"> 
		<div class="headline" style="background:#82bdba;color:#ffffff;text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/giftshop.gif" width="230" height="60" /><br />
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			{% $giftInfo.name %}<br />
		</div><!--/#headline-->
		<div class="description">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			こちらのギフトを購入しますか?<br />
		</div><!--/.description-->
		<div class="thumb" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/gift/130x130/{% $giftInfo.picture %}" width="130" height="130" style="margin:3px 0;" /><br />
			{% $giftInfo.introduce %}<br />
		</div><!--/.thumb-->
		<div class="giftContent">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#82bdba;color:#ffffff;text-align:center;">
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
				{% emoji code="F8E6" %}次の3点が贈られます{% emoji code="F8E6" %}<br />
				<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
			</div><!--/.headline-->
			{% foreach from=$unitList item=data key=key %}
				<div class="section">
					<table width="100%" cellpadding="0" cellspacing="0" border="0">
						<tr>
							<td style="width:44px;text-align:center;vertical-align:top;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/{% $data.belong %}/40x40/{% $data.unit_pictrue %}.gif" width="40" height="40" style="margin:3px 0;" /></td>
							<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}">
								{% $data.unit_name %}<br />
								{% $data.unit_introduce %}<br />
								<div style="color:#cc0000;text-align:right;">{% if $data.type == 0%}非売品{% /if %}&nbsp;</div>
							</div></td>
						</tr>
					</table>
					<div style="background:#82bdba;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
				</div><!--/.section-->
			{% /foreach %}
		</div><!--/.giftContent-->

		<div class="account">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
			<table width="150" cellpadding="0" cellspacing="0" border="0" align="center" style="text-align:center;">
				<tr>
					<td colspan="2"><div class="line" style="background:#82bdba;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div></td>
				</tr>
				<tr>
					<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}text-align:left;">{% if $payType == "gold" %}{% emoji code="F8C8" %}所持M{% else %}{% emoji code="F8E5" %}所持T{% /if %}</div></td>
					<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}text-align:right;">{% if $payType == "gold" %}{% $gold %}M{% else %}{% $point %}T{% /if %}</div></td>
				</tr>
				<tr>
					<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}text-align:left;">{% if $payType == "gold" %}{% emoji code="F8C8" %}{% else %}{% emoji code="F8E5" %}{% /if %}価格</div></td>
					<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}text-align:right;">{% if $payType == "gold" %}{% $giftInfo.price_gold %}M{% else %}{% $giftInfo.price_point %}T{% /if %}</div></td>
				</tr>
				{% if $giftInfo.disct > 0%}
				<tr>
					<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}text-align:left;">{% if $payType == "gold" %}{% emoji code="F8C8" %}割引M{% else %}{% emoji code="F8E5" %}割引T{% /if %}</div></td>
					<td><div style="color:#cc0000;{% if $ua==1 %}font-size:x-small;{%/if%}text-align:right;">-{% if $payType == "gold" %}{% $giftInfo.disct %}M{% else %}{% $giftInfo.disct %}T{% /if %}</div></td>
				</tr>
				{% /if %}
				{% if $result == 1%}
					<tr>
						<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}text-align:left;">{% if $payType == "gold" %}{% emoji code="F8C8" %}購入後M{% else %}{% emoji code="F8E5" %}購入後T{% /if %}</div></td>
						<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}color:#cc0000;text-align:right;">{% if $payType == "gold" %}{% $giftInfo.money_left %}M{% else %}{% $giftInfo.money_left %}T{% /if %}</div></td>
					</tr>
				{% /if %}
				<tr>
					<td colspan="2"><div class="line" style="background:#82bdba;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div></td>
				</tr>
			</table>
		</div><!--/.account-->

		{% if $result == 1 %}
			<div class="buy" style="color:#cc0000;text-align:center;">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
				{% if $payType == "gold" %}{% emoji code="F8C8" %}{% else %}{% emoji code="F8E5" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchenshop/giftfinish?gift_id=`$giftInfo.gift_id`&pay=`$payType`"|mixiurl %}' style="color:#cc0000;"><span style="color:#cc0000;">購入する</span></a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
			</div><!--/.buy-->
		{% else %}
			<div class="buy" style="color:#cc0000;text-align:center;">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
				{% emoji code="F997" %}{% if $payType == "gold" %}ﾒﾀﾞﾙ{% else %}ﾁｯﾌﾟ{% /if %}が足りません<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
			</div><!--/.buy-->
		{% /if %}

		<div class="caution">
			{% emoji code="F9DC" %}ｷﾞﾌﾄはﾌﾟﾚｾﾞﾝﾄ専用ｱｲﾃﾑです｡<span style="color:#cc0000;">ご自身では利用できません</span>のでご注意ください｡<br />
		</div><!--/.caution-->

		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#82bdba;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	</div><!--/.content-->
</div><!--/#yorozuConfirm-->

{%include file="common/browseback.phtml"%}
{%include file="footer.phtml"%}
