{%include file="header.phtml"%}
{%include file="common/ad_header.phtml"%}

<div id="zakkaList">
	<div class="content" style="background:#eeffff;">
		<div class="headline" style="background:#82bdba;text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/zakka.gif" width="230" height="60" /><br />
		</div><!--/#headline-->
		<div class="money">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<table width="220" cellpadding="3" cellspacing="1" border="0" align="center" style="background:#82bdba;">
				<tr>
					<td style="background:#ffffee;text-align:center;"><div style="{% if $ua==1 %}font-size:x-small;{%/if%}">
						{% if $gold >= 1000000 || $point >= 1000000 %}
							{% emoji code="F8C8" %}所持M {% $gold|string_format:"%'#7s"|replace:"#":"&nbsp;" %}<br />
							{% emoji code="F8E5" %}所持T {% $point|string_format:"%'#7s"|replace:"#":"&nbsp;" %}<br />
						{% elseif $gold >= 100000 || $point >= 100000 %}
							{% emoji code="F8C8" %}所持M {% $gold|string_format:"%'#6s"|replace:"#":"&nbsp;" %}<br />
							{% emoji code="F8E5" %}所持T {% $point|string_format:"%'#6s"|replace:"#":"&nbsp;" %}<br />
						{% else %}
							{% emoji code="F8C8" %}所持M {% $gold|string_format:"%'#5s"|replace:"#":"&nbsp;" %}<br />
							{% emoji code="F8E5" %}所持T {% $point|string_format:"%'#5s"|replace:"#":"&nbsp;" %}<br />
						{% /if %}
					</div></td>
				</tr>
			</table>
		</div><!--/.money-->
		<div class="count">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% $count %}件中 {% $start %}-{% if $count <= $start+4 %} {% $count %} {% else %}{% $start+4 %}  {% /if %}件<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div style="background:#82bdba;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
		</div><!--/.count-->
		<div class="inner">
			{% foreach from=$goodsList item=data key=key %}
				<div class="section">
					<table width="100%" cellpadding="0" cellspacing="0" border="0">
						<tr>
							<td style="width:44px;text-align:center;vertical-align:top;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/zakka/40x40/{% $data.goods_picture %}.gif" width="40" height="40" style="margin:3px 0;" /></td>
							<td><div style="{% if $ua==1 %}font-size:x-small;{%/if%}">
								<span style="color:#82bdba;"> [{%$data.genreName%}]</span>{%$data.goods_name%}<br />
								{%$data.goods_introduce%}<br />
								{% if $data.genreLevel >= $data.level %}
									<div style="color:#999999;text-align:right;"><a href='{% "$baseUrl/mobile/kitchenflash/setgoods?goodsId=`$data.goods_id`1&pay=gold&opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$osUID`&rand=`$rand`"|mobile_flashurl %}'>{%$data.goods_price_gold%}M</a>/{% if $data.type == 1%}<a href='{% "$baseUrl/mobile/kitchenflash/setgoods?goodsId=`$data.goods_id`1&pay=point&opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$osUID`&rand=`$rand`"|mobile_flashurl %}'>{%$data.goods_price_point%}T</a>{% else %}非売品{% /if %}&nbsp;</div>
								{% else %}
									<div style="color:#ff0000;text-align:right;">Lv.{%$data.level%}～購入可</div>
								{% /if %}
							</div></td>
						</tr>
					</table>
					<div style="background:#82bdba;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
				</div><!--/.section-->
			{% /foreach %}
			{% if $count > 5 %}
				<div class="pager" style="color:#006699;text-align:center;">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					{%include file="kitchenshop/common/pagergoods.phtml"%}<br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<div style="background:#82bdba;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
				</div><!--/.pager-->
			{% /if %}
			<div class="toInvite" style="text-align:center;">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F99F" %}<a href='{% "$baseUrl/mobile/kitchenshop/gachalist"|mixiurl %}'>非売品ざっかをﾌﾟﾚﾐｱｶﾞﾁｬでGET</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div style="background:#82bdba;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.toInvite-->
			<div class="footlink">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchenshop/shopping"|mixiurl %}'>マイキチデパート</a><br />
				{% emoji code="F9B8" %}<a href='{% "$baseUrl/mobile/kitchenitem/good"|mixiurl %}'>アイテムBOX:ざっか置き場</a><br />
				{% emoji code="F8C4" %}<a href='{% "$baseUrl/mobile/kitchen/home"|mixiurl %}'>Myレストラン</a><br />
			</div><!--/.footlink-->
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="line" style="background:#82bdba;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
		</div><!--/.inner-->
	</div><!--/.content-->
</div><!--/#zakkaList-->

{%include file="common/menu.phtml"%}
{%include file="ad_footer.phtml"%}