<div id="guide">
	<div class="content" style="background:#ffffdd;">
		<div class="headline" style="background:#81623e;color:#ffffff;text-align:center;">
			<img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/makeguide.gif" width="230" height="60" /><br />
		</div><!--/#headline-->
		<div class="inner">
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				レシピ開発方法を伝授します!<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="line" style="background:#81623e;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.description-->
			<div class="section">
				<table width="100%" cellpadding="0" cellspacing="0" border="0">
					<tr>
						<td style="width:64px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/recipe/g01.jpg" width="60" height="60" style="margin:3px 0;" /></td>
						<td><img src="{%$staticUrl%}/apps/kitchen/mobile/img/recipe/g01.gif" width="165" height="60" /></td>
					</tr>
				</table>
				<span style="color:#cc0000;">キッチンの[レシピ選択]画面より[レシピ開発部]を選んでください</span>レシピ開発部長がアナタの訪問を今か今かと待ちわびています{% emoji code="F994" %}<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="line" style="background:#81623e;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<table width="100%" cellpadding="0" cellspacing="0" border="0">
					<tr>
						<td style="width:64px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/recipe/g02.jpg" width="60" height="60" style="margin:3px 0;" /></td>
						<td><img src="{%$staticUrl%}/apps/kitchen/mobile/img/recipe/g02.gif" width="165" height="60" /></td>
					</tr>
				</table>
				冷蔵庫にある<span style="color:#cc0000;">食材を2種類以上配合</span>します{% emoji code="F99C" %}<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="line" style="background:#81623e;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="section">
				<table width="100%" cellpadding="0" cellspacing="0" border="0">
					<tr>
						<td style="width:64px;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/recipe/g03.jpg" width="60" height="60" style="margin:3px 0;" /></td>
						<td><img src="{%$staticUrl%}/apps/kitchen/mobile/img/recipe/g03.gif" width="165" height="60" /></td>
					</tr>
				</table>
				配合に成功すると、成功レシピを見てシェフが調理を始めます{% emoji code="F99F" %}<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="line" style="background:#81623e;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.section-->
			<div class="toGame" style="text-align:center;">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
				<span style="color:#cc0000;">まだレシピ開発をしていない場合は<br />
					[ウィンナー]と[ポテト]を配合し<br />
					[ジャーマンポテト]を<br />
					レシピ開発してみましょう!</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="5" /><br />
				これでかんたん入門ｶﾞｲﾄﾞは終了です<br />
				詳しいﾙｰﾙや説明は<br />
				ﾍﾙﾌﾟの各項目をご覧ください<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="5" /><br />
	            <table width="230" cellpadding="3" cellspacing="1" border="0" align="center" style="background:#81623e;">
					<tr>
						<td style="background:#ffffcc;text-align:center;"><div style="{% if $ua==1 %}font-size:x-small;{%/if%}"><span style="color:#006699;">≫</span><a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=index"|mixiurl %}'>ヘルプ：もくじへ</a><span style="color:#006699;">≪</span></div></td>
					</tr>
	            </table>
			</div><!--/.toGame-->
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="10" /><br />
			<div class="line" style="background:#81623e;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
	    </div><!--/.inner-->
	</div><!--/.content-->
</div><!--/#guide-->
