<div id="help">
    <div class="content" style="background:#f0f5e0;">
        <div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
            <img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/help.gif" width="230" height="60" /><br />
            <img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
            {% emoji code="F8D0" %}キッチンの遊び方<br />
        </div><!--/.headline-->
		<div class="subHeadline" style="text-align:center;">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<span style="color:#497d40;">調理（レシピ選択）</span><br />
			<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
		</div><!--/.subHeadline-->
        <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
        <div class="inner">
			ｷｯﾁﾝで調理をする手順については､以下の通りとなります｡<br />
			<br />
			1.空いている調理台で､｢ﾚｼﾋﾟ選択｣をｸﾘｯｸします｡<br />
			<br />
			2.習得済みﾚｼﾋﾟを選択するか､ﾚｼﾋﾟ開発を成功させます｡<br />
			<br />
			3.選択したﾚｼﾋﾟ､開発に成功したﾚｼﾋﾟの調理がｽﾀｰﾄします｡<br />
			<br />
			4.ﾚｼﾋﾟごとに決められた時間が経過すると､料理が完成します｡<br />
			<br />
			※ﾚｼﾋﾟ開発は､ﾚﾍﾞﾙ2から利用できます｡<br />
        </div><!--/.inner-->
        <div class="footlink">
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
            <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchenstatic/help"|mixiurl %}'>ヘルプ:もくじ</a><br />
        </div><!--/.footlink-->
        <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
        <div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
    </div><!--/.content-->
</div><!--/#help-->
