<div id="help">
    <div class="content" style="background:#f0f5e0;">
        <div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
            <img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/help.gif" width="230" height="60" /><br />
            <img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
            {% emoji code="F8E4" %}レシピ開発/レシピ図鑑<br />
        </div><!--/.headline-->
		<div class="subHeadline" style="text-align:center;">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<span style="color:#497d40;">レシピ開発</span><br />
			<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
		</div><!--/.subHeadline-->
        <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
        <div class="inner">
			ﾚｼﾋﾟ開発に関する説明は､以下の通りとなります｡<br />
			<br />
			1.新規ﾚｼﾋﾟ開発は､ﾚｼﾋﾟ選択の時に実行できます｡<br />
			<br />
			2.ﾚｼﾋﾟ開発に成功すると､ﾚｼﾋﾟを習得して､そのまま調理がｽﾀｰﾄします｡<br />
			<br />
			3.ﾚｼﾋﾟ開発は､調理台ごとの1回の調理につき3回までﾁｬﾚﾝｼﾞできます｡3回失敗すると既存ﾚｼﾋﾟで一度調理を完了するまでは､ﾚｼﾋﾟ開発にﾁｬﾚﾝｼﾞできません｡<br />
			<br />
			4.ﾏｲﾐｸのｷｯﾁﾝで味見をするときにﾚｼﾋﾟを覚えることもあります｡<br />
        </div><!--/.inner-->
        <div class="footlink">
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
            <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchenstatic/help"|mixiurl %}'>ヘルプ:もくじ</a><br />
        </div><!--/.footlink-->
        <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
        <div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
    </div><!--/.content-->
</div><!--/#help-->
