<div id="help">
    <div class="content" style="background:#f0f5e0;">
        <div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
            <img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/help.gif" width="230" height="60" /><br />
            <img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
            {% emoji code="F9EB" %}デパートでお買いもの<br />
        </div><!--/.headline-->
		<div class="subHeadline" style="text-align:center;">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<span style="color:#497d40;">プレミアガチャ</span><br />
			<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
		</div><!--/.subHeadline-->
        <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
        <div class="inner">
			ﾌﾟﾚﾐｱｶﾞﾁｬでは､非売品のｱｲﾃﾑが当たるｶﾞﾁｬに挑戦できます｡ﾌﾟﾚﾐｱｶﾞﾁｬを利用する手順は､以下の通りです｡<br />
			<br />
			1.ﾌﾟﾚﾐｱｶﾞﾁｬ画面で､挑戦したいｶﾞﾁｬを選択します｡<br />
			<br />
			2.ｶﾞﾁｬ内容を確認して､ｶﾞﾁｬの値段をｸﾘｯｸします｡<br />
			<br />
			3.確認画面で｢利用する｣をｸﾘｯｸすると､ｶﾞﾁｬ画面が表示されます｡<br />
			<br />
			4.ｶﾞﾁｬ画面で決定ﾎﾞﾀﾝをｸﾘｯｸして､ｶﾞﾁｬに挑戦します｡<br />
			<br />
			5.決定ﾎﾞﾀﾝを再度ｸﾘｯｸして､ｶﾞﾁｬの結果を確認します｡<br />
			<br />
			※ﾌﾟﾚﾐｱｶﾞﾁｬは必ずしもご希望のｱｲﾃﾑが獲得できるわけではありませんので､ご注意ください｡<br />
			※ﾏｲﾐｸの招待が1人成立するごとに､ﾒﾀﾞﾙを使わずにｶﾞﾁｬに挑戦できます｡<br />
        </div><!--/.inner-->
        <div class="footlink">
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
            <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchenstatic/help"|mixiurl %}'>ヘルプ:もくじ</a><br />
        </div><!--/.footlink-->
        <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
        <div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
    </div><!--/.content-->
</div><!--/#help-->
