<div id="help">
    <div class="content" style="background:#f0f5e0;">
        <div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
            <img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/help.gif" width="230" height="60" /><br />
            <img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
            {% emoji code="F9B8" %}アイテムBOX<br />
        </div><!--/.headline-->
		<div class="subHeadline" style="text-align:center;">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<span style="color:#497d40;">ざっか置き場</span><br />
			<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
		</div><!--/.subHeadline-->
        <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
        <div class="inner">
			<ざっか置き場>では､置いてある<ざっか>も含めて今持っている<ざっか>が全て表示されます｡<ざっか置き場>に関する説明は､以下の通りとなります｡<br />
			<br />
			1.<ざっか>は､<ざっか屋>での購入や､ｷﾞﾌﾄを贈られることで獲得できます｡<br />
			<br />
			2.<ざっか>をMyﾚｽﾄﾗﾝに置きたい場合は､置きたい<ざっか>を選択して｢おく｣をｸﾘｯｸした後に置く場所を選択すると､Myﾚｽﾄﾗﾝに置くことができます｡<br />
			<br />
			3.Myﾚｽﾄﾗﾝに置いてある<ざっか>を片づけたい場合は､片づけたい<ざっか>を選択して､｢しまう｣をｸﾘｯｸすると片づけることができます｡<br />
			<br />
			※一度獲得した<ざっか>を捨てることはできません｡<br />
        </div><!--/.inner-->
        <div class="footlink">
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
            <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchenstatic/help"|mixiurl %}'>ヘルプ:もくじ</a><br />
        </div><!--/.footlink-->
        <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
        <div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
    </div><!--/.content-->
</div><!--/#help-->
