<div id="help">
    <div class="content" style="background:#f0f5e0;">
        <div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
            <img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/help.gif" width="230" height="60" /><br />
            <img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
            {% emoji code="F99F" %}その他<br />
        </div><!--/.headline-->
		<div class="subHeadline" style="text-align:center;">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<span style="color:#497d40;">マイミクを招待する</span><br />
			<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
		</div><!--/.subHeadline-->
        <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
        <div class="inner">
			ﾏｲﾐｸが増えるとｹﾞｰﾑが有利に進められます｡ﾏｲﾐｸを招待して招待が成立した場合は以下のﾌﾟﾚｾﾞﾝﾄがあります｡<br />
			<br />
			1.招待したﾏｲﾐｸがﾚｽﾄﾗﾝを開店したときにﾏｲﾐｸ招待が成立して､100Mがもらえます｡<br />
			<br />
			2.ﾏｲﾐｸの招待が1人成立するごとに､ﾒﾀﾞﾙを使わずにﾌﾟﾚﾐｱｶﾞﾁｬに挑戦できます｡<br />
			<br />
			※招待ﾒｯｾｰｼﾞを送信するだけでは､上記のﾌﾟﾚｾﾞﾝﾄはありません｡<br />
			※期間限定でﾎﾞｰﾅｽがもらえる場合があります｡開催するときは､ｱﾌﾟﾘﾄｯﾌﾟなどでお知らせを表示します｡<br />
        </div><!--/.inner-->
        <div class="footlink">
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
            <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchenstatic/help"|mixiurl %}'>ヘルプ:もくじ</a><br />
        </div><!--/.footlink-->
        <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
        <div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
    </div><!--/.content-->
</div><!--/#help-->
