<div id="help">
    <div class="content" style="background:#f0f5e0;">
        <div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
            <img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/help.gif" width="230" height="60" /><br />
            <img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
            {% emoji code="F8C5" %}運営者情報<br />
        </div><!--/.headline-->
		<div class="subHeadline" style="text-align:center;">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<span style="color:#497d40;">運営会社について</span><br />
			<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
		</div><!--/.subHeadline-->
        <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
        <div class="inner">
			■会社名<br />
			株式会社ｺﾐｭﾆﾃｨﾌｧｸﾄﾘｰ<br />
			<br />
			■創立<br />
			2006年2月<br />
			<br />
			■資本金<br />
			63,400,000円<br />
			<br />
			■代表取締役<br />
			松本 龍祐<br />
			<br />
			■所在地<br />
			〒150-0002<br />
			東京都渋谷区渋谷3-27-15<br />
			坂上ﾋﾞﾙ 6F<br />
			<br />
			■主な事業内容<br />
			･ｿｰｼｬﾙｱﾌﾟﾘｹｰｼｮﾝの企画/開発/運営<br />
			･ｿｰｼｬﾙﾈｯﾄﾜｰｷﾝｸﾞｻｲﾄの企画･開発<br />
			･ｿｰｼｬﾙﾈｯﾄﾜｰｷﾝｸﾞｻｲﾄの運営<br />
			･ﾌﾞﾛｸﾞｻｲﾄの企画/開発/運営<br />
			･ｲﾝﾀｰﾈｯﾄ上のｺﾐｭﾆﾃｨｻｲﾄの構築､運営<br />
			その他関連事業<br />
			<br />
        </div><!--/.inner-->
        <div class="footlink">
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
            <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchenstatic/help"|mixiurl %}'>ヘルプ:もくじ</a><br />
        </div><!--/.footlink-->
        <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
        <div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
    </div><!--/.content-->
</div><!--/#help-->
