<div id="help">
    <div class="content" style="background:#f0f5e0;">
        <div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
            <img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/help.gif" width="230" height="60" /><br />
            <img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
            {% emoji code="F8C5" %}運営者情報<br />
        </div><!--/.headline-->
		<div class="subHeadline" style="text-align:center;">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<span style="color:#497d40;">特定商取引法に基づく表記</span><br />
			<div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
		</div><!--/.subHeadline-->
        <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
        <div class="inner">
			■役務提供事業者<br />
			株式会社ｺﾐｭﾆﾃｨﾌｧｸﾄﾘｰ<br />
			<br />
			■所在地<br />
			〒150-0002　東京都渋谷区渋谷3-27-15 坂上ﾋﾞﾙ 6F<br />
			<br />
			■通信販売に関する責任者<br />
			松本 龍祐<br />
			<br />
			■問い合わせ先<br />
			ﾒｰﾙ:info@communityfactory.com<br />
			TEL:03-6419-3733<br />
			(平日 10:00〜17:00)<br />
			※お問い合わせへの回答は原則ﾒｰﾙにて行なっております｡何卒ご協力をお願いいたします｡<br />
			<br />
			■販売価格<br />
			対象となるﾃﾞｼﾞﾀﾙｺﾝﾃﾝﾂごとに表示される金額｡<br />
			<br />
			■販売価格以外の費用<br />
			ﾊﾟｹｯﾄ代の携帯電話の利用に伴う通信費用｡<br />
			<br />
			■支払の時期および方法<br />
			有料ﾃﾞｼﾞﾀﾙｺﾝﾃﾝﾂへのｱｸｾｽまたは有料ｺﾝﾃﾝﾂのﾀﾞｳﾝﾛｰﾄﾞについては､mixiのｱｶｳﾝﾄを通じて請求が行なわれます｡mixiが定める方法により､mixiによる請求を支払わなければなりません｡<br />
			<br />
			■提供時期<br />
			ﾃﾞｼﾞﾀﾙｺﾝﾃﾝﾂはお支払い手続き完了後､直ちに提供いたします｡<br />
			<br />
			■返金および交換<br />
			<br />	提供するﾃﾞｼﾞﾀﾙｺﾝﾃﾝﾂおよびｻｰﾋﾞｽの性質により､ご購入いただいたﾃﾞｼﾞﾀﾙｺﾝﾃﾝﾂの登録について返金および交換は行なわれません｡<br />
			<br />
			■対応機種<br />
			◯NTT DoCoMo<br />
			FOMA i-mode対応及びFlashLite1.1対応機種(N601i,L602i,70Xi/80Xi/90Xiｼﾘｰｽﾞ及びそれ以降の機種)<br />
			※NM850iGは除く<br />
			<br />
			◯KDDI(au)<br />
			CDMA 1X(A1407PT,A5011HM,A5526K,A5527SA,A5528K,A5529K,B01K)/WIN全機種の内FlashLite1.1対応機種<br />
			※法人用端末,W21Hは除く<br />
			<br />
			◯ｿﾌﾄﾊﾞﾝｸﾓﾊﾞｲﾙ<br />
			Softbank 3G対応機種の内FlashLite1.1対応機種<br />
			※旧Vodafone端末(2006年7月以前に発売)は除く<br />
			※HTC,Nokia(N73は対応)、Motorola端末は除く<br />
			※SAMSUNG端末(705SC,706SC,707SC,709SC)は除く<br />
			※iPhoneは除く<br />
			<br />
			◯DisneyMobile<br />
			FlashLite1.1対応機種<br />
			<br />
			機種によって一部機能をお使いいただけない場合がございます｡また､ﾌﾙﾌﾞﾗｳｻﾞ､PCｻｲﾄﾋﾞｭｰｱｰはｻﾎﾟｰﾄ対象外です｡<br />
			<br />
        </div><!--/.inner-->
        <div class="footlink">
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
            <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchenstatic/help"|mixiurl %}'>ヘルプ:もくじ</a><br />
        </div><!--/.footlink-->
        <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
        <div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
    </div><!--/.content-->
</div><!--/#help-->
