<div id="help">
    <div class="content" style="background:#f0f5e0;">
        <div class="headline" style="background:#8bbd82;color:#ffffff;text-align:center;">
            <img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/help.gif" width="230" height="60" /><br />
            <img src="{%$staticUrl%}/apps/kitchen/mobile/img/title/w.gif" width="100%" height="1" style="margin:1px 0;" /><br />
            もくじ<br />
        </div><!--/.headline-->
        <div class="inner">
			<div class="backMypage">
	            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% if $ua!=2 %}{% emoji code="F97E" %}{% else %}{% emoji code="F8F8" %}{% /if %}<a href='{% "$baseUrl/mobile/kitchen/home"|mixiurl %}'>Myレストラン</a><br />
				{% emoji code="F9A0" %}<a href='{% "$baseUrl/mobile/kitchenstatic/qa"|mixiurl %}'>よくある質問</a><br />
				{% emoji code="F977" %}<a href='{% "$baseUrl/mobile/kitchenstatic/info"|mixiurl %}'>運営事務局よりお知らせ</a><br />
	            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	            <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
			</div><!--/.backMypage-->
			<div class="section">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<a name="next01" id="next01"></a>
				<span style="color:#497d40;">{% emoji code="F9CE" %}かんたん入門ガイド</span><span style="color:#497d40;">[<a href="#next02" style="color:#497d40;"><span style="color:#497d40;">↓</span></a>]</span><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0101"|mixiurl %}'>どんなゲーム？</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0102"|mixiurl %}'>入門ガイド</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0103"|mixiurl %}'>レシピ開発ガイド</a><br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
            </div><!--/.section-->
            <div class="section" style="text-align:left;">
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<a name="next02" id="next02"></a>
                <span style="color:#497d40;">{% emoji code="F9BE" %}基本ルールと知識</span><span style="color:#497d40;">[<a href="#next03" style="color:#497d40;"><span style="color:#497d40;">↓</span></a>]</span><br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0201"|mixiurl %}'>シェフ</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0202"|mixiurl %}'>チップ</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0203"|mixiurl %}'>メダル</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0204"|mixiurl %}'>経験値</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0205"|mixiurl %}'>レベルアップ</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0206"|mixiurl %}'>お店の名前</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0207"|mixiurl %}'>レストランのジャンル</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0208"|mixiurl %}'>マイミクのキッチンを訪問</a><br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
            </div><!--/.section-->
            <div class="section" style="text-align:left;">
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<a name="next03" id="next03"></a>
                <span style="color:#497d40;">{% emoji code="F8D0" %}キッチンの遊び方</span><span style="color:#497d40;">[<a href="#next04" style="color:#497d40;"><span style="color:#497d40;">↓</span></a>]</span><br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0301"|mixiurl %}'>調理（レシピ選択）</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0302"|mixiurl %}'>味付け</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0303"|mixiurl %}'>ハエを飛ばす</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0304"|mixiurl %}'>ハエ撃退</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0305"|mixiurl %}'>どうぐを使う</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0306"|mixiurl %}'>味見する</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0307"|mixiurl %}'>料理を運ぶ</a><br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
            </div><!--/.section-->
            <div class="section" style="text-align:left;">
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<a name="next04" id="next04"></a>
                <span style="color:#497d40;">{% emoji code="F8E4" %}レシピ開発/レシピ図鑑</span><span style="color:#497d40;">[<a href="#next05" style="color:#497d40;"><span style="color:#497d40;">↓</span></a>]</span><br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0401"|mixiurl %}'>レシピ開発</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0402"|mixiurl %}'>食材が足りない場合</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0403"|mixiurl %}'>レシピ図鑑</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0404"|mixiurl %}'>マイミクのレシピ図鑑</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0405"|mixiurl %}'>ラッキー食材</a><br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
            </div><!--/.section-->
            <div class="section" style="text-align:left;">
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<a name="next05" id="next05"></a>
                <span style="color:#497d40;">{% emoji code="F8F6" %}お店の模様替え</span><span style="color:#497d40;">[<a href="#next06" style="color:#497d40;"><span style="color:#497d40;">↓</span></a>]</span><br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0501"|mixiurl %}'>ざっかを置く</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0502"|mixiurl %}'>ざっかをしまう</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0503"|mixiurl %}'>ざっかを購入する</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0504"|mixiurl %}'>不動産を変更する</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0505"|mixiurl %}'>ざっかのジャンル</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0506"|mixiurl %}'>マイミクのお店に飾る</a><br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
            </div><!--/.section-->
            <div class="section" style="text-align:left;">
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<a name="next06" id="next06"></a>
                <span style="color:#497d40;">{% emoji code="F8E6" %}ギフト</span><span style="color:#497d40;">[<a href="#next07" style="color:#497d40;"><span style="color:#497d40;">↓</span></a>]</span><br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0601"|mixiurl %}'>デイリーギフト</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0602"|mixiurl %}'>ごほうびギフト</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0603"|mixiurl %}'>マイミクからのギフト</a><br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
            </div><!--/.section-->
            <div class="section" style="text-align:left;">
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<a name="next07" id="next07"></a>
                <span style="color:#497d40;">{% emoji code="F9EB" %}デパートでお買いもの</span><span style="color:#497d40;">[<a href="#next08" style="color:#497d40;"><span style="color:#497d40;">↓</span></a>]</span><br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0701"|mixiurl %}'>食材市場</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0702"|mixiurl %}'>不動産屋</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0703"|mixiurl %}'>ざっか屋</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0704"|mixiurl %}'>よろず屋</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0705"|mixiurl %}'>ギフト屋</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0706"|mixiurl %}'>美容室</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0707"|mixiurl %}'>プレミアガチャ</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0708"|mixiurl %}'>マイキチ銀行</a><br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
            </div><!--/.section-->
            <div class="section" style="text-align:left;">
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<a name="next08" id="next08"></a>
                <span style="color:#497d40;">{% emoji code="F9B8" %}アイテムBOX</span><span style="color:#497d40;">[<a href="#next09" style="color:#497d40;"><span style="color:#497d40;">↓</span></a>]</span><br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0801"|mixiurl %}'>食材冷蔵庫</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0802"|mixiurl %}'>ざっか置き場</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0803"|mixiurl %}'>どうぐばこ</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0804"|mixiurl %}'>ギフト配送所</a><br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
            </div><!--/.section-->
            <div class="section" style="text-align:left;">
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<a name="next09" id="next09"></a>
                <span style="color:#497d40;">{% emoji code="F99F" %}その他</span><span style="color:#497d40;">[<a href="#next10" style="color:#497d40;"><span style="color:#497d40;">↓</span></a>]</span><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0901"|mixiurl %}'>お店のジャンルを変更する</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0902"|mixiurl %}'>マイミクにギフトを贈る</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0903"|mixiurl %}'>割引券を利用する</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0904"|mixiurl %}'>マイミクを招待する</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0905"|mixiurl %}'>便利なアクセスキー</a><br />
				&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=0907"|mixiurl %}'>FLASH画面が操作できない場合</a><br />
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
            </div><!--/.section-->

	            <div class="section" style="text-align:left;">
	                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<a name="next10" id="next10"></a>
	                <span style="color:#497d40;">{% emoji code="F8C5" %}運営者情報</span><span style="color:#497d40;">[<a href="#next01" style="color:#497d40;"><span style="color:#497d40;">↑</span></a>]</span><br />
					{%*
						&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=1001"|mixiurl %}'>運営会社について</a><br />
					*%}
					&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=1002"|mixiurl %}'>特定商取引法に関する記載</a><br />
					&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=1003"|mixiurl %}'>プライバシーポリシー</a><br />
					{%*
						&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=goldlist"|mixiurl %}'>銀行トップ</a><br />
						&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=recipeconfirm"|mixiurl %}'>レシピ開発完了</a><br />
						&nbsp;<a href='{% "$baseUrl/mobile/kitchenstatic/help?CF_help=1004"|mixiurl %}'>広告出稿のお知らせ</a><br />
					*%}
	                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	                <div style="background:#8bbd82;text-align:center;"><img src="{%$staticUrl%}/apps/kitchen/mobile/img/line.gif" width="230" height="1" /></div>
	            </div><!--/.section-->

            <div class="caution">
                <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
                {% emoji code="F9DC" %}ｻｰﾋﾞｽに関する不明点・疑問を感じた場合は､「<a href='{% "$baseUrl/mobile/kitchenstatic/qa"|mixiurl %}'>よくある質問</a>」をご覧ください｡<br />
            </div><!--/.caution-->
        </div><!--/.inner-->
        <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
        <div class="line" style="background:#8bbd82;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></div>
    </div><!--/.content-->
</div><!--/#help-->
