<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ja" dir="ltr">
<head>
	<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=Shift_JIS" />
	<title>ようこそマイキッチン</title>
	<style type="text/css"><![CDATA[
		a:link{color:#006699;}
		a:visited{color:#006699;}
		a:focus{}
		*{
			{% if $ua==3 %}
				font-size:5;
			{% else %}
				font-size:x-small;
			{% /if %}
			color:#333333;
		}
	]]></style>
</head>
<body style="background:#ffffff;">
	<div id="container" style="{% if $ua==1 %}color:#333333;font-size:x-small;{%/if%}">
